#!/bin/sh /etc/rc.common

START=25

FIRMWARE_IMAGES_DIR="/opt/intel/wave/images"
FAPI_DB_DIR="/opt/intel/wave/db/default"
FAPI_DB_DIR_INSTANCE="/opt/intel/wave/db/instance"

start() {
    echo "INTEL WIFI START" > /dev/console

    export LD_LIBRARY_PATH='/opt/intel/lib:/opt/intel/usr/lib:'
    export PATH=$PATH':/opt/intel/bin:/opt/intel/sbin'

    if [ ! -d "$FAPI_DB_DIR" ]; then
        echo "INTEL WIFI START - createConfig" > /dev/console
        cp $FIRMWARE_IMAGES_DIR/* /lib/firmware
        fapi_wlan_cli createConfig > /dev/console
    fi

    fapi_wlan_cli init > /dev/console

    wifi detect > /etc/config/wireless
}

stop() {
    echo "INTEL WIFI STOP" > /dev/console

    fapi_wlan_cli unInit > /dev/console
}
