O 1 FW
G 1 1 GLOBAL_GID_802_11_PROTOCOL
G 1 2 GLOBAL_AGER_EMULATOR
G 1 3 GLOBAL_GID_AGGREGATION_BUILDER
G 1 4 GLOBAL_GID_TX_HW_ACCELERATORS
G 1 5 GLOBAL_GID_ATF
G 1 6 GLOBAL_GID_BA_ANALYZER
G 1 7 GLOBAL_GID_HW_DRIVERS
G 1 8 GLOBAL_GID_BEACON_HANDLER
G 1 9 GLOBAL_GID_BSS
G 1 10 GLOBAL_GID_BSS_MANAGER
G 1 11 GLOBAL_GID_CHANNEL_SWITCH_MANAGER
G 1 12 GLOBAL_GID_COC
G 1 13 GLOBAL_GID_CSA_MANAGER
G 1 14 GLOBAL_GID_CTS_MANAGER
G 1 15 GLOBAL_GID_DATABASE
G 1 16 GLOBAL_GID_SECURITY_DEBRA
G 1 17 GLOBAL_GID_DEBUG_ENVIRONMENT
G 1 18 GLOBAL_GID_DMA_MANAGER
G 1 19 GLOBAL_GID_DUT
G 1 20 GLOBAL_GID_ERROR_HANDLER
G 1 21 GLOBAL_GID_EVENTS_MANAGER
G 1 22 GID_MTIDLPARSER
G 1 23 GID_LOG
G 1 24 GLOBAL_GID_GIDM_MANAGER
G 1 25 GLOBAL_GID_GROUP_DB
G 1 26 GLOBAL_GID_GROUP_MANAGER
G 1 27 GLOBAL_GID_HDK_CALIBRATIONS_1
G 1 28 GLOBAL_GID_CALIBRATIONS
G 1 29 GLOBAL_GID_HDK_MODULE
G 1 30 GLOBAL_GID_HDK_MODULE_1
G 1 31 GLOBAL_GID_GENRISCS_INTERFACE
G 1 32 GLOBAL_GID_HOST_IF
G 1 33 GLOBAL_GID_PAC
G 1 34 GLOBAL_GID_PAC_1
G 1 35 GLOBAL_GID_RX_QUEUES
G 1 36 GLOBAL_GID_TX_SELECTOR
G 1 37 GLOBAL_GID_UTILS
G 1 38 GLOBAL_GID_INTERFERER_DETECTION
G 1 39 GLOBAL_GID_SYS
G 1 40 GLOBAL_GID_IPC
G 1 41 GLOBAL_GID_KERNEL
G 1 42 GLOBAL_GID_LINK_ADAPTATION
G 1 43 GLOBAL_GID_LOCKER
G 1 44 GLOBAL_GID_LOGGER
G 1 45 GLOBAL_GID_LOWER_MAC
G 1 46 GLOBAL_GID_QUEUE_MGMT
G 1 47 GLOBAL_GID_LOWER_MAC_IF
G 1 48 GLOBAL_GID_MEMORY_MGMT
G 1 49 GLOBAL_GID_NDPA_MANAGER
G 1 50 GLOBAL_GID_PACKET_TRAFFIC_ARBITRATOR
G 1 51 GLOBAL_GID_PAC_MANAGER
G 1 52 GLOBAL_GID_PAUSER
G 1 53 GLOBAL_GID_PERIPHERALS
G 1 54 GLOBAL_GID_SECURITY
G 1 55 GLOBAL_GID_PROCESS_MANAGER
G 1 56 GLOBAL_GID_PROTECTED_DB_LOCK
G 1 57 GLOBAL_GID_PS_MANAGER
G 1 58 GLOBAL_GID_QOS
G 1 59 GLOBAL_GID_QS_MANAGER
G 1 60 GLOBAL_GID_REG_ACCESS
G 1 61 GLOBAL_GID_WAVE500
G 1 62 GLOBAL_GID_RX_CLASSIFIER
G 1 63 GLOBAL_GID_RX_DATA_PATH
G 1 64 GLOBAL_GID_RX_HANDLER
G 1 65 GLOBAL_GID_RX_LIBERATOR
G 1 66 GLOBAL_GID_RX_MANAGER
G 1 67 GLOBAL_GID_RX_POST_PROCESSING
G 1 68 GLOBAL_GID_RX_HW_ACCLERATORS
G 1 69 GLOBAL_GID_RSN
G 1 70 GLOBAL_GID_SENDER
G 1 71 GLOBAL_GID_SERVICES_HANDLER
G 1 72 GLOBAL_GID_SHARED_RAM
G 1 73 GLOBAL_GID_SMPS_MANAGER
G 1 74 GLOBAL_GID_STATION_DB
G 1 75 GID_STATISTICS_MANAGER
G 1 76 GLOBAL_GID_TX_APP
G 1 77 GLOBAL_GID_TINY_KERNEL
G 1 78 GID_TRAINING_MANAGER
G 1 79 GLOBAL_GID_TS_MANAGER
G 1 80 GLOBAL_GID_TX_DATA_PATH
G 1 81 GLOBAL_GID_TX_HANDLER
G 1 82 GLOBAL_GID_TX_MANAGER
G 1 83 GLOBAL_GID_TX
G 1 84 GLOBAL_GID_TX_SEQUENCER
G 1 85 GLOBAL_GID_UPPER_MAC_INTERFACE
G 1 86 GLOBAL_GID_CALENDAR_WHEEL
G 1 87 GLOBAL_GID_VAP_DB
S 1 1 1 117 Assert in file: "ieee_address.c" in line: 117
S 1 1 1 141 Assert in file: "ieee_address.c" in line: 141
S 1 1 1 166 Assert in file: "ieee_address.c" in line: 166
S 1 1 2 169 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 169
S 1 1 2 198 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 198
S 1 1 2 226 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 226
S 1 1 2 255 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 255
S 1 1 2 283 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 283
S 1 1 2 310 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 310
S 1 1 2 338 Assert in file: "Protocol_AirTimeAndDuration.c" in line: 338
S 1 4 1 966 Assert in file: "AggregationBuilder.c" in line: 966
S 1 4 1 990 Assert in file: "AggregationBuilder.c" in line: 990
S 1 4 1 1021 Assert in file: "AggregationBuilder.c" in line: 1021
S 1 4 1 1028 Assert in file: "AggregationBuilder.c" in line: 1028
S 1 4 1 1079 Assert in file: "AggregationBuilder.c" in line: 1079
S 1 4 1 1110 Assert in file: "AggregationBuilder.c" in line: 1110
S 1 4 1 1332 Assert in file: "AggregationBuilder.c" in line: 1332
S 1 4 1 1356 Assert in file: "AggregationBuilder.c" in line: 1356
S 1 7 1 316 Assert in file: "BaAnalyzer.c" in line: 316
S 1 8 4 255 Assert in file: "Beacon_BlockingManager.c" in line: 255
S 1 8 4 256 Assert in file: "Beacon_BlockingManager.c" in line: 256
S 1 8 4 304 Assert in file: "Beacon_BlockingManager.c" in line: 304
S 1 8 4 305 Assert in file: "Beacon_BlockingManager.c" in line: 305
S 1 8 4 554 pScratchPadApiParams->numOfBeaconsTransmitted =%d, BeaconHandlerBlockingDb.lastNumBeaconsTransmitted =%d
S 1 8 3 189 beaconHandlerDeactivateHw for vap:%d
S 1 8 3 221 beaconHandlerSendTemplateWasSetIndication for vap:%d
S 1 8 3 298 beaconHandlerUpdateIEsPdList for vap:%d
S 1 8 3 669 Assert in file: "BeaconHandler.c" in line: 669
S 1 8 3 697 beaconHandlerUpdateIEsPdList Vap Id:%d is active so calling Locker
S 1 8 3 705 beaconHandlerUpdateIEsPdList Vap Id:%d is inactive sending template was set indication
S 1 8 3 743 BeaconHandler_AddVap for vap:%d
S 1 8 3 844 beaconHandlerDeactivateBeacon for vap:%d
S 1 8 3 1043 Assert in file: "BeaconHandler.c" in line: 1043
S 1 8 3 1048 Assert in file: "BeaconHandler.c" in line: 1048
S 1 8 3 1053 Assert in file: "BeaconHandler.c" in line: 1053
S 1 8 3 1058 Assert in file: "BeaconHandler.c" in line: 1058
S 1 8 3 1205 Assert in file: "BeaconHandler.c" in line: 1205
S 1 9 0 226 vBSS_Initialize, send PAC_MANAGER_START_REQ
S 1 12 0 121 Assert in file: "CoC.c" in line: 121
S 1 12 0 122 Assert in file: "CoC.c" in line: 122
S 1 12 0 168 Assert in file: "CoC.c" in line: 168
S 1 12 0 169 Assert in file: "CoC.c" in line: 169
S 1 12 0 212 Assert in file: "CoC.c" in line: 212
S 1 12 0 213 Assert in file: "CoC.c" in line: 213
S 1 12 0 249 Assert in file: "CoC.c" in line: 249
S 1 12 0 327 Assert in file: "CoC.c" in line: 327
S 1 12 0 355 Assert in file: "CoC.c" in line: 355
S 1 12 0 389 Assert in file: "CoC.c" in line: 389
S 1 12 0 568 Assert in file: "CoC.c" in line: 568
S 1 13 0 177 CSA Manager changed from %d to %d
S 1 13 0 616 Fatal Error in file: "csaManager.c"; Fatal Print: CSA Manager Fatal
S 1 13 1 341 CSA Manager STA Manager, STA %d changed from %d to %d
S 1 13 1 1742 Fatal Error in file: "CsaManager_StaManager.c"; Fatal Print: Csa Manager STA Manager Fatal
S 1 13 1 1779 Assert in file: "CsaManager_StaManager.c" in line: 1779
S 1 13 1 1817 Assert in file: "CsaManager_StaManager.c" in line: 1817
S 1 13 2 267 CSA Manager VAP Manager, VAP %d changed from %d to %d
S 1 13 2 1247 Assert in file: "CsaManager_VapManager.c" in line: 1247
S 1 13 2 1643 Fatal Error in file: "CsaManager_VapManager.c"; Fatal Print: CSA Manager VAP Manager Fatal
S 1 15 0 144 Assert in file: "mib.c" in line: 144
S 1 15 0 205 Assert in file: "mib.c" in line: 205
S 1 15 0 441 u16MIB_PutValue: u16ID=%d 
S 1 15 0 485 Assert in file: "mib.c" in line: 485
S 1 16 0 269 Assert in file: "Debra.c" in line: 269
S 1 18 0 69 Assert in file: "DmaManager.c" in line: 69
S 1 18 0 71 Assert in file: "DmaManager.c" in line: 71
S 1 18 1 315 Assert in file: "DmaDriver.c" in line: 315
S 1 18 3 305 Assert in file: "DmaDriver.c" in line: 305
S 1 18 3 323 Assert in file: "DmaDriver.c" in line: 323
S 1 19 0 156 -------- DUT VAP ADDED --------
S 1 19 0 177 Assert in file: "Dut.c" in line: 177
S 1 19 0 183 -------- DUT VAP REMOVED--------
S 1 19 0 200 -------- DUT Dut_HandleSetFixedRateCfm--------
S 1 19 0 287 DUT_CfmToHost  DUT_CfmToHost  DUT_CfmToHost  DUT_CfmToHost
S 1 19 0 313 Dut_MsgCallBackFromProcess
S 1 19 0 378 Assert in file: "Dut.c" in line: 378
S 1 19 1 177 dutResetBb, calling PhyDrv_ResetBB()
S 1 19 1 190 dutStartBb, calling PhyDrv_ReActivateBB()
S 1 19 1 307 dutHwAccessSetDefaultAntenaSet, calling PhyDrv_SetRFMtype(MTLK_RF_MGMT_TYPE_OFF) 
S 1 19 1 376 dutHwAccessSetSpacelessTransmission, dutDB_p->spaceless:%d
S 1 19 1 421 DUT_SendModifyIfsParamsReq, spacing[usec]:%d
S 1 19 1 439 DUT_SendModifyIfsParamsReq
S 1 19 1 498 DUT_SetIfsValue, spacingUsec:%d, ifsn:%d, slotTimer:%d
S 1 19 1 592 Assert in file: "Dut_HwAccess.c" in line: 592
S 1 19 1 605 dutHwAccessGetTxPowerFeedbackReq, dutTxState NOT is DUT_TX_STATE_TRANSMITTING ! return to user
S 1 19 1 650 dutHwAccessGetRxGains, ant:%d, BBGain = %d
S 1 19 1 665 dutHwAccessGetRxGains, ant:%d, lnaActiveValue = %d %d
S 1 19 1 689 dutHwAccessGetRxGains, sysGain[%d] = 0x%x
S 1 19 1 703 dutHwAccessGetRxGains, backoffToDbmOffset = 0x%x
S 1 19 1 710 dutHwAccessGetRxGains, rxGains_p->antRxGains[%d].bbGain = 0x%x
S 1 19 1 812 Assert in file: "Dut_HwAccess.c" in line: 812
S 1 19 1 826 Assert in file: "Dut_HwAccess.c" in line: 826
S 1 19 1 852 Assert in file: "Dut_HwAccess.c" in line: 852
S 1 19 1 868 Assert in file: "Dut_HwAccess.c" in line: 868
S 1 19 1 897 Assert in file: "Dut_HwAccess.c" in line: 897
S 1 19 1 907 dutHwAccessReadTxPowerFeedBack, powerIndex:%x, validSamples:0x%x, txEnabledAntennas:0x%x, phyBw:%d
S 1 19 1 916 dutHwAccessReadTxPowerFeedBack, ant:%d, voltageMeasure:%d
S 1 19 1 925 voltageMeasure, voltageMeasure:%d , ant = %d
S 1 19 2 128 DUT API NOT SUPPORTED !!
S 1 19 2 351 Assert in file: "Dut_Managment.c" in line: 351
S 1 19 2 435 dutStartCalibration, abort request, calibration in process: %d
S 1 19 2 453 dutStartCalibration, start DUT_CALIBRATION_TYPE_ONLINE
S 1 19 2 462 dutStartCalibration, start DUT_CALIBRATION_TYPE_OFFLINE
S 1 19 2 468 Assert in file: "Dut_Managment.c" in line: 468
S 1 19 2 488 Assert in file: "Dut_Managment.c" in line: 488
S 1 19 2 510 Assert in file: "Dut_Managment.c" in line: 510
S 1 19 2 529 DUT_HandleCalibDone, calibration type: %d ended
S 1 19 2 604 Assert in file: "Dut_Managment.c" in line: 604
S 1 19 2 724 Assert in file: "Dut_Managment.c" in line: 724
S 1 19 3 159 Assert in file: "Dut_Tx.c" in line: 159
S 1 19 3 169 dutTxSetState, old state:%d, new state:%d
S 1 19 3 223 dutTxGetPowerVectorPerAnt, index:%d, measuredVoltagePerPower:%d
S 1 19 3 273 ----- dutTxStartTransmision ----
S 1 19 3 288 Error!, dutTxStartTransmision, isChannelSet:%d
S 1 19 3 301 dutTxStartTransmision, DUT_STATUS_TX_START_IS_ONGOING
S 1 19 3 307 dutTxStartTransmision, DUT_STATUS_TX_STOP_IS_ONGOING
S 1 19 3 312 Assert in file: "Dut_Tx.c" in line: 312
S 1 19 3 329 ----- dutTxStopTransmision ---- TxState = 0x%x
S 1 19 3 340 dutTxStopTransmision, packetsTransmitted:%d, packetsProcessed:%d
S 1 19 3 345 dutTxStopTransmision, DUT_STATUS_TX_ALREADY_STOPPED
S 1 19 3 351 dutTxStopTransmision, DUT_STATUS_TX_STOP_IS_ONGOING
S 1 19 3 356 Assert in file: "Dut_Tx.c" in line: 356
S 1 19 3 370 Assert in file: "Dut_Tx.c" in line: 370
S 1 19 3 425 dutTransmitPacketReq, dutDB_p->spaceless:%d
S 1 19 3 435 ---- dutTransmitPacketReq, no free desc
S 1 19 3 477 dutTransmitPacketReq, calling TxPacketsClassifier_SendManagementPacketFromFw, dutDB_p->m_DutTrafficParams.packetsProcessed:%d
S 1 19 3 504 Assert in file: "Dut_Tx.c" in line: 504
S 1 19 3 519 dutHandleCbInTransmittingState transmitPowerVector.numOfTransmitionPerPower[PVpowerToTransmitIndex]:%d
S 1 19 3 540 dutHandleCbInTransmittingState SET NEW POWER AND LENGTH
S 1 19 3 546 dutHandleCbInTransmittingState packetLength:%d
S 1 19 3 547 dutHandleCbInTransmittingState dutPowerAndPacketLength.txPower:%d
S 1 19 3 568 dutHandleCbInTransmittingState, calling TxPacketsClassifier_SendManagementPacketFromFw, m_DutTrafficParams_p->packetsProcessed:%d
S 1 19 3 585 dutHandleTxActionPublicFrameCb, DUT_TX_STATE_TRANSMITTING -> DUT_TX_STATE_IDLE, calling ResourceManager_ReleaseDescriptor
S 1 19 3 622 dutHandleTxActionPublicFrameCb, m_DutTrafficParams_p->trafficState:%d, m_DutTrafficParams_p->txPacketIsOngoing:%d, packetsTransmitted:%d
S 1 19 3 645 Assert in file: "Dut_Tx.c" in line: 645
S 1 21 0 185 Assert in file: "eventsManager.c" in line: 185
S 1 21 0 202 Fatal Error in file: "eventsManager.c"; Fatal Print: EventManager_MaskHwEvent
S 1 21 0 207 Fatal Error in file: "eventsManager.c"; Fatal Print: HwEvents_UnMaskEvent
S 1 21 0 226 Assert in file: "eventsManager.c" in line: 226
S 1 21 0 233 Assert in file: "eventsManager.c" in line: 233
S 1 21 2 203 Assert in file: "eventsManager.c" in line: 203
S 1 21 2 213 Assert in file: "eventsManager.c" in line: 213
S 1 21 2 244 Assert in file: "eventsManager.c" in line: 244
S 1 21 2 254 Assert in file: "eventsManager.c" in line: 254
S 1 24 0 162 Assert in file: "GidmManager.c" in line: 162
S 1 24 0 175 GidmManager_RunStateMachine: Sta = %d, CurrentState = %d, event = %d
S 1 24 0 183 GidmManager_ChangeState: staIndex = %d, newState = %d
S 1 24 0 190 Fatal Error in file: "GidmManager.c"; Fatal Print: GidmManager_IllegalEvent
S 1 24 0 326 Assert in file: "GidmManager.c" in line: 326
S 1 24 0 347 Assert in file: "GidmManager.c" in line: 347
S 1 24 0 351 Assert in file: "GidmManager.c" in line: 351
S 1 24 0 383 Assert in file: "GidmManager.c" in line: 383
S 1 25 0 106 Fatal Error in file: "GroupDatabase.c"; Fatal Print: GroupDb_SetTxPpduModePerUspInGroup
S 1 25 0 147 GroupDb_FillGroupParams: groupIndex is %x. SIDs in group (%d, %d, %d, %d)
S 1 25 0 415 Assert in file: "GroupDatabase.c" in line: 415
S 1 25 0 416 Assert in file: "GroupDatabase.c" in line: 416
S 1 25 0 417 Assert in file: "GroupDatabase.c" in line: 417
S 1 25 0 418 Assert in file: "GroupDatabase.c" in line: 418
S 1 25 0 425 Assert in file: "GroupDatabase.c" in line: 425
S 1 25 0 430 Fatal Error in file: "GroupDatabase.c"; Fatal Print: GroupDb_UpdateMuGroupAttributes invalid option
S 1 25 0 470 GroupDb_ResetGroupEntry: groupIndex is %X
S 1 25 0 507 GroupDB_Init
S 1 26 0 1021 Assert in file: "GroupManager.c" in line: 1021
S 1 26 0 1042 groupManagerAddStation: Adding station %d
S 1 26 0 1051 groupManagerAddStation: station id %d is not allowed
S 1 26 0 1094 groupManagerRemoveStation: received on SID %d
S 1 26 0 1143 groupManagerTrainingTimer: stations timer event, handle index %d
S 1 26 0 1161 groupManagerTrainingTimer: groups timer event, handle index %d
S 1 26 0 1351 groupManagerGroupsMarksReceived: word in Bitmap %d, stations waiting for group marks in this word 0x%x
S 1 26 0 1365 Assert in file: "GroupManager.c" in line: 1365
S 1 26 0 1451 groupManagerStationNssHasChanged: station index %d. New nss %d. virtual group removed %d
S 1 26 0 1468 groupManagerStationNssHasChanged: station index %d. New nss %d. active group removed %d
S 1 26 0 1510 groupManagerAddGroupConfirmation - groupIdx %d
S 1 26 0 1600 groupManagerRemovedGroupConfirmation: from LA on group index %d. group state %d
S 1 26 0 1642 groupManagerGroupsHasFailed: group index %d
S 1 26 0 1732 Fatal Error in file: "GroupManager.c"; Fatal Print: groupManagerResetMultiUserOperation
S 1 26 0 1748 Fatal Error in file: "GroupManager.c"; Fatal Print: groupManagerResetMultiUserOperation
S 1 26 0 1795 Fatal Error in file: "GroupManager.c"; Fatal Print: groupManagerSetMultiUserOperationCfm
S 1 26 0 1833 Assert in file: "GroupManager.c" in line: 1833
S 1 26 0 1834 Assert in file: "GroupManager.c" in line: 1834
S 1 26 0 1889 groupManagerSetMultiUserOperation: current MU state = %d
S 1 26 0 1904 groupManagerSetMultiUserOperation: MU is already active
S 1 26 0 1926 groupManagerSetMultiUserOperation: MU is already deactivated
S 1 26 0 1958 groupManagerSetMuFixedRate: isFixedRate %d
S 1 26 0 2158 Assert in file: "GroupManager.c" in line: 2158
S 1 26 0 2233 Assert in file: "GroupManager.c" in line: 2233
S 1 26 0 2386 groupManagerStationEventRemoveStationInActiveOrTempActive: on station index %d
S 1 26 0 2667 groupManagerStationEventRemoveGroupDueToStationInNotifying: group index %d, station index %d
S 1 26 0 2736 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Configure station for selector as SU.
S 1 26 0 2751 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Station is only a member in notifying groups
S 1 26 0 2762 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Station is only a member in virtual groups
S 1 26 0 2772 groupManagerStationEventRemoveGroupDueToStationInProbing: group index %d, station index %d. Station is not a member of any group. Moving to HALT
S 1 26 0 2835 groupManagerStationEventRemoveGroupInTempActive: Removing groupIndex %d. stationIndex %d is tempActive of the group
S 1 26 0 2869 groupManagerStationEventRemoveGroupInTempActive: Removing groupIndex %d which is primary group of stationIndex %d. station is tempActive of another group and part of more active groups
S 1 26 0 2882 groupManagerStationEventRemoveGroupInTempActive: Removing groupIndex %d which is primary group of stationIndex %d. station is tempActive and member of only probing groups
S 1 26 0 2991 groupManagerStationEventRemoveGroupDueToStationInSuValWaitingLa: groupIndex %d, station index %d
S 1 26 0 2997 groupManagerStationEventRemoveGroupDueToStationInSuValWaitingLa: the primary group of station waiting to start SU val is removed, cancel SU val
S 1 26 0 3040 groupManagerStationEventRemoveGroupDueToStationInSingleUserValidation: group index %d, station index %d, primary group index = %d
S 1 26 0 3130 groupManagerStationEventRemoveGroupInNotifying: groupIndex %d, stationIndex %d
S 1 26 0 3182 groupManagerStationEventRemoveGroupInProbing: Station %d is primary of probing group %d which is beeing removed. configure station in selector to SU
S 1 26 0 3198 groupManagerStationEventRemoveGroupInProbing: Station %d remains member of only notify groups
S 1 26 0 3206 groupManagerStationEventRemoveGroupInProbing: Station %d is not a member of any active/probing/notify group
S 1 26 0 3562 groupManagerStationEventActivateGroupInProbing: group idx %d, SID %d 
S 1 26 0 3579 groupManagerStationEventActivateGroupInProbing: tempPrimaryGroup before activation is %d 
S 1 26 0 3948 groupManagerStationEventActivateGroupInSingleUserValidationEnded: SID %d, configured to be primary of group %d
S 1 26 0 4138 groupManagerStationEventSuValStartCfmInSuValWaitingLa: SID %d configured to SU mode
S 1 26 0 4282 groupManagerStationEventSuValEndCfmInSuValSucceeded: SID %d, configured to work in MU mode, primary for group %d
S 1 26 0 4587 Assert station %d state: %d
S 1 26 0 4589 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in group manager station event
S 1 26 0 4619 Ingore event station %d state: %d
S 1 26 0 4651 Remove Group event update station bitmap station %d state: %d group %d
S 1 26 0 4686 Add Group event update station bitmap station %d state: %d group %d
S 1 26 0 4767 groupManagerRunStationStateMachine station %d state: %d event %d
S 1 26 0 4781 Assert in file: "GroupManager.c" in line: 4781
S 1 26 0 4821 groupManagerChangeStationState: Change station %d state: old state %d new state %d
S 1 26 0 4871 group manager, Send Confirmation, Client %d, stationIndex %d
S 1 26 0 4909 groupManagerRemoveAllStationVirtualGroups: SID %d, virtualGroupsBitmap 0x%x
S 1 26 0 5016 Fatal Error in file: "GroupManager.c"; Fatal Print: Station was not found in virtual group
S 1 26 0 5063 Fatal Error in file: "GroupManager.c"; Fatal Print: Station was not found in group
S 1 26 0 5109 groupManagerSetStationPrimaryBitInGroupsDb: stationIndex %d, groupIndex %d, primary stations bitmap after adding new primary 0x%x
S 1 26 0 5144 groupManagerConfigureStationAsPrimaryInGroup: station index %d configured primary for selector with group index %d
S 1 26 0 5220 groupManagerClearStationPrimaryInGroup: station index %d, group index %d, primaryStationsbitmap for this group 0x%x
S 1 26 0 5242 Fatal Error in file: "GroupManager.c"; Fatal Print: Trying to delete staticGroup !
S 1 26 0 5280 groupManagerSendEndSingleUserValidationMessage: to LA on SID %d
S 1 26 0 5316 groupManagerTriggerRemoveStationInTraining: sent to Training mng on SID %d
S 1 26 0 5446 groupManagerFindBestGroup: group with best mark  is %d
S 1 26 0 5527 groupManagerRemoveGroupInActive: group index: %d, haltNeeded: %d 
S 1 26 0 5536 groupManagerRemoveGroupInActive: station has more active groups. bitmap of groups 0x%x
S 1 26 0 5711 groupManagerTryToStartNewSingleUserValidation: Single User Validation bitmap %d, SID %d
S 1 26 0 5716 groupManagerTryToStartNewSingleUserValidation: Single User Validation bitmap after adding new one %d, SID %d
S 1 26 0 5726 groupManagerTryToStartNewSingleUserValidation: start single user val on SID %d
S 1 26 0 5762 groupManagerSendGroupsMarksMessage
S 1 26 0 5816 groupManagerStationExitActiveState: station has more probing groups
S 1 26 0 5835 groupManagerStationExitActiveState: station has more notifying groups
S 1 26 0 5846 groupManagerStationExitActiveState: can remain in single user state. isHaltNeeded %d, virtual groups bitmap 0x%x
S 1 26 0 5854 groupManagerStationExitActiveState: station is moving to HALT
S 1 26 0 5913 groupManagerStartNewSingleUserValidation: all stations candidates for su validation bitmap 0x%x
S 1 26 0 5919 groupManagerStartNewSingleUserValidation: SID %d chosen next for SU validation, moving to Su val pending
S 1 26 0 5926 groupManagerStartNewSingleUserValidation: no candidates for su val found
S 1 26 0 6006 groupManagerConfigureNewGroupForSelector: numOfStations %d
S 1 26 0 6011 groupManagerConfigureNewGroupForSelector: sid %d
S 1 26 0 6022 groupManagerConfigureNewGroupForSelector: Configure primary SID %d for group %d in Selector
S 1 26 0 6222 Assert in file: "GroupManager.c" in line: 6222
S 1 26 0 6224 groupManagerGroupEventStartNotifying: group index for notification %d, virtual group index %d
S 1 26 0 6268 groupManagerGroupEventStartNotifying: station index %d, group index %d, uspVector 0x%x
S 1 26 0 6398 groupManagerGroupEventRemoveGroupInProbing: group %d
S 1 26 0 6438 groupManagerGroupEventRemoveGroupInActive: group %d
S 1 26 0 6491 groupManagerGroupEventNotificationCfmInProbingNotifying: on SID %d, groupIdx %d, notifStatus %d
S 1 26 0 6513 groupManagerGroupEventNotificationCfmInProbingNotifying: All notifications arrived successfully
S 1 26 0 6543 groupManagerGroupEventNotificationCfmInProbingNotifying: timer started after static group generation
S 1 26 0 6567 groupManagerGroupEventNotificationCfmInProbingNotifying: All notifications arrived - last FAILED
S 1 26 0 6599 groupManagerGroupEventNotificationCfmInProbingNotifying: one of notification failed, more notifications will arrive - start remove group now
S 1 26 0 7004 groupManagerGroupEventRemoveGroupCfmInRemovingWaitingForLaCfm
S 1 26 0 7056 groupManagerGroupEventProbingResultsAreReadyInProbing: group Idx %d, group mark %d, states (%d, %d, %d, %d)
S 1 26 0 7079 groupManagerGroupEventProbingResultsAreReadyInProbing: for group %d station %d mark is below threshold! (%d, %d, %d, %d)
S 1 26 0 7095 groupManagerGroupEventProbingResultsAreReadyInProbing: Group mark is below threshold!!!
S 1 26 0 7102 groupManagerGroupEventProbingResultsAreReadyInProbing: num of active groups %d, num of removing active groups %d
S 1 26 0 7125 groupManagerGroupEventProbingResultsAreReadyInProbing: active groups are full. Worth active group index %d, group mark %d, probing grop mark %d
S 1 26 0 7143 groupManagerGroupEventProbingResultsAreReadyInProbing: Send activateGroup event to SID %d
S 1 26 0 7170 groupManagerGroupEventProbingResultsAreReadyInProbing: Valid probing group found. Group idx %d. will be active
S 1 26 0 7200 groupManagerGroupEventProbingResultsAreReadyInProbing: Probing group idx %d is not valid. No primary station availabe for it. Will be removed
S 1 26 0 7252 Ignore 'probing results ready event' for group %d (static group) in state: %d
S 1 26 0 7258 Assert group %d state: %d on probing results ready event
S 1 26 0 7260 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in group manager group event
S 1 26 0 7388 Assert group %d state: %d
S 1 26 0 7390 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in group manager group event
S 1 26 0 7421 Ignore event group %d state: %d
S 1 26 0 7459 groupManagerRunGroupStateMachine group %d state: %d event %d
S 1 26 0 7488 groupManagerChangeGlobalState: current state: %d, new state %d
S 1 26 0 7522 groupManagerChangeGroupState: Change group %d state: old state %d new state %d
S 1 26 0 7564 groupManagerSendRemoveGroupMessage: groupIndex %d
S 1 26 0 7609 groupManagerSendAddGroupMessage: send add group to LA
S 1 26 0 7647 groupManagerLockGroup: sending lock request to Locker on group %d
S 1 26 0 7660 groupManagerLockGroup: lock was already sent. Adding group %d to waiting list. waitingLock bitmap 0x%x
S 1 26 0 7720 groupManagerGroupRemoveGroupInProbingNotifying: station %d is removed during probing, send stopTx to GIDM Mng
S 1 26 0 7734 groupManagerGroupRemoveGroupInProbingNotifying: send stopTx on station %d to GIDM Mng, notification cancelled
S 1 26 0 7750 groupManagerGroupRemoveGroupInProbingNotifying: station index received %d. notification status of the group (%d, %d, %d, %d)
S 1 26 0 7805 groupManagerHandleNextGroupWaitingForLock: group  %d
S 1 26 0 7843 groupManagerFinishGroupRemovalProcess: group idx %d, removingGroupsBitmap 0x%x, occupiedGroupsBitmap 0x%x, numberOfOccupiedGroups %d, activeGroupsBitmap 0x%x, probingGroupsBitmap 0x%x
S 1 26 0 7859 groupManagerFinishGroupRemovalProcess: group was in active state. After clear bits: activeGroupsBitmap 0x%x, numberOfActiveGroups %d, num of removing groups in active %d
S 1 26 0 7868 groupManagerFinishGroupRemovalProcess: group was in probing state. After clear bits: probingGroupsBitmap 0x%x, numberOfProbingGroups %d
S 1 26 0 7888 groupManagerFinishGroupRemovalProcess: group failed
S 1 26 0 7900 groupManagerFinishGroupRemovalProcess: group not failed
S 1 26 0 7950 groupManagerFinishGlobalRemovalProcess: sending multi user operation setting cfm
S 1 26 0 7961 groupManagerFinishGlobalRemovalProcess: starting static group generation
S 1 26 0 8005 groupManagerTryToFindNewGroupForProbing: probing groups %d, occupied groups %d
S 1 26 0 8018 groupManagerTryToFindNewGroupForProbing: virtuals db bitmap 0x%x
S 1 26 0 8086 groupManagerTryToFindNewGroupForProbing: virtual groups bitmap candidates for probing 0x%x
S 1 26 0 8102 groupManagerTryToFindNewGroupForProbing: found best virtual group index for probing %d
S 1 26 0 8440 GroupManager_TrainingWasStoppedConfirmation
S 1 26 0 8463 GroupManager_TrainingWasStoppedConfirmation: send multi user operation setting cfm
S 1 26 0 8481 GroupManager_TrainingWasStoppedConfirmation: Starting To create static group
S 1 26 0 8501 Fatal Error in file: "GroupManager.c"; Fatal Print: Assert in GroupManager_TrainingWasStoppedConfirmation
S 1 26 0 8600 GroupManager_TrainingResultsWereReceived: entry num %d
S 1 26 0 8606 GroupManager_TrainingResultsWereReceived: invalid	StaIdx %d
S 1 26 0 8614 GroupManager_TrainingResultsWereReceived: staIdx %d, invalid combination. 
S 1 26 0 8643 GroupManager_TrainingResultsWereReceived: staId %d - (%d, %d, %d, %d).
S 1 26 0 8645 GroupManager_TrainingResultsWereReceived: MCS - (%d, %d, %d, %d)
S 1 26 0 8647 GroupManager_TrainingResultsWereReceived: groupGrade - %d, singleNsts %d, doubleNsts %d
S 1 26 0 8680 GroupManager_TrainingResultsWereReceived: Nss bitmap: 0x%x
S 1 26 0 8693 GroupManager_TrainingResultsWereReceived:occupied groupId %d, groupStations (%d,%d,%d,%d)
S 1 26 0 8705 GroupManager_TrainingResultsWereReceived: Group Exists in occupied DB: EntryIdx %d, staId %d, groupIndex %d
S 1 26 0 8727 GroupManager_TrainingResultsWereReceived: virtualGroupId %d, groupStations (%d,%d,%d,%d)
S 1 26 0 8747 GroupManager_TrainingResultsWereReceived: Group Exists in VIRTUAL DB: EntryIdx %d, staId %d, virtualGroupIdx %d
S 1 26 0 8765 GroupManager_TrainingResultsWereReceived: Found free spot %d in virtual DB
S 1 26 0 8776 GroupManager_TrainingResultsWereReceived: Virtual DB is full!
S 1 26 0 8792 GroupManager_TrainingResultsWereReceived: new group will overwrite groupIdx %d in virtual DB. Prev group grade %d, new group grade %d
S 1 26 0 8940 GroupManager_GidmNotificationConfirmation: SID %d, notify group idx %d
S 1 26 0 9274 Assert in file: "GroupManager.c" in line: 9274
S 1 26 0 9506 groupManagerCreateMuStaticGroup: preparing for static group generation
S 1 26 0 9541 groupManagerDeleteMuStaticGroup
S 1 27 0 164 AfePhase: Executing Calibration
S 1 27 0 171 AfePhase: run time =%d
S 1 27 0 215 AfePhase: initCalibration() nCB mode
S 1 27 0 224 AfePhase: initCalibration() CB mode
S 1 27 0 290 AfePhase: AfePhase_Logic() initValue[%d] = h%x
S 1 27 0 317 Calibration Step delay[0] = h%x delay[1] = h%x delay[2] = h%x
S 1 27 0 318 Tx: res[0] = h%x res[1] = h%x res[2] = h%x
S 1 27 0 319 Rx: res[0] = h%x res[1] = h%x res[2] = h%x
S 1 27 0 386 Assert in file: "AfePhaseClbrHndlr.c" in line: 386
S 1 27 0 399 ant1equal = %d times, ant2equal= %d
S 1 27 0 452 Assert in file: "AfePhaseClbrHndlr.c" in line: 452
S 1 27 0 458 diff_array_rx[%d] = %d rxDelay = %d
S 1 27 0 459 diff_array_tx[%d] = %d 
S 1 27 5 651 START AFE CALIBRATION
S 1 27 5 680 retVal=%d, packetMod=%d
S 1 27 5 690 packetMod=%d,pElements->results.offlineModulationType=%d 
S 1 27 5 694 exit ALB mode, calibration end!
S 1 27 5 701 LastClRunTime: %d
S 1 27 5 761 QBF calibration finished
S 1 27 5 792 Setting TPC: %d, for extPa = %d
S 1 27 5 885 Assert in file: "BeamFormingClbrHndlr.c" in line: 885
S 1 27 5 888 agcGains(ant %d). lnaIndx = %d pgc1Indx = %d pgc2Indx = %d pgc3Indx = %d
S 1 27 5 900 Send packet %d => %d
S 1 27 5 913 Packet sent from ant %d to ant %d
S 1 27 5 924 BM calibration fail! number of recorded bins from sessions not identical
S 1 27 5 946 StopRisc called
S 1 27 5 1002 StartRisc called
S 1 27 5 1056 TRSW: %x %x %x
S 1 27 5 1206 Registers values were not saved, cannot restore them
S 1 27 5 1207 Assert in file: "BeamFormingClbrHndlr.c" in line: 1207
S 1 27 5 1212 Stop risc
S 1 27 5 1234 Run risc
S 1 27 5 1279 Assert in file: "BeamFormingClbrHndlr.c" in line: 1279
S 1 27 5 1333 BF Calibration Failed!! could not achieve a good channel
S 1 27 5 1353 triggerTB
S 1 27 5 1433 Record channel failed!!! CRC error
S 1 27 5 1543 Assert in file: "BeamFormingClbrHndlr.c" in line: 1543
S 1 27 5 1550 Record %d bins
S 1 27 5 1911 Assert in file: "BeamFormingClbrHndlr.c" in line: 1911
S 1 27 5 2001 Assert in file: "BeamFormingClbrHndlr.c" in line: 2001
S 1 27 5 2022 START AGC GAINS CALIBRATION
S 1 27 5 2035 START K CALIBRATION
S 1 27 5 2063 START AGC OFFSET CALIBRATION
S 1 27 5 2073 START TX OFFSET CALIBRATION
S 1 27 5 2088 exit ALB mode, calibration end!, calStatus = %X
S 1 27 5 2118 Start K%d calibration, CB=%d
S 1 27 5 2220 relative gain = %d
S 1 27 5 2245 Assert in file: "BeamFormingClbrHndlr.c" in line: 2245
S 1 27 5 2260 Warning: working at %d instead of 15 dB backoff
S 1 27 5 2268 BF Calibration Failed !! Attenuation between antennas too high:%d
S 1 27 5 2309 Send packet: Ant%d->Ant%d
S 1 27 5 2310 trSwTxAnt: %d
S 1 27 5 2508 Assert in file: "BeamFormingClbrHndlr.c" in line: 2508
S 1 27 5 2575 digital gain %d
S 1 27 5 2588 running for gains : LnaIndex %d, pgc1Index %d, pgc2Index %d,pgc3Index %d
S 1 27 5 2842 Assert in file: "BeamFormingClbrHndlr.c" in line: 2842
S 1 27 5 3042 Assert in file: "BeamFormingClbrHndlr.c" in line: 3042
S 1 27 5 3092 BF Calibration Failed!! could not achieve a good channel
S 1 27 5 3168 DisTxCancel
S 1 27 5 3175 EnTxCancel
S 1 27 9 650 START AFE CALIBRATION
S 1 27 9 679 retVal=%d, packetMod=%d
S 1 27 9 689 packetMod=%d,pElements->results.offlineModulationType=%d 
S 1 27 9 693 exit ALB mode, calibration end!
S 1 27 9 700 LastClRunTime: %d
S 1 27 9 760 QBF calibration finished
S 1 27 9 791 Setting TPC: %d, for extPa = %d
S 1 27 9 884 Assert in file: "BeamFormingClbrHndlr.c" in line: 884
S 1 27 9 887 agcGains(ant %d). lnaIndx = %d pgc1Indx = %d pgc2Indx = %d pgc3Indx = %d
S 1 27 9 899 Send packet %d => %d
S 1 27 9 912 Packet sent from ant %d to ant %d
S 1 27 9 923 BM calibration fail! number of recorded bins from sessions not identical
S 1 27 9 945 StopRisc called
S 1 27 9 1001 StartRisc called
S 1 27 9 1055 TRSW: %x %x %x
S 1 27 9 1205 Registers values were not saved, cannot restore them
S 1 27 9 1206 Assert in file: "BeamFormingClbrHndlr.c" in line: 1206
S 1 27 9 1211 Stop risc
S 1 27 9 1233 Run risc
S 1 27 9 1278 Assert in file: "BeamFormingClbrHndlr.c" in line: 1278
S 1 27 9 1332 BF Calibration Failed!! could not achieve a good channel
S 1 27 9 1352 triggerTB
S 1 27 9 1434 Record channel failed!!! CRC error
S 1 27 9 1542 Assert in file: "BeamFormingClbrHndlr.c" in line: 1542
S 1 27 9 1548 Record %d bins
S 1 27 9 1903 Assert in file: "BeamFormingClbrHndlr.c" in line: 1903
S 1 27 9 1994 Assert in file: "BeamFormingClbrHndlr.c" in line: 1994
S 1 27 9 2015 START AGC GAINS CALIBRATION
S 1 27 9 2028 START K CALIBRATION
S 1 27 9 2056 START AGC OFFSET CALIBRATION
S 1 27 9 2066 START TX OFFSET CALIBRATION
S 1 27 9 2081 exit ALB mode, calibration end!, calStatus = %X
S 1 27 9 2111 Start K%d calibration, CB=%d
S 1 27 9 2213 relative gain = %d
S 1 27 9 2238 Assert in file: "BeamFormingClbrHndlr.c" in line: 2238
S 1 27 9 2253 Warning: working at %d instead of 15 dB backoff
S 1 27 9 2261 BF Calibration Failed !! Attenuation between antennas too high:%d
S 1 27 9 2302 Send packet: Ant%d->Ant%d
S 1 27 9 2303 trSwTxAnt: %d
S 1 27 9 2501 Assert in file: "BeamFormingClbrHndlr.c" in line: 2501
S 1 27 9 2568 digital gain %d
S 1 27 9 2581 running for gains : LnaIndex %d, pgc1Index %d, pgc2Index %d,pgc3Index %d
S 1 27 9 2835 Assert in file: "BeamFormingClbrHndlr.c" in line: 2835
S 1 27 9 3035 Assert in file: "BeamFormingClbrHndlr.c" in line: 3035
S 1 27 9 3085 BF Calibration Failed!! could not achieve a good channel
S 1 27 9 3161 DisTxCancel
S 1 27 9 3168 EnTxCancel
S 1 28 0 178 LPF: Executing Calibration.
S 1 28 0 190 LPF: Finished Calibration. Ret Val = %d, Run Time = %d
S 1 28 0 216 LPF_LoadResults(): Ant %u lpfI=%u lpfQ=%u
S 1 28 1 124 Assert in file: "LpfClbrUtils.c" in line: 124
S 1 28 5 140 MsSsiAdc: Executing Calibration
S 1 28 5 442 MsSsiAdc verifyCalibrationResults: antNum = %d Status = %d
S 1 28 5 443 MsSsiAdc verifyCalibrationResults: statusGain = %d gainDist = %d
S 1 28 5 444 MsSsiAdc verifyCalibrationResults: statusOffset = %d offsetDist = %d
S 1 28 6 114 RficBias: Executing Calibration
S 1 28 6 143 RficBias: status = %d, statusRpos = %d, statusRneg = %d
S 1 28 6 144 RficBias: Rint = %d Rpos = %d, Rneg = %d
S 1 28 6 154 RficBias: Finished Calibration. Run Time = %d
S 1 28 6 215 RficBias_calibrateRpos:Failed to reach comparator SUCCESS
S 1 28 6 276 RficBias_calibrateRneg:Failed to reach comparator SUCCESS
S 1 28 6 394 RficBias_LoadResults(): Rint=%d
S 1 28 7 127 RssiDcOffset: Executing Calibration
S 1 28 7 349 RssiDcOffset min_search !!! DEBUG !!!: delta=0: antenna %d
S 1 28 7 445 RssiDcOffset: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 28 7 453 RssiDcOffset: AntNum = %d Status = %d
S 1 28 7 461 RssiDcOffset OFFSETS: I1 = %d I2 = %d I3 = %d
S 1 28 7 462 RssiDcOffset OFFSETS: I4 = %d I5 = %d
S 1 28 7 463 RssiDcOffset OFFSETS: Q1 = %d Q2 = %d Q3 = %d
S 1 28 7 464 RssiDcOffset OFFSETS: Q4 = %d Q5 = %d
S 1 28 7 472 RssiDcOffset DATA OUT OFFSETS: I1 = %d I2 = %d I3 = %d
S 1 28 7 473 RssiDcOffset DATA OUT OFFSETS: I4 = %d I5 = %d
S 1 28 7 474 RssiDcOffset DATA OUT OFFSETS: Q1 = %d Q2 = %d Q3 = %d
S 1 28 7 475 RssiDcOffset DATA OUT OFFSETS: Q4 = %d Q5 = %d
S 1 28 8 123 RSSI Path: Executing Calibration
S 1 28 8 153 RSSI Path Calibration:Antenna %d status %d
S 1 28 8 170 RSSI Path Calibration:Finished Calibration. ret = %d, Run Time = %d
S 1 28 8 210 RSSI Path calibrateSingleAntenna(): Antenna %d
S 1 28 8 222 Assert in file: "RssiPathClbrHndlr.c" in line: 222
S 1 28 8 244 RSSI Path calibrateSingleAntenna:Rssi = %d
S 1 28 8 283 RSSI Path calibrateSingleAntenna():Index = %d,Rssi = %d
S 1 28 8 308 RSSI Path calibrateSingleAntenna:Partitioned Section =%d Index = %d,Rssi = %d
S 1 28 8 468 Assert in file: "RssiPathClbrHndlr.c" in line: 468
S 1 28 8 512 RSSI Path measureRssi: measureRssi() time = %d
S 1 28 8 588 Assert in file: "RssiPathClbrHndlr.c" in line: 588
S 1 28 8 602 RSSI CalcDerivative: section=%d a=%d b=%d
S 1 28 8 618 RSSI Path calcDerivative(): time = %d
S 1 28 8 760 GenerateRssiTable:Dynamic Range low =%d high %d
S 1 28 8 761 GenerateRssiTable:First Calibrated Power In Dynamic Range: %d
S 1 28 8 762 GenerateRssiTable:Last Calibrated Power In Dynamic Range: %d
S 1 28 8 804 Assert in file: "RssiPathClbrHndlr.c" in line: 804
S 1 28 8 849 Assert in file: "RssiPathClbrHndlr.c" in line: 849
S 1 28 8 902 RSSI path VerifyResult: AntNum %d
S 1 28 8 938 RSSI path VerifyResult: transmit power %d  meaured rssi %d  calibrated power %d
S 1 28 8 963 RSSI path VerifyResult: Dynamic range %d low_power %d high_power %d
S 1 28 8 972 RSSI path VerifyResult: Status Fail, dynamicRange below minimum allowed %d
S 1 28 8 981 RSSI path VerifyResult: rssiPowerDiff %d maxDiffIsInPower %d
S 1 28 8 990 RSSI path VerifyResult: Status Fail, rssiPowerDiff exceeds maximum allowed %d
S 1 28 8 1005 RSSI path VerifyResult: measurementVariation %d min_measure %d max_measure %d
S 1 28 8 1014 RSSI path VerifyResult: Status Fail, measurementVariation exceeds maximum allowed %d
S 1 28 8 1030 RSSI Path VerifyResult(): ret %d status %d
S 1 28 8 1038 RSSI Path VerifyResult(): verify run time %d
S 1 28 8 1055 Assert in file: "RssiPathClbrHndlr.c" in line: 1055
S 1 28 28 279 RSSI Path: Executing Calibration
S 1 28 28 290 Assert in file: "RssiPathClbrHndlr.c" in line: 290
S 1 28 28 596 Assert in file: "RssiPathClbrHndlr.c" in line: 596
S 1 28 28 628 Assert in file: "RssiPathClbrHndlr.c" in line: 628
S 1 28 28 646 Assert in file: "RssiPathClbrHndlr.c" in line: 646
S 1 28 29 280 RSSI Path: Executing Calibration
S 1 28 29 291 Assert in file: "RssiPathClbrHndlr.c" in line: 291
S 1 28 29 597 Assert in file: "RssiPathClbrHndlr.c" in line: 597
S 1 28 29 629 Assert in file: "RssiPathClbrHndlr.c" in line: 629
S 1 28 29 647 Assert in file: "RssiPathClbrHndlr.c" in line: 647
S 1 28 9 351 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 351
S 1 28 9 657 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 657
S 1 28 9 671 Assert in file: "RxDcOffsetClbrHndlr.c" in line: 671
S 1 28 10 119 Rx IQ: Executing Calibration
S 1 28 10 197 RxIQ ALGO:Finished Calibration. Ret Code = %d, Run Time = %d
S 1 28 10 230 Rx IQ: Restore Done. Duration = %d
S 1 28 10 285 Rx IQ: Init Done. Duration = %d
S 1 28 10 439 RxIQ error verification for ANTENNA %d  w1 = %d w2 = %d
S 1 28 10 440 RxIQ error verification II = %d QQ = %d IQ = %d
S 1 28 10 457 RxIQ verifyCalibrationResults: error verification Status = %d w1_Error= %d w2_Error= %d
S 1 28 14 132 use ssb loop %d
S 1 28 14 182 Tx IQ: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 28 14 264 Tx IQ initAntennaOnlineIterationDetails: last antenna = %d
S 1 28 14 374 TXIQ calibrateSingleAntenna:RF Ant %d,LoopBackRxAnt %d, LoopBackTxAnt %d
S 1 28 14 436 Tx IQ calibrateSingleAntenna(): Restore Hw Registers Run Time = %d
S 1 28 14 493 amplitude: %d digital gain: %d
S 1 28 14 494 Tx IQ: Init Done. Duration = %d
S 1 28 14 522 Tx IQ: Restore Done. Duration = %d
S 1 28 14 587 setTxIqAdaptiveGain. acc result(II) = %d. accumNorm = %d
S 1 28 14 606 Accumulator measurement is low - increase gain. course = %d
S 1 28 14 618 Accumulator measurement is high - decrease gain. course = %d
S 1 28 14 639 old Amp: %d new Amp: %d old digital: %d new digital: %d
S 1 28 14 660 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 660
S 1 28 14 677 a: %d phiSquared: %d IMR: %d
S 1 28 14 811 Tx IQ calibrateAndVerifySingleBin:Bin %d
S 1 28 14 831 Reference energy (bin %d - %d): %d
S 1 28 14 883 Tx IQ calibrateAndVerifySingleBin(): Run Time = %d
S 1 28 14 942 tx ant: %d. rx ant: %d. II: %d QQ: %d IQ: %d
S 1 28 14 946 Tx IQ calcMinimumCoeffcientsValue(): a energy x0=%d x1=%d x2=%d
S 1 28 14 947 Tx IQ calcMinimumCoeffcientsValue(): a energy x3=%d x4=%d x5=%d
S 1 28 14 948 Tx IQ calcMinimumCoeffcientsValue(): a energy x6=%d x7=%d x8=%d
S 1 28 14 967 tx ant: %d. rx ant: %d. II: %d QQ: %d IQ: %d
S 1 28 14 971 Tx IQ calcMinimumCoeffcientsValue(): b energy x0=%d x1=%d x2=%d
S 1 28 14 972 Tx IQ calcMinimumCoeffcientsValue(): b energy x3=%d x4=%d x5=%d
S 1 28 14 973 Tx IQ calcMinimumCoeffcientsValue(): b energy x6=%d x7=%d x8=%d
S 1 28 14 982 Tx IQ calcMinCoeffcientValues(): a=%d, b=%d
S 1 28 14 1172 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1172
S 1 28 14 1195 Tx IQ VerifyCalibrationResults(): Energy(log) = %d
S 1 28 14 1208 Tx IQ verifyCalibrationResults():Energy exceeds max TH = %d status = %d
S 1 28 14 1225 Tx IQ verifyCalibrationResults(): Single bin verify Run Time = %d
S 1 28 14 1250 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1250
S 1 28 14 1254 Verify. a = %d b = %d
S 1 28 14 1258 Verify. tx ant: %d. rx ant: %d. II: %d QQ: %d IQ: %d
S 1 28 14 1265 Verify. IMR(dB) = %d
S 1 28 14 1278 Tx IQ verifyCalibrationResults():Energy exceeds max TH = %d status = %d
S 1 28 14 1295 Tx IQ verifyCalibrationResults(): Single bin verify Run Time = %d
S 1 28 14 1434 Tx IQ fixFailedBins(): Can't fix bins - calibration of all bins in range failed !!!
S 1 28 14 1450 Tx IQ fixFailedBins():Minimal Coefficient Values: bin=%d a=%d, b=%d
S 1 28 14 1461 Tx IQ fixFailedBins(): Failed bins %d, Fixed bins %d
S 1 28 14 1481 Tx IQ fixFailedBins(): Range sign %d, Run Time = %d
S 1 28 14 1595 Tx IQ calcInterpolatedCoefficients(): Interpolation between 2 bins [0,1] Run Time = %d
S 1 28 14 1645 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1645
S 1 28 14 1752 TxIQClbr_StoreResults(): CB mode %d
S 1 28 14 1773 TxIQClbr_StoreResults(): binIndex %d a=%d b=%d
S 1 28 14 1785 TxIQClbr_StoreResults(): binIndex %d a=%d b=%d
S 1 28 14 1930 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1930
S 1 28 14 1953 Assert in file: "TxIQMismatchClbrHndlr.c" in line: 1953
S 1 28 14 1971 ant: %d bin: %d a_k: %d b_k: %d
S 1 28 14 1986 x: %d, p/2: %d, e: %d
S 1 28 14 2001 F00: %d, F01: %d, F10: %d, F11: %d
S 1 28 14 2018 e %d sqrte %d ret %d
S 1 28 15 138 Tx Lo: Executing Calibration: CalibType(offline(1)/online(2)) = %d,
S 1 28 15 176 Tx Lo: Finished Calibration. Ret Code = %d, Run Time = %d
S 1 28 15 351 TXLo calibrateSingleAntenna:RF Ant %d,LoopBackRxAnt %d, LoopBackTxAnt %d
S 1 28 15 366 TxLo calibrateSingleAntenna(): Restore Hw Registers Run Time = %d
S 1 28 15 643 TxLo calibrateAndVerifySingleTpc: TPC %d
S 1 28 15 681 Tx Lo calibrateAndVerifySingleTpc(): Verify reference Energy(log) = %d
S 1 28 15 775 TxLo doAxisIteration(). Iteration = %d, I = %d
S 1 28 15 787 TxLo doAxisIteration(). Iteration = %d, Q = %d
S 1 28 15 803 TxLo calibrateAndVerifySingleTpc digitalDacI = %d, digitalDacQ = %d
S 1 28 15 811 TxLo calibrateAndVerifySingleTpc dacI = %d, dacQ = %d
S 1 28 15 822 TxLo calibrateAndVerifySingleTpc(): Run Time = %d
S 1 28 15 956 TxLo digitalDacUpdateRequired() DAC  %d exceeds allowed range but digital DAC max iterations %d exceeded
S 1 28 15 1111 Tx Lo VerifyCalibrationResults(): TPC Energy(log) = %d Diff from Ref %d
S 1 28 15 1121 Tx Lo verifyCalibrationResults():Energy diff from ref %d below TH = %d status = %d
S 1 28 15 1129 TxLo verifyCalibrationResults status = %d
S 1 28 15 1136 TxLo verifyCalibrationResults(): Single TPC verify Run Time = %d
S 1 28 15 1291 TxLo updateTpcsToNextCalibTpc: next TPC = %d
S 1 28 15 1390 Assert in file: "TxLOLeakageClbrHndlr.c" in line: 1390
S 1 28 15 1439 TxLoLeakage_StoreResults(): Ant %d Digital DAC: I=%d Q=%d
S 1 28 15 1447 TxLoLeakage_StoreResults(): Ant %d Num Calibrated TPCs=%d
S 1 28 15 1458 TxLoLeakage_StoreResults(): Ant %d TPC %d DAC: I=%d Q=%d
S 1 28 16 356 Assert in file: "CalibrationHandler.c" in line: 356
S 1 28 16 364 Assert in file: "CalibrationHandler.c" in line: 364
S 1 28 16 386 Calibrating...
S 1 28 16 549 Assert in file: "CalibrationHandler.c" in line: 549
S 1 28 16 564 runCalibration. clbrType: %d dataStoreState: %d
S 1 28 16 584 runCalibration. proc %d
S 1 28 16 588 Assert in file: "CalibrationHandler.c" in line: 588
S 1 28 16 602 Calibrations fragmented
S 1 28 16 608 Finished Calibrations
S 1 28 16 710 CalibrationHandler getUpdateOfflineStatus(). StatusVector = 0x%x %d
S 1 28 16 810 calBitmap:%d
S 1 28 17 32 Assert in file: "CalibrationHandlerUtils.c" in line: 32
S 1 29 0 1098 Assert in file: "Afe.c" in line: 1098
S 1 29 0 1131 Assert in file: "Afe.c" in line: 1131
S 1 29 0 1293 Assert in file: "Afe.c" in line: 1293
S 1 29 0 1438 Assert in file: "Afe.c" in line: 1438
S 1 29 4 863 Assert in file: "Afe.c" in line: 863
S 1 29 4 1391 Assert in file: "Afe.c" in line: 1391
S 1 29 4 1532 Assert in file: "Afe.c" in line: 1532
S 1 30 4 865 Assert in file: "Afe.c" in line: 865
S 1 30 4 1391 Assert in file: "Afe.c" in line: 1391
S 1 30 4 1532 Assert in file: "Afe.c" in line: 1532
S 1 30 1 61 Assert in file: "efuseAccess.c" in line: 61
S 1 30 1 62 Assert in file: "efuseAccess.c" in line: 62
S 1 30 1 110 Assert in file: "efuseAccess.c" in line: 110
S 1 29 5 256 Assert in file: "IndirectAccess.c" in line: 256
S 1 29 6 639 Assert in file: "PhyCalDriver.c" in line: 639
S 1 29 6 1081 Assert in file: "PhyCalDriver.c" in line: 1081
S 1 29 6 1311 Assert in file: "PhyCalDriver.c" in line: 1311
S 1 29 8 781 Assert in file: "PhyCalDriver.c" in line: 781
S 1 29 8 782 Assert in file: "PhyCalDriver.c" in line: 782
S 1 29 8 813 Assert in file: "PhyCalDriver.c" in line: 813
S 1 29 8 867 Assert in file: "PhyCalDriver.c" in line: 867
S 1 29 8 1397 Assert in file: "PhyCalDriver.c" in line: 1397
S 1 29 8 1689 Assert in file: "PhyCalDriver.c" in line: 1689
S 1 29 9 281 Fatal Error in file: "mt_phy_dummy.c"; Fatal Print: Bad PHY mdoe
S 1 29 9 351 Assert in file: "mt_phy_dummy.c" in line: 351
S 1 29 13 461 PhyDrv_DisableBB
S 1 29 13 470 PhyDrv_EnableBB
S 1 29 13 582 Assert in file: "PhyDriver.c" in line: 582
S 1 29 13 610 Fatal Error in file: "PhyDriver.c"; Fatal Print: PHY DRV Get TCR All
S 1 29 13 738 Assert in file: "PhyDriver.c" in line: 738
S 1 29 13 829 Assert in file: "PhyDriver.c" in line: 829
S 1 29 13 831 Assert in file: "PhyDriver.c" in line: 831
S 1 29 13 832 Assert in file: "PhyDriver.c" in line: 832
S 1 29 13 842 Fatal Error in file: "PhyDriver.c"; Fatal Print: WD(phy) interrupt occured
S 1 29 13 849 Fatal Error in file: "PhyDriver.c"; Fatal Print: Tx packet interrupt
S 1 29 15 121 Assert in file: "PhyTestBus.c" in line: 121
S 1 29 15 141 Assert in file: "PhyTestBus.c" in line: 141
S 1 29 15 165 Fatal Error in file: "PhyTestBus.c"; Fatal Print: PhyTestBus_Read, illegal case
S 1 30 2 757 Assert in file: "RficDriver.c" in line: 757
S 1 30 2 804 Assert in file: "RficDriver.c" in line: 804
S 1 30 2 1089 Assert in file: "RficDriver.c" in line: 1089
S 1 30 2 1185 Assert in file: "RficDriver.c" in line: 1185
S 1 30 2 1245 Assert in file: "RficDriver.c" in line: 1245
S 1 30 2 1307 Assert in file: "RficDriver.c" in line: 1307
S 1 30 2 1355 Assert in file: "RficDriver.c" in line: 1355
S 1 30 2 1396 Assert in file: "RficDriver.c" in line: 1396
S 1 30 2 1440 Assert in file: "RficDriver.c" in line: 1440
S 1 30 2 1480 Assert in file: "RficDriver.c" in line: 1480
S 1 30 2 1582 Assert in file: "RficDriver.c" in line: 1582
S 1 30 2 1660 Assert in file: "RficDriver.c" in line: 1660
S 1 30 2 1675 Assert in file: "RficDriver.c" in line: 1675
S 1 30 2 1742 Assert in file: "RficDriver.c" in line: 1742
S 1 30 2 1851 Assert in file: "RficDriver.c" in line: 1851
S 1 30 2 1896 Assert in file: "RficDriver.c" in line: 1896
S 1 30 2 1913 RficDriver_SetFrequency freq = %d, bw = %d
S 1 30 2 1919 DRIVER set frequency %d ....FREQ FOR CALIBRATE, is diffrent from LoFrequencies_G[2]=%d
S 1 30 2 1921 LoFrequencies_G[1]=%d, .LoFrequencies_G[2]=%d
S 1 30 2 2088 Assert in file: "RficDriver.c" in line: 2088
S 1 30 2 2290 Assert in file: "RficDriver.c" in line: 2290
S 1 30 2 2351 Assert in file: "RficDriver.c" in line: 2351
S 1 30 2 2424 Assert in file: "RficDriver.c" in line: 2424
S 1 30 2 2472 Assert in file: "RficDriver.c" in line: 2472
S 1 30 2 2707 Assert in file: "RficDriver.c" in line: 2707
S 1 30 2 2742 Assert in file: "RficDriver.c" in line: 2742
S 1 29 22 265 Assert in file: "PSD.c" in line: 265
S 1 29 22 343 Assert in file: "PSD.c" in line: 343
S 1 29 22 354 Assert in file: "PSD.c" in line: 354
S 1 29 22 446 Assert in file: "PSD.c" in line: 446
S 1 29 22 482 Assert in file: "PSD.c" in line: 482
S 1 29 22 523 Assert in file: "PSD.c" in line: 523
S 1 29 22 563 Assert in file: "PSD.c" in line: 563
S 1 29 22 637 Assert in file: "PSD.c" in line: 637
S 1 29 22 638 Assert in file: "PSD.c" in line: 638
S 1 29 22 676 Assert in file: "PSD.c" in line: 676
S 1 29 22 721 Assert in file: "PSD.c" in line: 721
S 1 29 22 1051 Assert in file: "PSD.c" in line: 1051
S 1 29 22 1071 Assert in file: "PSD.c" in line: 1071
S 1 29 22 1178 Assert in file: "PSD.c" in line: 1178
S 1 29 22 1179 Assert in file: "PSD.c" in line: 1179
S 1 29 24 103 LmHdk_init
S 1 31 5 176 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Host Interface 2 MIPS Error Start
S 1 31 5 192 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Unsupported Message ID
S 1 31 5 217 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Unsupported Message ID
S 1 31 5 229 Fatal Error in file: "HostGenRiscInterface.c"; Fatal Print: Host Interface 2 MIPS Unknown event
S 1 31 5 420 Assert in file: "HostGenRiscInterface.c" in line: 420
S 1 31 5 451 Assert in file: "HostGenRiscInterface.c" in line: 451
S 1 31 5 502 Assert in file: "HostGenRiscInterface.c" in line: 502
S 1 32 2 443 HostIfAcc_SetPdThreshold - %d
S 1 33 4 83 [Pac_DurEnableNavInitMode] - WAVE400------------------------------------end]
S 1 33 5 96 [PTA][Pac_RxcSetForceCca] read regVal = 0x%x
S 1 33 5 104 [PTA][Pac_RxcSetForceCca] write regVal = 0x%x
S 1 33 5 109 [PTA][Pac_RxcSetForceCca] read u32PacRxcMtForceCCA = 0x%x
S 1 33 5 120 [PTA][Pac_RxcSetForceCcaToNormalMode] read regVal = 0x%x
S 1 33 5 130 [PTA][Pac_RxcSetForceCcaToNormalMode] write regVal = 0x%x
S 1 33 5 380 [Pac_RxcEnableRssiAbort]--WAVE400
S 1 33 5 404 [Pac_RxcDisableRssiAbort]--WAVE400
S 1 33 6 588 [Pac_RxdConfigureRssiMode]---WAVE400------------------------end]
S 1 33 7 274 Assert in file: "PacRxf.c" in line: 274
S 1 33 7 277 [Pac_RxfSetMACAddressfilter] before, sRXF.asLFCs[0].u32Ref1 = %x, sRXF.asLFCs[0].u32Ref2 = %x, sRXF.asLFCs[0].u32Control = %x
S 1 33 7 330 [Pac_RxfSetMACAddressfilter] after, sRXF.asLFCs[0].u32Ref1 = %x, sRXF.asLFCs[0].u32Ref2 = %x, sRXF.asLFCs[0].u32Control = %x
S 1 33 7 334 [Pac_RxfSetMACAddressfilter]---WAVE400----------------------end]
S 1 33 7 350 Assert in file: "PacRxf.c" in line: 350
S 1 33 7 379 [Pac_RxfUseFixedVapId] - WAVE400------------------------------------end]
S 1 33 7 416 [Pac_RxfNormalVapId]---WAVE400------------------------------end]
S 1 33 9 291 LmUtil_setIfsValue, ifsValue[ifs resolution]:%d, spacingUsec:%d, PhyDrv_GetDelayValue(PHY_DID_PIFS):%d
S 1 33 20 134 Assert in file: "Pac.c" in line: 134
S 1 33 23 146 Assert in file: "PacDeliniator.c" in line: 146
S 1 33 24 155 Assert in file: "PacDur.c" in line: 155
S 1 33 25 111 [PTA][Pac_RxcSetForceCca] read regVal = 0x%x
S 1 33 25 119 [PTA][Pac_RxcSetForceCca] write regVal = 0x%x
S 1 33 25 132 [PTA][Pac_RxcSetForceCcaToNormalMode] read regVal = 0x%x
S 1 33 25 140 [PTA][Pac_RxcSetForceCcaToNormalMode] write regVal = 0x%x
S 1 33 26 489 Fatal Error in file: "PacRxd.c"; Fatal Print: Pac_RxdConfigureScanMode
S 1 33 27 255 Assert in file: "PacRxf.c" in line: 255
S 1 33 27 375 Assert in file: "PacRxf.c" in line: 375
S 1 33 27 597 Assert in file: "PacRxf.c" in line: 597
S 1 33 27 612 [Pac_RxfSetMACAddressfilter], PacManagerGlobalParameters->longFilter0Ref1RegNormal = %x
S 1 33 27 613 [Pac_RxfSetMACAddressfilter], PacManagerGlobalParameters->longFilter0Ref2RegNormal = %x
S 1 33 27 647 [Pac_RxfSetMACAddressfilter], longFilterRef1Address = %x
S 1 33 27 648 [Pac_RxfSetMACAddressfilter], longFilter0Ref1Reg.val = %x
S 1 33 27 649 [Pac_RxfSetMACAddressfilter], longFilterRef2Address = %x
S 1 33 27 650 [Pac_RxfSetMACAddressfilter], longFilter0Ref2Reg.val = %x
S 1 33 27 670 Assert in file: "PacRxf.c" in line: 670
S 1 33 27 744 [Pac_RxfNormalVapId], pLocalPacManagerGlobalParameters->vapIdBitMap = %d
S 1 33 27 745 [Pac_RxfNormalVapId], longFilterRef1Address = %x
S 1 33 27 746 [Pac_RxfNormalVapId], pLocalPacManagerGlobalParameters->longFilter0Ref1RegNormal = %x
S 1 33 27 747 [Pac_RxfNormalVapId], longFilterRef2Address = %x
S 1 33 27 748 [Pac_RxfNormalVapId], pLocalPacManagerGlobalParameters->longFilter0Ref2RegNormal = %x
S 1 7 4 157 Assert in file: "HwEvents.c" in line: 157
S 1 7 4 249 Fatal Error in file: "HwEvents.c"; Fatal Print: hwEventsRxClassifierRekey
S 1 7 6 371 Assert in file: "HwQManager.c" in line: 371
S 1 7 6 399 Assert in file: "HwQManager.c" in line: 399
S 1 7 6 429 Assert in file: "HwQManager.c" in line: 429
S 1 7 6 458 Assert in file: "HwQManager.c" in line: 458
S 1 7 6 487 Assert in file: "HwQManager.c" in line: 487
S 1 7 6 516 Assert in file: "HwQManager.c" in line: 516
S 1 7 6 546 Assert in file: "HwQManager.c" in line: 546
S 1 7 6 574 Assert in file: "HwQManager.c" in line: 574
S 1 35 0 548 Assert in file: "RxQueues.c" in line: 548
S 1 35 0 591 Assert in file: "RxQueues.c" in line: 591
S 1 35 0 599 Assert in file: "RxQueues.c" in line: 599
S 1 35 0 607 Assert in file: "RxQueues.c" in line: 607
S 1 35 0 766 Assert in file: "RxQueues.c" in line: 766
S 1 35 0 788 Assert in file: "RxQueues.c" in line: 788
S 1 7 8 195 Assert in file: "HwQManager.c" in line: 195
S 1 7 8 198 Assert in file: "HwQManager.c" in line: 198
S 1 7 8 204 Assert in file: "HwQManager.c" in line: 204
S 1 7 8 266 Assert in file: "HwQManager.c" in line: 266
S 1 7 8 695 HwQManager_ErrorEvent: 0x%X 
S 1 7 8 697 Fatal Error in file: "HwQManager.c"; Fatal Print: HW Q Manager Error Event
S 1 7 8 724 Assert in file: "HwQManager.c" in line: 724
S 1 7 8 755 Assert in file: "HwQManager.c" in line: 755
S 1 7 8 789 Assert in file: "HwQManager.c" in line: 789
S 1 38 2 117 ContinuousInterfererDetectionGlobalParameters.maxMeasuremenet = %d continuousInterfererMessageParameters.channel: %d
S 1 38 2 211 continuousInterfererMessageParameters.maximumValue = %d continuousInterfererMessageParameters.channel: %d
S 1 38 1 148 Assert in file: "RadarDetection.c" in line: 148
S 1 38 1 196 Assert in file: "RadarDetection.c" in line: 196
S 1 38 1 239 Assert in file: "RadarDetection.c" in line: 239
S 1 38 1 273 Assert in file: "RadarDetection.c" in line: 273
S 1 38 1 317 Assert in file: "RadarDetection.c" in line: 317
S 1 38 1 392 Assert in file: "RadarDetection.c" in line: 392
S 1 38 1 397 Assert in file: "RadarDetection.c" in line: 397
S 1 38 1 450 Assert in file: "RadarDetection.c" in line: 450
S 1 38 1 536 Assert in file: "RadarDetection.c" in line: 536
S 1 38 1 559 Assert in file: "RadarDetection.c" in line: 559
S 1 38 1 627 radarDetectionCheckLongRadarPri: pri count %d, long %d, short %d
S 1 38 1 674 Assert in file: "RadarDetection.c" in line: 674
S 1 38 1 675 Assert in file: "RadarDetection.c" in line: 675
S 1 38 1 679 Assert in file: "RadarDetection.c" in line: 679
S 1 38 1 686 Assert in file: "RadarDetection.c" in line: 686
S 1 38 1 690 Assert in file: "RadarDetection.c" in line: 690
S 1 38 1 710 enough PRIs %d
S 1 38 1 752 radarDetectionCheckValidPri: pri %d
S 1 38 1 765 Assert in file: "RadarDetection.c" in line: 765
S 1 38 1 804 radarDetectionCheckLongValidPri: pri %d, pwdiff %d
S 1 38 1 937 Assert in file: "RadarDetection.c" in line: 937
S 1 38 1 938 Assert in file: "RadarDetection.c" in line: 938
S 1 38 1 944 ================================== RadarDetection_ProcessSamples ======================================
S 1 38 1 950 @@@@@ record: pw %d, timestamp %u @@@@@
S 1 38 1 1040 $$$$$$$$$$$$$$$$$$$$$$$$$$ Radar detected %d $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
S 1 38 1 1041 $$$$$$$$$$$$$$$$$$$$$$$$$$ Radar detected SubBandBitmap = %d $$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
S 1 39 0 441 Fatal Error in file: "InterruptManager.c"; Fatal Print: Spurious Interrupt
S 1 39 0 475 Assert in file: "InterruptManager.c" in line: 475
S 1 39 0 481 Assert in file: "InterruptManager.c" in line: 481
S 1 39 0 523 Assert in file: "InterruptManager.c" in line: 523
S 1 39 0 527 Assert in file: "InterruptManager.c" in line: 527
S 1 39 0 693 Assert in file: "InterruptManager.c" in line: 693
S 1 40 0 78 IPC UM Debug - MSG from other core: %d : MsgType: 0x%x
S 1 40 0 80 IPC LM Debug - MSG from other core: %d : MsgType: 0x%x
S 1 40 0 143 Assert in file: "ipc.c" in line: 143
S 1 40 0 275 Assert in file: "ipc.c" in line: 275
S 1 41 0 183 Fatal Error in file: "kccmsg.c"; Fatal Print: pre-allocated message space insufficient
S 1 41 0 200 Assert in file: "kccmsg.c" in line: 200
S 1 41 0 201 Assert in file: "kccmsg.c" in line: 201
S 1 41 0 202 Assert in file: "kccmsg.c" in line: 202
S 1 41 0 203 Assert in file: "kccmsg.c" in line: 203
S 1 41 0 217 Assert in file: "kccmsg.c" in line: 217
S 1 41 0 253 Fatal Error in file: "kccmsg.c"; Fatal Print: Tried to increase a reference count past limit
S 1 42 0 151 AntennaSelectionAddSta. ActivatedAntennasCount %d antSelMask %d
S 1 42 0 199 AntennaSelectionSetNextProbingPoint
S 1 42 0 211 AntennaSelectionSetNextProbingPoint. nextprobingMask 0x%x
S 1 42 0 267 AntennaSelectionProcessFeedback
S 1 42 0 310 AntennaSelectionProcessFeedback. PB is better than WP - change WP!
S 1 42 0 338 AntennaSelectionProcessFeedback - SET RATE + 1
S 1 42 0 488 setAntSelParams. numOfAntennas %d isLimitingState %d validAntennas %d 
S 1 42 0 513 getPermutation. antennasIndex %d permutationIndex %d 
S 1 42 0 515 Assert in file: "AntennaSelection.c" in line: 515
S 1 42 0 516 Assert in file: "AntennaSelection.c" in line: 516
S 1 42 0 558 increaseAntSelectionProbingIndices. nextPermutation 0x%x antennaIndex %d permutationIndex %d 
S 1 42 0 606 increaseAntSelectionProbingIndices. validPermutationFound %d ActivatedAntennasBitmap 0x%x 
S 1 42 0 641 Assert in file: "AntennaSelection.c" in line: 641
S 1 42 0 690 Assert in file: "AntennaSelection.c" in line: 690
S 1 42 0 749 Assert in file: "AntennaSelection.c" in line: 749
S 1 42 0 834 Assert in file: "AntennaSelection.c" in line: 834
S 1 42 0 1110 setAntSelectionInStaTcr 0x%x isProbing: %d
S 1 42 0 1144 AntSelectionModificationFunc.numOfAntsPp %d, change also CDD
S 1 42 0 1255 AntennaSelectionBfModeIsChanged. newBfMode %d
S 1 42 17 379 Assert in file: "Beamforming.c" in line: 379
S 1 42 17 923 linkAdaptationHandleAgingTimerEvent
S 1 42 2 234 Assert in file: "BwAdaptation.c" in line: 234
S 1 42 2 263 Assert in file: "BwAdaptation.c" in line: 263
S 1 42 2 366 Fatal Error in file: "BwAdaptation.c"; Fatal Print: BwSetNextProbingPoint
S 1 42 2 376 Assert in file: "BwAdaptation.c" in line: 376
S 1 42 2 396 Fatal Error in file: "BwAdaptation.c"; Fatal Print: BwSetNextProbingPoint - No probing should be done if BW loop is not activate
S 1 42 18 102 CddAddSta: %d cddIndex: %d
S 1 42 18 142 non effective loop
S 1 42 18 198 CddProcessFeedback, workingPointPer = %d, slowProbingPointPer = %d
S 1 42 18 224 PB is better than WP - change WP!
S 1 42 18 252 CddProcessFeedback - SET RATE + 1
S 1 42 18 307 validRate: %d antennaCount: %d stbc: %d
S 1 42 18 327 CddStaNumOfAntsIsChanged: antCount %d
S 1 42 18 396 nextPermutation: 0x%x
S 1 42 18 404 cddIndex: %d
S 1 42 18 451 setCddInStaTcr. cddAnt1: %d cddAnt2: %d cddAnt3: %d
S 1 42 18 475 setCddValues. cddAnt1 %d, cddAnt2 %d cddAnt3 %d
S 1 42 18 490 setCddFixedValues. cddAnt1 %d, cddAnt2 %d cddAnt3 %d
S 1 42 18 501 getPermutation. antCount%d
S 1 42 18 503 Assert in file: "CDD.c" in line: 503
S 1 42 18 504 Assert in file: "CDD.c" in line: 504
S 1 42 18 526 tcrCddAnt1: %d tcrCddAnt2: %d tcrCddAnt3: %d
S 1 42 18 535 sameAsWorkingPoint = %d
S 1 42 20 61 DynamicTxop_SetTxopMode. staId %d mode %d
S 1 42 20 111 DynamicTxop_OverwriteTxopModeForMuMember. staId %d mode %d
S 1 42 20 162 DynamicTxop_RateOrBwIsChanged. currentMaxPsduTime %d newMaxPsduTime %d
S 1 42 20 181 DynamicTxop_UpdateEstimator. currentPsduTime %d counter %d
S 1 42 20 230 setTxopModeInHwStaDb. staId %d mode %d
S 1 42 20 248 setTxopInHwStaDb. staId %d enable %d
S 1 42 20 276 setTxopAccordingToPsduTimeEstimation. effectivePsduTime %d currentMaxPsduTime %d enable %d
S 1 42 20 301 calcMaxPsduTimePerRateAndBw. psduLength %d phyRate %d maxTime %d
S 1 42 20 312 getMaxPsduTimeFromStaDb. staId %d maxTime %d 
S 1 42 9 115 Assert in file: "LinkAdaptationProductAdjustment.c" in line: 115
S 1 42 8 338 setStaFixedRatesInHwDb 1 isRateInc = %d newRateindex= %d oldRate= %d 
S 1 42 8 354 setStaFixedRatesInHwDb 2 isRateInc = %d newRateindex= %d oldRate= %d 
S 1 42 8 1317 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1317
S 1 42 8 1490 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1490
S 1 42 8 1522 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1522
S 1 42 8 1689 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1689
S 1 42 8 1734 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1734
S 1 42 8 1736 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1736
S 1 42 8 1737 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1737
S 1 42 8 1750 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1750
S 1 42 8 1818 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1818
S 1 42 8 1910 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1910
S 1 42 8 1911 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1911
S 1 42 8 1912 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1912
S 1 42 8 1926 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1926
S 1 42 8 2002 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2002
S 1 42 8 2091 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2091
S 1 42 8 2831 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2831
S 1 42 8 2958 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2958
S 1 42 8 3065 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3065
S 1 42 8 3068 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3068
S 1 42 8 3108 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3108
S 1 42 8 3119 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3119
S 1 42 8 3129 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3129
S 1 42 8 3164 Assert in file: "LinkAdaptationPhyDriver.c" in line: 3164
S 1 42 11 76 [LinkAdaptation_QAMplusInit] Wave500B, QAMplusEnableFromLm = %d
S 1 42 14 223 Assert in file: "ProtectionAdaptation.c" in line: 223
S 1 42 14 248 Assert in file: "ProtectionAdaptation.c" in line: 248
S 1 42 14 295 ProtectionAdaptation_SetFixedMode : %d
S 1 42 14 342 Assert in file: "ProtectionAdaptation.c" in line: 342
S 1 42 14 369 Assert in file: "ProtectionAdaptation.c" in line: 369
S 1 42 14 371 Assert in file: "ProtectionAdaptation.c" in line: 371
S 1 42 14 410 Assert in file: "ProtectionAdaptation.c" in line: 410
S 1 42 14 438 ProtectionAdaptation_VapSm - vapCollisionTotalRatio is very high : %d, Ackbitmap:%d, Ctsbitmap:%d
S 1 42 14 447 ProtectionAdaptation_VapSm -got indication for invalid VAP 
S 1 42 14 458 ProtectionAdaptation_VapSm -VAP state:NONE-VAP_PROTECTION_FORCE_STATE : %d
S 1 42 14 463 ProtectionAdaptation_VapSm -VAP in PROTECTION_NONE_STATE collsion Count : %d
S 1 42 14 468 ProtectionAdaptation_VapSm -Transition to threshold - collsion Count : %d
S 1 42 14 481 Assert in file: "ProtectionAdaptation.c" in line: 481
S 1 42 14 499 Assert in file: "ProtectionAdaptation.c" in line: 499
S 1 42 14 511 ProtectionAdaptation_VapSm - VAP state:  VAP_PROTECTION_THRESHOLD_STATE
S 1 42 14 523 ProtectionAdaptation_VapSm - berGap = %d
S 1 42 14 529 ProtectionAdaptation_VapSm - Transition to  VAP_PROTECTION_NONE_STATE
S 1 42 14 549 ProtectionAdaptation_VapSm - Transition to  VAP_PROTECTION_NONE_STATE - protection doen't improve
S 1 42 14 564 ProtectionAdaptation_VapSm -VAP state:TH- VAP_PROTECTION_DISABLE_STATE
S 1 42 14 570 Assert in file: "ProtectionAdaptation.c" in line: 570
S 1 42 14 575 ProtectionAdaptation_VapSm -VAP state: VAP_PROTECTION_FORCED_STATE
S 1 42 14 581 ProtectionAdaptation_VapSm -transition to VAP_PROTECTION_NONE_STATE
S 1 42 14 592 ProtectionAdaptation_VapSm -VAP state:Force- VAP_PROTECTION_DISABLE_STATE
S 1 42 14 600 Assert in file: "ProtectionAdaptation.c" in line: 600
S 1 42 14 604 Assert in file: "ProtectionAdaptation.c" in line: 604
S 1 42 14 633 protectionAdaptationStaSm - staCollisionCount : %d, Ackbitmap:%d, Ctsbitmap:%d
S 1 42 14 635 protectionAdaptationStaSm - staCollisionCount is very high
S 1 42 14 638 protectionAdaptationStaSm, vapCollisionResetCounter = %d, staCollisionResetCounter = %d
S 1 42 14 647 protectionAdaptationStaSm, pStaProtectionEstimatorPtr->staCollisionResetCounter = %d
S 1 42 14 658 protectionAdaptationStaSm -statino state: STA_PROTECTION_NONE_STATE
S 1 42 14 664 protectionAdaptationStaSm -transition to STA_THRESHOLD_MODE vapStaCollisionDelta = %d
S 1 42 14 673 protectionAdaptationStaSm -statino state: STA_PROTECTION_THRESHOLD_STATE  vapStaCollisionDelta = %d
S 1 42 14 678 protectionAdaptationStaSm -transition to STA_FORCE_PROTECTION_MODE vapStaCollisionDelta = %d
S 1 42 14 691 protectionAdaptationStaSm -transition to STA_NO_PROTECTION_MODE vapStaCollisionDelta = %d
S 1 42 14 701 protectionAdaptationStaSm -transition to STA_NO_PROTECTION_MODE vapStaCollisionDelta = %d
S 1 42 14 712 protectionAdaptationStaSm -statino state: STA_PROTECTION_FORCE_STATE vapStaCollisionDelta = %d
S 1 42 14 717 protectionAdaptationStaSm -transition to STA_THRESHOLD_MODE - delta exceed threshold, delta = %d
S 1 42 14 732 protectionAdaptationStaSm -transition to STA_NO_PROTECTION_MODE - No improvement with protection vapStaCollisionDelta = %d
S 1 42 14 754 protectionAdaptationStaSm -BAA report arrived to a non-valid station!
S 1 42 14 758 Assert in file: "ProtectionAdaptation.c" in line: 758
S 1 42 14 783 Assert in file: "ProtectionAdaptation.c" in line: 783
S 1 42 14 820 ProtectionAdaptation_WlanTimerEventHandler -collosionRatio == %d
S 1 42 14 972 protectionAdaptationResetCollisionsCounters, vapCollisionResetCounter = %d, staCollisionResetCounter = %d
S 1 42 14 986 protectionAdaptationAgingReset, staCollisionResetCounter = %d, vapCollisionResetCounter = %d
S 1 42 19 145 [QAMplus_ResetCounters]
S 1 42 19 186 [QAMplus_ResetParams]
S 1 42 19 233 [QAMplus_SupportedState], LA in steadyState
S 1 42 19 299 [QAMplus_TrialState] pBaaReport->successMpdu = %d, pBaaReport->MpduCnt = %d
S 1 42 19 316 Assert in file: "QAMplus.c" in line: 316
S 1 42 19 360 [QAMplus_TrialState] pQAMplusDatabase->lastRSSIdB = %d
S 1 42 19 403 Assert in file: "QAMplus.c" in line: 403
S 1 42 19 412 [QAMplus_NewBAReport] start
S 1 42 19 440 [QAMplus_NewBAReport] start, isWorkingPoint = %d, highestRateIndex = %d
S 1 42 19 441 [QAMplus_NewBAReport] start, rateIndexFromCurrentBA = %d
S 1 42 19 442 [QAMplus_NewBAReport] QAM_PLUS_STATE_SUPPORTED start, pQAMplusDatabase->successHighestRateWPCounter = %d
S 1 42 19 443 [QAMplus_NewBAReport] QAM_PLUS_STATE_SUPPORTED start, pBaaReport->successMpdu = %d
S 1 42 19 448 [QAMplus_NewBAReport] QAM_PLUS_STATE_SUPPORTED end, pQAMplusDatabase->successHighestRateWPCounter = %d
S 1 42 19 456 [QAMplus_NewBAReport] QAM_PLUS_STATE_TRIAL start, pBaaReport->phyMode = %d, rateIndexFromCurrentBA = %d, RatesTable[rateIndexFromCurrentBA].vhtMcs = %d
S 1 42 19 470 [QAMplus_NewBAReport] end
S 1 42 19 500 [QAMplus_AddStationReq]  QAMplusEnableFromDriver = %d, QAMplusEnable = %d
S 1 42 19 509 [QAMplus_AddStationReq]  QAMplus_GetState = %d
S 1 42 19 520 [QAMplus_AddStationReq] stationId = %d
S 1 42 19 555 [QAMplus_compareRSSI], start 
S 1 42 19 567 [QAMplus_compareRSSI], end newRSSILarger = %d, pQAMplusDatabase->lastRSSIdB = %d, maxCurrentRssidB = %d
S 1 42 19 609 [QAMplus_findMaxRssi], maxCurrentRssidB = %d
S 1 42 19 637 [QAMplus_SetState] QAMplus_GetState = %d
S 1 42 19 711 [QAMplus_SetSupportedThresh], pQAMplusDatabase->supportedThresh = %d
S 1 42 19 748 [QAMplus_GetMaxNssInMask], MaxNss = %d, indexNss = %d, localRateMask[0] = %d, localRateMask[1] = %d
S 1 42 19 758 Assert in file: "QAMplus.c" in line: 758
S 1 42 19 794 [QAMplus_UpdateLaRateMask] before update
S 1 42 19 804 Assert in file: "QAMplus.c" in line: 804
S 1 42 19 818 [QAMplus_UpdateLaRateMask], maxNss according to raIndexMask= %d
S 1 42 19 819 [QAMplus_UpdateLaRateMask], maxNss according to raIndexMaskOrg= %d
S 1 42 19 823 Assert in file: "QAMplus.c" in line: 823
S 1 42 19 824 Assert in file: "QAMplus.c" in line: 824
S 1 42 19 838 [QAMplus_UpdateLaRateMask] after update
S 1 42 19 875 [QAMplus_SetThresh]
S 1 42 19 904 [QAMplus_Enable], QAMplusEnableFromDriver = %d
S 1 42 19 959 [QAMplus_SetSupportedThresh]
S 1 42 19 991 [QAMplus_GetThresh], pQAMplusConfigParams->trialThresh=%d, pQAMplusConfigParams->inactiveTrialThresh = %d, pQAMplusDatabase->supportedThresh = %d
S 1 42 19 1020 [QAMplus_GetCounters] stationId = %d: failureCounter = %d, numberTrialsCounter = %d, successHighestRateWPCounter = %d
S 1 42 15 721 slowProbingHandler, staIndex = %d, stayWithLastProbingPoint = %d, notEffectveProbeCounter = %d
S 1 42 15 828 Assert in file: "RateAdaptation.c" in line: 828
S 1 42 15 841 raFastProbingProcessFeedback, WORKING POINT CHANGED AFTER PROBING, Last rate = %d, new Rate = %d, newPER = %d
S 1 42 15 950 rateAdaptationChangeWorkingPoint, BW = %d, newRate = %d, prevRate = %d
S 1 42 15 973 Assert in file: "RateAdaptation.c" in line: 973
S 1 42 15 1047 updatePerStability,  pStabilityState = %d
S 1 42 15 1110 updatePerStability, perDeviationStability = %d,targetPerStability = %d, resultPerStability = %d
S 1 42 15 1187 Assert in file: "RateAdaptation.c" in line: 1187
S 1 42 15 1261 Assert in file: "RateAdaptation.c" in line: 1261
S 1 42 15 1360 Assert in file: "RateAdaptation.c" in line: 1360
S 1 42 15 1368 Assert in file: "RateAdaptation.c" in line: 1368
S 1 42 15 1381 Assert in file: "RateAdaptation.c" in line: 1381
S 1 42 15 1695 Assert in file: "RateAdaptation.c" in line: 1695
S 1 42 15 1772 Assert in file: "RateAdaptation.c" in line: 1772
S 1 42 15 1907 FAST DROP, StaINdex = %d, BW = %d, currentRateIndex = %d, newRateindex = %d
S 1 42 15 2018 Assert in file: "RateAdaptation.c" in line: 2018
S 1 42 15 2019 Assert in file: "RateAdaptation.c" in line: 2019
S 1 42 15 2020 Assert in file: "RateAdaptation.c" in line: 2020
S 1 42 15 2071 Assert in file: "RateAdaptation.c" in line: 2071
S 1 42 12 120 Assert in file: "LinkAdaptation_Tests.c" in line: 120
S 1 42 12 230 Assert in file: "LinkAdaptation_Tests.c" in line: 230
S 1 42 12 302 Assert in file: "LinkAdaptation_Tests.c" in line: 302
S 1 42 12 359 Assert in file: "LinkAdaptation_Tests.c" in line: 359
S 1 43 0 172 lockerScheduleRequest  lockRequesterParams= %x 
S 1 43 0 176 Assert in file: "Locker.c" in line: 176
S 1 43 0 229 lockerScheduleGroupRequest  lockRequesterParams=0x %x 
S 1 43 0 233 Assert in file: "Locker.c" in line: 233
S 1 43 0 300 Locker_LockRequestServiced  stationOrVapNum= %x tid = %x callerContext = %x
S 1 43 0 354 Locker_LockGroupRequestServiced status= %d
S 1 44 2 213 LoggerApi_SetSeverity, level:%d, targetCPU:%d
S 1 44 2 219 Logger severity request is out of range:%d ! (should be [%d, %d]
S 1 44 2 274 Assert in file: "loggerAPI.c" in line: 274
S 1 44 2 293 Assert in file: "loggerAPI.c" in line: 293
S 1 44 2 393 Assert in file: "loggerAPI.c" in line: 393
S 1 44 2 576 Assert in file: "loggerAPI.c" in line: 576
S 1 44 2 586 Assert in file: "loggerAPI.c" in line: 586
S 1 45 2 204 Fatal Error in file: "lmint.c"; Fatal Print: Status FIFO has overflowed
S 1 45 2 253 Fatal Error in file: "lmint.c"; Fatal Print: Unused TSF timer
S 1 45 2 515 INT_GP_TIMER_2_ISR in OPERATION_MODE_DUT, calling LowerSenderDutTxEndHandler
S 1 45 2 584 Assert in file: "lmint.c" in line: 584
S 1 45 2 585 Assert in file: "lmint.c" in line: 585
S 1 45 3 349 [lmmain_HwSemaphoreTest 2] got the lock
S 1 45 3 361 [lmmain_HwSemaphoreTest 3] try to free
S 1 45 3 367 [lmmain_HwSemaphoreTest 4] lock is free
S 1 45 3 377 [1] Try to get the lock. Lock status is %d
S 1 45 3 381 [2] I got the lock. Lock status is %d
S 1 45 3 385 [3] I freed the lock. lock status is %d
S 1 45 5 199 Assert in file: "lmtimerUtility.c" in line: 199
S 1 45 5 246 Assert in file: "lmtimerUtility.c" in line: 246
S 1 45 7 210 Assert in file: "lmwmertns.c" in line: 210
S 1 45 7 223 Assert in file: "lmwmertns.c" in line: 223
S 1 45 7 225 Assert in file: "lmwmertns.c" in line: 225
S 1 45 7 255 Assert in file: "lmwmertns.c" in line: 255
S 1 45 8 255 Assert in file: "lm_StaDatabase.c" in line: 255
S 1 45 8 292 Assert in file: "lm_StaDatabase.c" in line: 292
S 1 45 8 325 Assert in file: "lm_StaDatabase.c" in line: 325
S 1 45 8 352 Assert in file: "lm_StaDatabase.c" in line: 352
S 1 45 9 188 Assert in file: "lm_VapDatabase.c" in line: 188
S 1 46 0 89 Assert in file: "lmi_queue.c" in line: 89
S 1 47 0 205 Assert in file: "lm_interface_task.c" in line: 205
S 1 47 0 217 Assert in file: "lm_interface_task.c" in line: 217
S 1 47 0 218 Assert in file: "lm_interface_task.c" in line: 218
S 1 47 0 219 Assert in file: "lm_interface_task.c" in line: 219
S 1 47 0 220 Assert in file: "lm_interface_task.c" in line: 220
S 1 47 0 224 Assert in file: "lm_interface_task.c" in line: 224
S 1 47 0 402 Assert in file: "lm_interface_task.c" in line: 402
S 1 47 0 403 Assert in file: "lm_interface_task.c" in line: 403
S 1 7 10 118 Assert in file: "Mac2index.c" in line: 118
S 1 7 10 121 Assert in file: "Mac2index.c" in line: 121
S 1 7 10 269 Assert in file: "Mac2index.c" in line: 269
S 1 7 10 272 Assert in file: "Mac2index.c" in line: 272
S 1 48 0 84 Assert in file: "init_ifmsg.c" in line: 84
S 1 48 0 86 Assert in file: "init_ifmsg.c" in line: 86
S 1 48 0 139 Assert in file: "init_ifmsg.c" in line: 139
S 1 48 0 145 Assert in file: "init_ifmsg.c" in line: 145
S 1 48 1 64 Assert in file: "MT_NSSMemoryPool.c" in line: 64
S 1 48 1 77 Assert in file: "MT_NSSMemoryPool.c" in line: 77
S 1 48 1 83 Assert in file: "MT_NSSMemoryPool.c" in line: 83
S 1 48 1 130 Assert in file: "MT_NSSMemoryPool.c" in line: 130
S 1 48 1 138 Assert in file: "MT_NSSMemoryPool.c" in line: 138
S 1 48 1 169 Assert in file: "MT_NSSMemoryPool.c" in line: 169
S 1 48 1 177 Assert in file: "MT_NSSMemoryPool.c" in line: 177
S 1 48 1 190 Assert in file: "MT_NSSMemoryPool.c" in line: 190
S 1 48 2 188 Assert in file: "PacketDescriptorsPool.c" in line: 188
S 1 48 2 220 Assert in file: "PacketDescriptorsPool.c" in line: 220
S 1 49 0 201 Fatal Error in file: "NdpaManager.c"; Fatal Print: ndpaManagerIllegalEvent
S 1 49 0 206 ndpaManagerChangeState: newState = %d
S 1 49 0 213 Assert in file: "NdpaManager.c" in line: 213
S 1 49 0 215 ndpaManagerRunStateMachine: CurrentState = %d, event = %d
S 1 49 0 228 Assert in file: "NdpaManager.c" in line: 228
S 1 49 0 231 ndpaManagerStartTxReq: received NdpaStartTx !!!
S 1 49 0 281 ndpaManagerStopTxReq: received NdpaStoptTx !!!
S 1 49 0 304 Assert in file: "NdpaManager.c" in line: 304
S 1 49 0 336 Assert in file: "NdpaManager.c" in line: 336
S 1 49 0 351 Assert in file: "NdpaManager.c" in line: 351
S 1 49 0 389 ndpaManagerIgnoreEvent: CurrentState = %d
S 1 49 0 402 ndpaManagerLaBfReportIndPdReleased: status = %d
S 1 49 0 412 ndpaManagerLaBfReportIndPdNotReleased: status = %d
S 1 49 0 424 ndpaManagerLaBfReportIndWaitForLock: status = %d
S 1 49 0 466 Assert in file: "NdpaManager.c" in line: 466
S 1 49 0 468 ndpaManagerLockCfmInWaitForLock: Lock status %d
S 1 49 0 504 Assert in file: "NdpaManager.c" in line: 504
S 1 49 0 536 Assert in file: "NdpaManager.c" in line: 536
S 1 50 1 153 [PTA][REP][PtaRepEventStart] repetition enable = %d
S 1 50 1 172 [PTA][REP][PtaRepEventActiveTimer] repetition enable = %d
S 1 50 1 207 [PTA][REP][PtaRepEventProcessStart] repetition enable = %d
S 1 50 1 228 [PTA][REP][PtaRepEventInactiveTimer]
S 1 50 1 239 [PTA][REP][PtaRepEventProcessStop] repetition enable = %d
S 1 50 1 257 [PTA][REP][PtaRepEventIgnore]
S 1 50 1 263 [PTA][REP][PtaRepEventAssert] ASSERT === ASSERT === ASSERT
S 1 50 1 271 [PTA][REP][PtaRepStateChange] currrnet state = %d next state = %d
S 1 50 1 281 [PTA][REP][PtaRepTimerStart] timeToGo = %d
S 1 50 1 300 [PTA][REP][PtaRepConfig] enable = %d activePeriod = %d inactivePeriod = %d
S 1 50 1 312 [PTA][REP][PtaRepTimerExpiry]
S 1 50 1 324 [PTA][REP][PtaRepProcessStart]
S 1 50 1 335 [PTA][REP][PtaRepProcessEnd]
S 1 50 1 361 [PTA][PtaGpioReadBtActive] BT not connected to board. BT_ACTIVE = LOW
S 1 50 1 383 [PTA][PtaGpioWriteGrant] Both ZigBee and BT are not connected to board. GRANT is not set
S 1 50 1 397 [PTA][PtaGpioDirectionGrant] Both ZigBee and BT are not connected to board. Not setting GPIO direction for GRANT
S 1 50 1 415 [PTA][PtaGpioDirection] register = 0x%x value = 0x%x
S 1 50 1 425 [PTA][PtaGpioRead] before isolation register = 0x%x value = 0x%x
S 1 50 1 432 [PTA][PtaGpioRead] after  isolation register = 0x%x value = 0x%x
S 1 50 1 445 [PTA][PtaGpioWrite] Value read from register  = 0x%x value = 0x%x
S 1 50 1 456 [PTA][PtaGpioWrite] Value written to register = 0x%x value = 0x%x
S 1 50 1 467 [PTA][PtaGpioMaskGpio0] Value read from register  = 0x%x value = 0x%x
S 1 50 1 476 [PTA][PtaGpioMaskGpio0] Value written to register = 0x%x value = 0x%x
S 1 50 1 488 [PTA][PtaGpioInitGpioState] setting GRANT as HIGH
S 1 50 1 497 [PTA][ptaGpioLatchClearGpio0] Latch cleared
S 1 50 1 508 [PTA][ptaGpioUnmsakGpio0] Value read from register  = 0x%x value = 0x%x
S 1 50 1 517 [PTA][ptaGpioUnmsakGpio0] Value written to register = 0x%x value = 0x%x
S 1 50 1 525 [PTA][PtaGpioBtAllow]
S 1 50 1 535 [PTA][PtaGpioBtDeny]
S 1 50 1 544 [PTA][PtaGpioZigBeeAllow]
S 1 50 1 554 [PTA][PtaGpioZigBeeDeny]
S 1 50 2 145 [PTA][REP][PtaRepEventStart] repetition enable = %d
S 1 50 2 164 [PTA][REP][PtaRepEventActiveTimer] repetition enable = %d
S 1 50 2 199 [PTA][REP][PtaRepEventProcessStart] repetition enable = %d
S 1 50 2 220 [PTA][REP][PtaRepEventInactiveTimer]
S 1 50 2 231 [PTA][REP][PtaRepEventProcessStop] repetition enable = %d
S 1 50 2 249 [PTA][REP][PtaRepEventIgnore]
S 1 50 2 255 [PTA][REP][PtaRepEventAssert] ASSERT === ASSERT === ASSERT
S 1 50 2 263 [PTA][REP][PtaRepStateChange] currrnet state = %d next state = %d
S 1 50 2 273 [PTA][REP][PtaRepTimerStart] timeToGo = %d
S 1 50 2 292 [PTA][REP][PtaRepConfig] enable = %d activePeriod = %d inactivePeriod = %d
S 1 50 2 304 [PTA][REP][PtaRepTimerExpiry]
S 1 50 2 316 [PTA][REP][PtaRepProcessStart]
S 1 50 2 327 [PTA][REP][PtaRepProcessEnd]
S 1 50 2 353 [PTA][PtaGpioReadBtActive] BT not connected to board. BT_ACTIVE = LOW
S 1 50 2 370 [PTA][PtaGpioReadGrant] ZigBee is not connected to board. GRANT = HIGH
S 1 50 2 385 [PTA][PtaGpioWriteGrant] ZigBee is not connected to board. GRANT is not set
S 1 50 2 399 [PTA][PtaGpioDirectionGrant] ZigBee is not connected to board. Not setting GPIO direction for GRANT
S 1 50 2 412 [PTA][PtaGpioDirectionWlanDeny] BT is not connected to board. Not setting GPIO direction for WLAN_DENY
S 1 50 2 426 [PTA][PtaGpioWriteWlanDeny] BT is not connected to board. WLAN_DENY is not set
S 1 50 2 445 [PTA][PtaGpioDirection] register = 0x%x value = 0x%x
S 1 50 2 455 [PTA][PtaGpioRead] before isolation register = 0x%x value = 0x%x
S 1 50 2 462 [PTA][PtaGpioRead] after  isolation register = 0x%x value = 0x%x
S 1 50 2 475 [PTA][PtaGpioWrite] Value read from register  = 0x%x value = 0x%x
S 1 50 2 486 [PTA][PtaGpioWrite] Value written to register = 0x%x value = 0x%x
S 1 50 2 495 [PTA][PtaGpioMaskGpio0] Value written to register = 0x%x bit = %d value = 0x%x
S 1 50 2 511 [PTA][PtaGpioInitGpioState] setting GRANT as HIGH and WLAN_DENY as HIGH
S 1 50 2 520 [PTA][ptaGpioLatchClearGpio0] Latch cleared
S 1 50 2 529 [PTA][ptaGpioUnmsakGpio0] Value written to register = 0x%x bit = %d value = 0x%x
S 1 50 2 536 [PTA][PtaGpioBtAllow]
S 1 50 2 547 [PTA][PtaGpioBtDeny]
S 1 50 2 558 [PTA][PtaGpioZigBeeAllow]
S 1 50 2 569 [PTA][PtaGpioZigBeeDeny]
S 1 51 0 165 Assert in file: "PacManager.c" in line: 165
S 1 51 0 199 [PacManagerSetRxd]---------------------------------------end]
S 1 51 0 313 [PacManagerNormalActivation] -------------------------------------------end]
S 1 51 0 351 [PacManagerRssiActivation]----------------------------------end]
S 1 51 0 394 -------- RXF configured for Sniffer --------
S 1 51 0 399 -------- RXD configured for Sniffer --------
S 1 51 0 405 -------- RXC reserved storage size configured for Sniffer --------
S 1 51 0 410 -------- RXC Rssi abort disabled for Sniffer --------
S 1 51 0 414 Assert in file: "PacManager.c" in line: 414
S 1 51 0 416 -------- RXC configured correctly --------
S 1 51 0 560 Assert in file: "PacManager.c" in line: 560
S 1 51 0 627 Assert in file: "PacManager.c" in line: 627
S 1 51 0 645 Assert in file: "PacManager.c" in line: 645
S 1 52 0 134 Assert in file: "TxPauser.c" in line: 134
S 1 52 0 495 Assert in file: "TxPauser.c" in line: 495
S 1 52 2 193 Assert in file: "TxPauser.c" in line: 193
S 1 52 2 209 Assert in file: "TxPauser.c" in line: 209
S 1 52 2 224 Assert in file: "TxPauser.c" in line: 224
S 1 52 2 240 Assert in file: "TxPauser.c" in line: 240
S 1 52 2 257 Assert in file: "TxPauser.c" in line: 257
S 1 52 2 272 Assert in file: "TxPauser.c" in line: 272
S 1 52 2 312 Assert in file: "TxPauser.c" in line: 312
S 1 53 0 153 Assert in file: "mt_addr_sharing.c" in line: 153
S 1 53 0 208 Assert in file: "mt_addr_sharing.c" in line: 208
S 1 55 0 166 processManagerScheduleProcessRequest:Process Manager State = %x processId = %x
S 1 55 0 183 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Schedule Process Unknown State
S 1 55 0 263 processManagerStartProcess:Process Manager State = %x
S 1 55 0 273 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Start Process Unknown State
S 1 55 0 306 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Queue Process Unknown State
S 1 55 0 345 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Reject Process Unknown State
S 1 55 0 375 Fatal Error in file: "ProcessManager.c"; Fatal Print: Process Manager Finish Process Unknown State
S 1 55 0 419 Assert in file: "ProcessManager.c" in line: 419
S 1 55 0 523 processManagerRunServices:servicesBitMask = %x
S 1 55 0 525 processManagerRunServices:servicesBitMask = %x
S 1 57 0 107 Assert in file: "PsManager.c" in line: 107
S 1 57 0 590 Assert in file: "PsManager.c" in line: 590
S 1 57 2 129 Assert in file: "PsManager.c" in line: 129
S 1 46 1 85 Assert in file: "GeneralQ.c" in line: 85
S 1 46 2 123 Assert in file: "MT_FifoQ.c" in line: 123
S 1 46 2 174 Assert in file: "MT_FifoQ.c" in line: 174
S 1 46 2 179 Assert in file: "MT_FifoQ.c" in line: 179
S 1 46 2 192 Assert in file: "MT_FifoQ.c" in line: 192
S 1 46 2 222 Assert in file: "MT_FifoQ.c" in line: 222
S 1 46 2 227 Assert in file: "MT_FifoQ.c" in line: 227
S 1 46 2 255 Assert in file: "MT_FifoQ.c" in line: 255
S 1 46 2 289 Assert in file: "MT_FifoQ.c" in line: 289
S 1 46 2 294 Assert in file: "MT_FifoQ.c" in line: 294
S 1 46 2 305 Assert in file: "MT_FifoQ.c" in line: 305
S 1 59 0 80 Assert in file: "QSmanager.c" in line: 80
S 1 60 0 185 Fatal Error in file: "RegAccess.c"; Fatal Print: REG Access Write Secured
S 1 61 0 253 Assert in file: "ResourceManager.c" in line: 253
S 1 61 0 287 Assert in file: "ResourceManager.c" in line: 287
S 1 61 0 291 Assert in file: "ResourceManager.c" in line: 291
S 1 61 0 295 Assert in file: "ResourceManager.c" in line: 295
S 1 61 0 301 Assert in file: "ResourceManager.c" in line: 301
S 1 61 0 544 Resource Manager - no ID available for pool type %d, return msg %d, return task %d, context %d
S 1 61 0 548 Assert in file: "ResourceManager.c" in line: 548
S 1 61 0 585 Assert in file: "ResourceManager.c" in line: 585
S 1 61 0 586 Assert in file: "ResourceManager.c" in line: 586
S 1 61 0 626 Assert in file: "ResourceManager.c" in line: 626
S 1 61 0 657 Assert in file: "ResourceManager.c" in line: 657
S 1 61 0 661 Assert in file: "ResourceManager.c" in line: 661
S 1 61 0 702 Assert in file: "ResourceManager.c" in line: 702
S 1 61 0 732 Assert in file: "ResourceManager.c" in line: 732
S 1 7 12 597 Assert in file: "RxClassifier.c" in line: 597
S 1 7 12 820 [RxClassifier_ConfigureNormalMode]-------- Rx Classifier RAM configured for NORMAL_AFTER_RSSI --------
S 1 7 12 829 [RxClassifier_ConfigureNormalMode]--------------------------end
S 1 7 12 864 [RxClassifier_ConfigureRssiMode]-------- Rx Classifier RAM configured for RSSI --------
S 1 7 12 871 [RxClassifier_ConfigureRssiMode], StaDB_IsDataEncrypted(%d) = %d, StaDB_IsManagementEncrypted(%d) = %d
S 1 7 12 879 [RxClassifier_ConfigureRssiMode]------------------------------------end]
S 1 7 12 945 -------- Rx Classifier configured for Sniffer --------
S 1 63 0 445 Assert in file: "RxDataPath.c" in line: 445
S 1 63 0 470 Assert in file: "RxDataPath.c" in line: 470
S 1 64 0 217 Assert in file: "RxHandler.c" in line: 217
S 1 64 0 254 Assert in file: "RxHandler.c" in line: 254
S 1 64 0 322 Assert in file: "RxHandler.c" in line: 322
S 1 64 0 429 Assert in file: "RxHandler.c" in line: 429
S 1 64 0 549 Frame is bigger than Max sniffer payload size (1600 bytes) and has been reduces!! Sniffer original payload size is %d
S 1 64 0 707 Assert in file: "RxHandler.c" in line: 707
S 1 64 0 741 Assert in file: "RxHandler.c" in line: 741
S 1 64 0 804 Assert in file: "RxHandler.c" in line: 804
S 1 64 0 805 Assert in file: "RxHandler.c" in line: 805
S 1 64 0 1008 Assert in file: "RxHandler.c" in line: 1008
S 1 64 0 1661 Assert in file: "RxHandler.c" in line: 1661
S 1 64 0 1665 Assert in file: "RxHandler.c" in line: 1665
S 1 64 0 1892 Assert in file: "RxHandler.c" in line: 1892
S 1 64 0 2200 [RxHandler_CopyMetricsToMetricsFifo] trigger SW event EVENT_ID_METRICS_FIFO_NOT_EMPTY, pFifoEntry->rxPhyMetrics.geriscSpare2 = %d
S 1 64 1 793 Assert in file: "RxHandler_Decryption.c" in line: 793
S 1 64 1 940 Assert in file: "RxHandler_Decryption.c" in line: 940
S 1 64 1 1092 Assert in file: "RxHandler_Decryption.c" in line: 1092
S 1 64 1 1152 Assert in file: "RxHandler_Decryption.c" in line: 1152
S 1 64 1 1390 Assert in file: "RxHandler_Decryption.c" in line: 1390
S 1 64 2 243 Assert in file: "RxHandler_Rtd.c" in line: 243
S 1 64 2 278 Assert in file: "RxHandler_Rtd.c" in line: 278
S 1 31 2 162 Fatal Error in file: "RxHandler.c"; Fatal Print: RX Handler Error Start
S 1 31 2 178 Fatal Error in file: "RxHandler.c"; Fatal Print: Unsupported Message ID
S 1 31 2 203 Fatal Error in file: "RxHandler.c"; Fatal Print: Unsupported Message ID
S 1 31 2 215 Fatal Error in file: "RxHandler.c"; Fatal Print: RX Handler Unknown Event
S 1 31 2 392 Assert in file: "RxHandler.c" in line: 392
S 1 31 2 426 Assert in file: "RxHandler.c" in line: 426
S 1 31 2 477 Assert in file: "RxHandler.c" in line: 477
S 1 67 0 289 Assert in file: "Reordering.c" in line: 289
S 1 67 0 828 Assert in file: "Reordering.c" in line: 828
S 1 67 0 936 Assert in file: "Reordering.c" in line: 936
S 1 67 2 169 Assert in file: "RxPp.c" in line: 169
S 1 67 2 189 Assert in file: "RxPp.c" in line: 189
S 1 67 2 861 Assert in file: "RxPp.c" in line: 861
S 1 67 2 1340 Assert in file: "RxPp.c" in line: 1340
S 1 68 1 179 Assert in file: "RxPp.c" in line: 179
S 1 68 1 467 Assert in file: "RxPp.c" in line: 467
S 1 68 1 477 Assert in file: "RxPp.c" in line: 477
S 1 68 1 517 Assert in file: "RxPp.c" in line: 517
S 1 68 1 654 Assert in file: "RxPp.c" in line: 654
S 1 68 1 1001 Assert in file: "RxPp.c" in line: 1001
S 1 68 1 1110 Assert in file: "RxPp.c" in line: 1110
S 1 54 5 96 Assert in file: "cipher_shared_ram_db.c" in line: 96
S 1 54 5 97 Assert in file: "cipher_shared_ram_db.c" in line: 97
S 1 54 5 136 Assert in file: "cipher_shared_ram_db.c" in line: 136
S 1 54 5 138 Assert in file: "cipher_shared_ram_db.c" in line: 138
S 1 54 5 170 Assert in file: "cipher_shared_ram_db.c" in line: 170
S 1 54 5 171 Assert in file: "cipher_shared_ram_db.c" in line: 171
S 1 54 5 173 Assert in file: "cipher_shared_ram_db.c" in line: 173
S 1 54 5 202 Assert in file: "cipher_shared_ram_db.c" in line: 202
S 1 54 6 158 Assert in file: "cipher_suite.c" in line: 158
S 1 54 6 174 Assert in file: "cipher_suite.c" in line: 174
S 1 54 6 188 Assert in file: "cipher_suite.c" in line: 188
S 1 54 6 214 Assert in file: "cipher_suite.c" in line: 214
S 1 54 6 216 Assert in file: "cipher_suite.c" in line: 216
S 1 54 7 98 Assert in file: "cipher_suite_ccmp.c" in line: 98
S 1 54 8 97 Assert in file: "cipher_suite_wep.c" in line: 97
S 1 54 8 123 Assert in file: "cipher_suite_wep.c" in line: 123
S 1 54 8 154 Assert in file: "cipher_suite_wep.c" in line: 154
S 1 54 1 94 Assert in file: "key_manager.c" in line: 94
S 1 54 3 169 SEC Manager VAP Manager, Vap %d changed from %d to %d
S 1 54 3 250 vUM_MAN_SET_KEY_REQ: u16Status:%d psMsg->header.vapId:%d
S 1 54 3 356 Assert in file: "secManager_VapManager.c" in line: 356
S 1 54 3 433 Assert in file: "secManager_VapManager.c" in line: 433
S 1 54 3 567 Fatal Error in file: "secManager_VapManager.c"; Fatal Print: SEC Manager STA Manager Fatal
S 1 54 3 635 Assert in file: "secManager_VapManager.c" in line: 635
S 1 54 3 707 Assert in file: "secManager_VapManager.c" in line: 707
S 1 54 3 745 Assert in file: "secManager_VapManager.c" in line: 745
S 1 54 3 785 Assert in file: "secManager_VapManager.c" in line: 785
S 1 54 3 788 secManager_VapManagerRemoveVap
S 1 70 1 99 Assert in file: "LowerSenderTxCancel.c" in line: 99
S 1 70 1 106 Assert in file: "LowerSenderTxCancel.c" in line: 106
S 1 70 1 121 Assert in file: "LowerSenderTxCancel.c" in line: 121
S 1 70 1 135 Assert in file: "LowerSenderTxCancel.c" in line: 135
S 1 70 1 147 Assert in file: "LowerSenderTxCancel.c" in line: 147
S 1 70 2 294 Assert in file: "UpperSender.c" in line: 294
S 1 70 2 296 Assert in file: "UpperSender.c" in line: 296
S 1 70 2 298 Assert in file: "UpperSender.c" in line: 298
S 1 70 2 665 Assert in file: "UpperSender.c" in line: 665
S 1 70 2 703 Assert in file: "UpperSender.c" in line: 703
S 1 70 2 765 Assert in file: "UpperSender.c" in line: 765
S 1 70 2 766 Assert in file: "UpperSender.c" in line: 766
S 1 70 3 109 Assert in file: "UpperSender_Encryption.c" in line: 109
S 1 70 3 327 Assert in file: "UpperSender_Encryption.c" in line: 327
S 1 70 3 511 Assert in file: "UpperSender_Encryption.c" in line: 511
S 1 31 4 169 Sender Error: file ID %d, line %d, state %d
S 1 31 4 170 Fatal Error in file: "SenderInterface.c"; Fatal Print: Sender Error Start
S 1 31 4 189 Fatal Error in file: "SenderInterface.c"; Fatal Print: Unsupported Message ID
S 1 31 4 215 Fatal Error in file: "SenderInterface.c"; Fatal Print: Unsupported Message ID
S 1 31 4 227 Fatal Error in file: "SenderInterface.c"; Fatal Print: Sender Unknown Event
S 1 31 4 367 Assert in file: "SenderInterface.c" in line: 367
S 1 31 4 400 Assert in file: "SenderInterface.c" in line: 400
S 1 31 4 468 Assert in file: "SenderInterface.c" in line: 468
S 1 71 0 448 [servicesHandlerSendCTS2Self], ctsParams->duration = %d, servicesHandlerParams.currentRunningServiceData = %d
S 1 71 0 476 Fatal Error in file: "ServicesHandler.c"; Fatal Print: servicesHandlerError
S 1 71 0 534 ServicesHandler_RunService:Service Id %d
S 1 71 0 535 ServicesHandler_RunService:Service Id %d
S 1 71 0 543 Assert in file: "ServicesHandler.c" in line: 543
S 1 72 0 58 Assert in file: "shram_interruptSection.c" in line: 58
S 1 72 0 63 Assert in file: "shram_interruptSection.c" in line: 63
S 1 73 0 282 Smps Manager STA Manager, STA %d changed from %d to %d
S 1 73 0 1462 Assert in file: "SmpsManager_StaManager.c" in line: 1462
S 1 73 0 1638 Assert in file: "SmpsManager_StaManager.c" in line: 1638
S 1 73 0 1676 Assert in file: "SmpsManager_StaManager.c" in line: 1676
S 1 74 0 169 Assert in file: "StaDatabase.c" in line: 169
S 1 74 0 176 Assert in file: "StaDatabase.c" in line: 176
S 1 74 0 186 Assert in file: "StaDatabase.c" in line: 186
S 1 74 0 193 Assert in file: "StaDatabase.c" in line: 193
S 1 74 0 205 Assert in file: "StaDatabase.c" in line: 205
S 1 74 0 364 StaDb_RemoveStationFromDB %X
S 1 74 0 473 Assert in file: "StaDatabase.c" in line: 473
S 1 74 0 510 Assert in file: "StaDatabase.c" in line: 510
S 1 74 0 663 Assert in file: "StaDatabase.c" in line: 663
S 1 74 0 1106 Assert in file: "StaDatabase.c" in line: 1106
S 1 74 0 1107 Assert in file: "StaDatabase.c" in line: 1107
S 1 74 0 1141 Assert in file: "StaDatabase.c" in line: 1141
S 1 74 0 1142 Assert in file: "StaDatabase.c" in line: 1142
S 1 74 0 1200 Assert in file: "StaDatabase.c" in line: 1200
S 1 74 0 1510 StaDB_SetPrimaryStationSuTxopAndNumMpdus: SID %d, txop %d, mpdus %d
S 1 74 0 1534 Assert in file: "StaDatabase.c" in line: 1534
S 1 74 0 1561 Assert in file: "StaDatabase.c" in line: 1561
S 1 74 0 1582 Assert in file: "StaDatabase.c" in line: 1582
S 1 74 0 1583 Assert in file: "StaDatabase.c" in line: 1583
S 1 74 0 1605 Assert in file: "StaDatabase.c" in line: 1605
S 1 39 1 131 Fatal Error in file: "System_Configuration.c"; Fatal Print: System_ConvertUsToSystemClk
S 1 39 2 451 Fatal Error in file: "System_MipsTimers.c"; Fatal Print: Radar Detection Timer isn't used in 2.4G
S 1 39 2 462 Fatal Error in file: "System_MipsTimers.c"; Fatal Print: Rx Pasue Timer isn't used in Wave500B
S 1 39 2 555 Assert in file: "System_MipsTimers.c" in line: 555
S 1 39 2 579 Assert in file: "System_MipsTimers.c" in line: 579
S 1 76 1 128 Assert in file: "tx_application_define.c" in line: 128
S 1 76 1 136 Assert in file: "tx_application_define.c" in line: 136
S 1 76 1 153 Assert in file: "tx_application_define.c" in line: 153
S 1 76 1 165 Assert in file: "tx_application_define.c" in line: 165
S 1 76 1 185 Assert in file: "tx_application_define.c" in line: 185
S 1 76 1 221 Assert in file: "tx_application_define.c" in line: 221
S 1 76 2 59 Assert in file: "tx_application_entry_func.c" in line: 59
S 1 76 2 62 Thread : %d  Entry func, recieved message 
S 1 76 2 63 Assert in file: "tx_application_entry_func.c" in line: 63
S 1 76 2 67 Assert in file: "tx_application_entry_func.c" in line: 67
S 1 76 3 96 Assert in file: "tx_application_func.c" in line: 96
S 1 76 3 113 Assert in file: "tx_application_func.c" in line: 113
S 1 76 3 123 Assert in file: "tx_application_func.c" in line: 123
S 1 76 3 151 Assert in file: "tx_application_func.c" in line: 151
S 1 76 3 203 Assert in file: "tx_application_func.c" in line: 203
S 1 76 3 222 Assert in file: "tx_application_func.c" in line: 222
S 1 76 3 243 Assert in file: "tx_application_func.c" in line: 243
S 1 76 3 296 Assert in file: "tx_application_func.c" in line: 296
S 1 76 3 315 Assert in file: "tx_application_func.c" in line: 315
S 1 76 3 316 Assert in file: "tx_application_func.c" in line: 316
S 1 76 3 337 Assert in file: "tx_application_func.c" in line: 337
S 1 76 3 411 Assert in file: "tx_application_func.c" in line: 411
S 1 76 3 416 Assert in file: "tx_application_func.c" in line: 416
S 1 76 5 46 Assert in file: "tx_application_msg_pool.c" in line: 46
S 1 76 5 87 Assert in file: "tx_application_msg_pool.c" in line: 87
S 1 76 5 108 Assert in file: "tx_application_msg_pool.c" in line: 108
S 1 76 5 113 Assert in file: "tx_application_msg_pool.c" in line: 113
S 1 76 5 138 Assert in file: "tx_application_msg_pool.c" in line: 138
S 1 76 5 142 Assert in file: "tx_application_msg_pool.c" in line: 142
S 1 76 5 198 Assert in file: "tx_application_msg_pool.c" in line: 198
S 1 76 5 214 Fatal Error in file: "tx_application_msg_pool.c"; Fatal Print: attempt to release a non allocated message
S 1 76 5 253 Fatal Error in file: "tx_application_msg_pool.c"; Fatal Print: Tried to decrease a reference count past zero
S 1 76 6 120 Assert in file: "tx_application_timer.c" in line: 120
S 1 77 0 118 Assert in file: "TinyKernel_Messages.c" in line: 118
S 1 77 0 145 Assert in file: "TinyKernel_Messages.c" in line: 145
S 1 77 0 154 Assert in file: "TinyKernel_Messages.c" in line: 154
S 1 77 0 158 Assert in file: "TinyKernel_Messages.c" in line: 158
S 1 77 0 211 Assert in file: "TinyKernel_Messages.c" in line: 211
S 1 77 0 232 Assert in file: "TinyKernel_Messages.c" in line: 232
S 1 77 0 233 Assert in file: "TinyKernel_Messages.c" in line: 233
S 1 77 0 256 Assert in file: "TinyKernel_Messages.c" in line: 256
S 1 77 0 270 Assert in file: "TinyKernel_Messages.c" in line: 270
S 1 77 0 425 Assert in file: "TinyKernel_Messages.c" in line: 425
S 1 77 0 456 Assert in file: "TinyKernel_Messages.c" in line: 456
S 1 79 0 204 Ts Manager, ADD STA, SID %d, allowed %d, Filter %d
S 1 79 0 293 tsManagerRemoveVap
S 1 79 0 343 Assert in file: "TsManager.c" in line: 343
S 1 79 0 400 Ts Manager, Set Filter, SID %d
S 1 79 0 443 Ts Manager, Remove STA, SID %d
S 1 79 0 640 Fatal Error in file: "TsManager.c"; Fatal Print: TS Manager Action Packet Confirmed - Unknown Action
S 1 79 0 770 Assert in file: "TsManager.c" in line: 770
S 1 79 0 1145 Ts Manager, Send Confirmation, Client %d, SID %d
S 1 79 0 1675 Assert in file: "TsManager.c" in line: 1675
S 1 79 0 1676 Assert in file: "TsManager.c" in line: 1676
S 1 79 0 1677 Assert in file: "TsManager.c" in line: 1677
S 1 79 0 1737 Assert in file: "TsManager.c" in line: 1737
S 1 79 0 1772 Assert in file: "TsManager.c" in line: 1772
S 1 79 2 409 Fatal Error in file: "TsManagerRecipient.c"; Fatal Print: TS Manager Recipient Fatal
S 1 79 2 439 TS Manager Recipient SID %d, TID %d, Change State from %d to %d
S 1 79 2 922 tsManagerRecipientAddbaRequestReceivedInClosed stationIndex %d tid %d 
S 1 79 2 956 tsManagerRecipientAddbaRequestReceivedInOpeningthe s
S 1 79 2 963 tsManagerRecipientAddbaRequestReceivedInOpeningthe same dialog token %d
S 1 79 2 1004 tsManagerRecipientAddbaRequestReceivedInOpenedthe s
S 1 79 2 1007 tsManagerRecipientAddbaRequestReceivedInOpenedthe same dialog token %d
S 1 79 2 1149 tsManagerRecipientDelbaReceivedInOpeningWaitingForPd remove status %d
S 1 79 2 1194 tsManagerRecipientDelbaReceivedInOpening 
S 1 79 2 1229 tsManagerRecipientDelbaReceivedInOpened 
S 1 79 2 1358 tsManagerRecipientAddbaResponseConfirmedInOpening station index %d tid % d
S 1 79 2 1425 tsManagerRecipientAddbaResponseConfirmedInClosing station index %d tid % d
S 1 79 2 1492 tsManagerRecipientDelbaConfirmedInClosing station index %d tid % d
S 1 79 2 1560 tsManagerRecipientAddbaResponseConfirmedInClosingWaitingForConfirmation 
S 1 79 2 1593 tsManagerRecipientIllegalPacketReceivedInClosed station index %d tid % d
S 1 79 2 1633 tsManagerRecipientIllegalPacketReceivedInClosedWaitingForMessage station index %d tid % d
S 1 79 2 1671 tsManagerRecipientIllegalPacketReceivedInOpeningWaitingForPd station index %d tid % d
S 1 79 2 1713 tsManagerRecipientPdAllocatedInClosedWaitingForMessage station index %d tid % d
S 1 79 2 1750 tsManagerRecipientPdAllocatedInOpeningWaitingForPd station index %d tid % d
S 1 79 2 1827 tsManagerRecipientPdAllocatedInClosingWaitingForPdForDelba station index %d tid % d
S 1 79 2 1867 tsManagerRecipientPdAllocatedInClosingWaitingForPdForAddbaResponse station index %d tid % d
S 1 79 2 1942 tsManagerRecipientBarReceivedInClosed station index %d tid % d
S 1 79 2 1980 tsManagerRecipientBarReceivedInClosedWaitingForMessage station index %d tid % d
S 1 79 2 2018 tsManagerRecipientBarReceivedInOpeningWaitingForPd station index %d tid % d
S 1 79 2 2055 tsManagerRecipientBarReceivedInOpening station index %d tid % d
S 1 79 2 2086 tsManagerRecipientBarReceivedInOpened station index %d tid % d
S 1 79 2 2117 tsManagerRecipientBarReceivedInClosing station index %d tid % d
S 1 79 2 2149 tsManagerRecipientBarReceivedInClosingWaitingForPdForDelba station index %d tid % d
S 1 79 2 2181 tsManagerRecipientBarReceivedInClosingWaitingForPdForDelba station index %d tid % d
S 1 79 2 2436 tsManagerRecipientCloseBaAgreement stationIndex %d tid %d 
S 1 79 2 2533 tsManagerRecipientProcessAddbaRequest invalid parameters 
S 1 79 2 2541 tsManagerRecipientProcessAddbaRequest invalid parameters 
S 1 79 2 2642 tsManagerRecipientProcessAddbaRequest ADDBA request declined allocation status %d
S 1 79 2 2704 Assert in file: "TsManagerRecipient.c" in line: 2704
S 1 79 2 2719 TsManagerRecipient_TimerEvent inactivity timeout delete BA agreement %d
S 1 79 2 3021 Assert in file: "TsManagerRecipient.c" in line: 3021
S 1 79 2 3220 TsManagerRecipient_BarReceived illegal BAR
S 1 79 2 3396 Assert in file: "TsManagerRecipient.c" in line: 3396
S 1 79 2 3434 TsManagerRecipient_PdAllocated stationIndex %d tid %d state %d
S 1 79 2 3771 Assert in file: "TsManagerRecipient.c" in line: 3771
S 1 79 2 3773 Assert in file: "TsManagerRecipient.c" in line: 3773
S 1 81 2 87 Assert in file: "TxHandlerNtd.c" in line: 87
S 1 4 4 572 Assert in file: "TxSelector.c" in line: 572
S 1 4 4 1248 Fatal Error in file: "TxSelector.c"; Fatal Print: TxSelector_IsDataInQueue - back door not available in gen5b
S 1 4 4 1328 Fatal Error in file: "TxSelector.c"; Fatal Print: ISR TX Selector Error
S 1 84 0 99 Assert in file: "TxSequencer.c" in line: 99
S 1 4 6 157 Assert in file: "TxSequencer.c" in line: 157
S 1 4 6 170 Assert in file: "TxSequencer.c" in line: 170
S 1 42 1 190 Assert in file: "AlphaFilter.c" in line: 190
S 1 86 0 240 Assert in file: "CalendarWheel.c" in line: 240
S 1 86 0 291 Assert in file: "CalendarWheel.c" in line: 291
S 1 86 0 360 Assert in file: "CalendarWheel.c" in line: 360
S 1 37 5 82 Assert in file: "HwSemaphore.c" in line: 82
S 1 37 5 149 Assert in file: "HwSemaphore.c" in line: 149
S 1 37 5 191 Assert in file: "HwSemaphore.c" in line: 191
S 1 37 5 246 [HwSemaphore_Read 1] readValue is %d 
S 1 37 5 273 [HwSemaphore_FreeAllDebug 1] hwSemaphoreShadow = %d
S 1 37 0 121 Assert in file: "MT_Math.c" in line: 121
S 1 37 0 124 Assert in file: "MT_Math.c" in line: 124
S 1 37 0 197 Assert in file: "MT_Math.c" in line: 197
S 1 37 1 60 Assert in file: "Utils_Misc.c" in line: 60
S 1 37 1 81 Assert in file: "Utils_Misc.c" in line: 81
S 1 37 1 113 Assert in file: "Utils_Misc.c" in line: 113
S 1 37 1 166 Assert in file: "Utils_Misc.c" in line: 166
S 1 37 1 202 Assert in file: "Utils_Misc.c" in line: 202
S 1 37 1 568 Fatal Error in file: "Utils_Misc.c"; Fatal Print: Utils_determineSourceTypeAndDmaDirection
S 1 87 0 269 VapDb_AddVap: vapIndex is %X
S 1 87 0 350 VapDb_ResetVapEntry: vapIndex is %X
S 1 87 0 516 Assert in file: "VapDatabase.c" in line: 516
S 1 87 0 537 Assert in file: "VapDatabase.c" in line: 537
S 1 87 0 581 Assert in file: "VapDatabase.c" in line: 581
S 1 87 0 650 Assert in file: "VapDatabase.c" in line: 650
S 1 87 0 749 Assert in file: "VapDatabase.c" in line: 749
S 1 87 0 770 Assert in file: "VapDatabase.c" in line: 770
S 1 87 0 832 Assert in file: "VapDatabase.c" in line: 832
S 1 87 0 855 Assert in file: "VapDatabase.c" in line: 855
S 1 87 0 1290 VapDB_Init
S 1 87 0 1413 [VapDB_FindCompatibleVap], rssiTypeFlag = %d
S 1 28 18 354 Load Store event: LOAD_STORE_EVENT_TRIGGER_LOAD. current state: %d
S 1 28 18 363 Load Store event: LOAD_STORE_EVENT_DMA_DONE. current state: %d
S 1 28 18 372 Load Store event: LOAD_STORE_EVENT_TRIGGER_STORE. current state: %d
S 1 28 18 425 Assert in file: "CalibrationManager.c" in line: 425
S 1 28 18 440 setLoadStoreSmState. state: %d
S 1 28 18 557 ClbrMngr_RunOnlineCalibration
S 1 28 18 560 Assert in file: "CalibrationManager.c" in line: 560
S 1 28 18 580 ClbrMngr_RunOfflineCalibration
S 1 28 18 592 SWITCH TYPE %d ++++++++ 
S 1 28 18 616 BITMAP BEFORE m_curOfflineProcBitmap = %d
S 1 28 18 631 Assert in file: "CalibrationManager.c" in line: 631
S 1 28 18 670 Assert in file: "CalibrationManager.c" in line: 670
S 1 28 18 689 CM_STATISTICS_ONLINE_CAL_NET_DURATION %d proc %d
S 1 28 18 691 Assert in file: "CalibrationManager.c" in line: 691
S 1 28 18 790 ClbrMngr_HandleCalibrateProcessStart
S 1 28 18 835 ClbrMngr_CalibrateChannelDone
S 1 28 18 860 Fatal Error in file: "CalibrationManager.c"; Fatal Print: Calibration WD Timer Expired
S 1 29 31 264 Change ERP State,from %d, to %d 
S 1 29 31 270 Run ERP SM, event %d, state %d
S 1 29 31 359 Assert in file: "Erp.c" in line: 359
S 1 29 31 848 Assert in file: "Erp.c" in line: 848
S 1 29 31 917 Assert in file: "Erp.c" in line: 917
S 1 32 3 67 Assert in file: "HostInterfaceAcc.c" in line: 67
S 1 32 3 72 Assert in file: "HostInterfaceAcc.c" in line: 72
S 1 32 3 154 Assert in file: "HostInterfaceAcc.c" in line: 154
S 1 32 3 238 HostIfAcc_SetPdThreshold - %d
S 1 36 1 599 TxSelector_ReleaseStd, numPendQs = %d
S 1 36 1 733 Assert in file: "TxSelector.c" in line: 733
S 1 36 1 765 TxSelector_DisableRequest - put in pending, numPendingQueues = %d
S 1 36 1 885 TxSelector_LockRequest - put in pending, numPendingQueues = %d
S 1 36 1 1294 txSelectorUnLockQueueIndex - NOT clearing, pendingLockRequest.numPendQs = %d
S 1 36 1 1354 Assert in file: "TxSelector.c" in line: 1354
S 1 36 1 1485 Assert in file: "TxSelector.c" in line: 1485
S 1 36 1 1653 Assert in file: "TxSelector.c" in line: 1653
S 1 36 1 1672 Assert in file: "TxSelector.c" in line: 1672
S 1 36 1 1731 Assert in file: "TxSelector.c" in line: 1731
S 1 36 1 1741 Assert in file: "TxSelector.c" in line: 1741
S 1 36 1 1749 Assert in file: "TxSelector.c" in line: 1749
S 1 36 1 2387 Assert in file: "TxSelector.c" in line: 2387
S 1 36 1 2467 Assert in file: "TxSelector.c" in line: 2467
S 1 42 13 674 Assert in file: "PowerAdaptation.c" in line: 674
S 1 42 13 857 PowerSetNextProbingPointAndIndications, Bw %d, newPower = %d
S 1 42 13 968 PowerAdaptationAdjustAdditionalSteps nextPowerProbingPoint = %d probingPowerStep = %d powerAdditionalStepUp = %d powerAdditionalStepDown = %d
S 1 42 13 1050 PowerProcessFeedback, workingPointPer = %d, slowProbingPointPer = %d
S 1 42 13 1117 PowerProcessFeedback: Change power working point newPower = %d
S 1 42 13 1253 *pAdditionalStep %d minAbsPowerStep %d
S 1 42 13 1344 CalcLimitsAndGetStaTcrPowerVal, Bw = %d, rateIndex = %d, powerVal = %d, newPower = %d, newTcrPowerVal = %d
S 1 42 13 1457 Assert in file: "PowerAdaptation.c" in line: 1457
S 1 42 13 1662 Assert in file: "PowerAdaptation.c" in line: 1662
S 1 42 13 1802 Assert in file: "PowerAdaptation.c" in line: 1802
S 1 42 13 1910 mcs:%d, mss:%d
S 1 42 13 1919 Assert in file: "PowerAdaptation.c" in line: 1919
S 1 42 13 1951 Assert in file: "PowerAdaptation.c" in line: 1951
S 1 42 13 1958 Assert in file: "PowerAdaptation.c" in line: 1958
S 1 42 13 2004 Assert in file: "PowerAdaptation.c" in line: 2004
S 1 42 13 2066 calcInternalLowerLimit, Limit = %d
S 1 42 13 2095 calcExternalLowerLimit, BW %d, Limit = %d
S 1 42 13 2134 calcExternalUpperLimit, BW %d, Limit = %d
S 1 42 13 2323 PowerAdaptationCalcPowerInStaLimits, newPower = %d, isPowerBlocked = %d
S 1 42 13 2660 Assert in file: "PowerAdaptation.c" in line: 2660
S 1 42 13 2686 Assert in file: "PowerAdaptation.c" in line: 2686
S 1 42 6 310 Assert in file: "LinkAdaptationPhyDriver.c" in line: 310
S 1 42 6 334 Assert in file: "LinkAdaptationPhyDriver.c" in line: 334
S 1 42 6 340 pDataTcr1->tcr1TxPower = %d
S 1 42 6 453 Assert in file: "LinkAdaptationPhyDriver.c" in line: 453
S 1 42 6 526 Assert in file: "LinkAdaptationPhyDriver.c" in line: 526
S 1 42 6 867 Assert in file: "LinkAdaptationPhyDriver.c" in line: 867
S 1 42 6 882 Assert in file: "LinkAdaptationPhyDriver.c" in line: 882
S 1 42 6 1301 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1301
S 1 42 6 1523 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1523
S 1 42 6 1548 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1548
S 1 42 6 1662 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1662
S 1 42 6 1771 bwAdaptationSetStationBwLimit, laDatabase->bwAdaptationDb.maxSupportedBw = %d
S 1 42 6 1819 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1819
S 1 42 6 1841 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1841
S 1 42 6 1928 Assert in file: "LinkAdaptationPhyDriver.c" in line: 1928
S 1 42 6 2084 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2084
S 1 42 6 2225 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2225
S 1 42 6 2227 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2227
S 1 42 6 2262 Assert in file: "LinkAdaptationPhyDriver.c" in line: 2262
S 1 28 11 548 Assert in file: "TpcClbrHndlr.c" in line: 548
S 1 28 11 570 Assert in file: "TpcClbrHndlr.c" in line: 570
S 1 28 11 764 Assert in file: "TpcClbrHndlr.c" in line: 764
S 1 28 11 1117 Assert in file: "TpcClbrHndlr.c" in line: 1117
S 1 28 11 1165 ===================== Calibrate index %d, ant %d, bw %d ==============================
S 1 28 11 1214 -------- feedback %d, measured %d, target %d -----------
S 1 28 11 1238 old %d, new %d, steps %d
S 1 28 11 1449 Assert in file: "TpcClbrHndlr.c" in line: 1449
S 1 28 11 1460 Assert in file: "TpcClbrHndlr.c" in line: 1460
S 1 28 11 1461 Assert in file: "TpcClbrHndlr.c" in line: 1461
S 1 28 13 172 Assert in file: "TpcClbrHndlr.c" in line: 172
S 1 28 13 173 Assert in file: "TpcClbrHndlr.c" in line: 173
S 1 28 13 372 Assert in file: "TpcClbrHndlr.c" in line: 372
S 1 28 13 381 Assert in file: "TpcClbrHndlr.c" in line: 381
S 1 28 13 694 Assert in file: "TpcClbrHndlr.c" in line: 694
S 1 28 13 695 Assert in file: "TpcClbrHndlr.c" in line: 695
S 1 3 0 451 Assert in file: "AggregationBuilder.c" in line: 451
S 1 3 0 483 Assert in file: "AggregationBuilder.c" in line: 483
S 1 3 0 611 Assert in file: "AggregationBuilder.c" in line: 611
S 1 3 0 627 Assert in file: "AggregationBuilder.c" in line: 627
S 1 3 0 788 Assert in file: "AggregationBuilder.c" in line: 788
S 1 3 0 793 Assert in file: "AggregationBuilder.c" in line: 793
S 1 3 0 946 Assert in file: "AggregationBuilder.c" in line: 946
S 1 5 0 294 [printGrants] stationID:%d grant:%d
S 1 5 0 321 [printGrants] stationID:%d grant:%d
S 1 5 0 347 [printGrants] stationID:%d grant:%d
S 1 5 0 375 [printPdTypeList] PdType:%d head:%x; tail:%x
S 1 5 0 479 Assert in file: "Atf.c" in line: 479
S 1 5 0 587 Atf_Manager_setAgeing AtfDb.AgeingEnable:%d, AtfDb.AgeingTtlCriteria:%d, AtfDb.end_of_interval_ttl:%d end_of_interval_ttl:%d
S 1 5 0 723 [Atf_Manager_transition] newAtmDistributionType:%d AtfDb.AtmDistributionType: %d; newAtmAlgorithmType: %d interval:%d freeTime:%d
S 1 5 0 750 Assert in file: "Atf.c" in line: 750
S 1 5 0 768 Assert in file: "Atf.c" in line: 768
S 1 5 0 783 Assert in file: "Atf.c" in line: 783
S 1 5 0 803 Assert in file: "Atf.c" in line: 803
S 1 5 0 1110 Assert in file: "Atf.c" in line: 1110
S 1 5 0 1131 Assert in file: "Atf.c" in line: 1131
S 1 5 0 1283 [Atf_GrantCalc_dynamicWeighted] maxGrant %d; ac %d
S 1 5 0 1425 [Atf_Buffering_lockReqHandler] stationId:%d
S 1 5 0 1463 [Atf_Buffering_lockReq] pushToStack stationId:%d
S 1 5 0 1505 [Atf_Buffering_lockCfmMsg] ATF_INVALID_LOCK_IDX stationId:%d
S 1 5 0 1514 [Atf_Buffering_lockCfmMsg] station:%d Lock Cfm msg in wait for lock state
S 1 5 0 1526 [Atf_Buffering_lockCfmMsg] station:%d During locking got timer event
S 1 5 0 1538 [Atf_Buffering_lockCfmMsg] station:%d During locking got stop traffic
S 1 5 0 1550 Assert in file: "Atf.c" in line: 1550
S 1 5 0 1580 [Atf_Buffering_himBufferReq] station:%d 
S 1 5 0 1585 Assert in file: "Atf.c" in line: 1585
S 1 5 0 1586 Assert in file: "Atf.c" in line: 1586
S 1 5 0 1639 [Atf_Buffering_himBufferCfmHandler] stationId:%d
S 1 5 0 1651 [Atf_Buffering_himBufferCfmMsg] During locking the station:%d got timer event
S 1 5 0 1658 [Atf_Buffering_himBufferCfmMsg] During locking the station:%d got stop traffic
S 1 5 0 1687 Assert in file: "Atf.c" in line: 1687
S 1 5 0 1709 [Atf_Buffering_unbufferHim], stationId %d
S 1 5 0 1741 [Atf_Buffering_flushStationQueues] station:%d Flush start
S 1 5 0 1799 [Atf_Buffering_flushStationQueues] managements exist
S 1 5 0 1813 [Atf_Buffering_flushStationQueues] aged exist
S 1 5 0 1837 2[Atf_Buffering_flushStationQueues] AtfBufferedList[%d][%d].head:%x tail:%x
S 1 5 0 1863 [---Atf_Buffering_Unbuffer---], stationId %d
S 1 5 0 1930 [Atf_Buffering_unbufferPushBuffered] AtfBufferedList[%d][%d].head:%x tail:%x
S 1 5 0 1965 [Atf_Buffering_unbufferDropToLiberator] station:%d unbuffer drop start
S 1 5 0 1989 [Atf_Buffering_unbufferPushToQueues] station:%d unbuffer queues start
S 1 5 0 2015 [Atf_Buffering_drop_buffered], stationId %d
S 1 5 0 2060 [Atf_Manager_stopTrafficMsg] stationId:%d
S 1 5 0 2112 [Atf_Buffering_AddStaMsg] stationId:%d
S 1 5 0 2171 [---Atf_Buffering_senderStopTxMsg---], stationId %d
S 1 5 0 2195 [Atf_Buffering_PushPacketToTail] pDesc:%x
S 1 5 0 2197 Assert in file: "Atf.c" in line: 2197
S 1 5 0 2240 [Atf_Buffering_PushListToHead]
S 1 5 0 2487 Assert in file: "Atf.c" in line: 2487
S 1 5 0 2512 Assert in file: "Atf.c" in line: 2512
S 1 5 0 2517 [Atf_buffering_StaSmRun] stationId:%d event:%d currentState:%d
S 1 5 0 2627 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATE_IDLE
S 1 5 0 2632 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_BUFFERED
S 1 5 0 2637 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_UNBUFFERED
S 1 5 0 2642 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_HOSTINTERFACE
S 1 5 0 2647 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_HOSTINTERFACE_STOP_UNBUFFER
S 1 5 0 2652 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_HOSTINTERFACE_STOP_DROP
S 1 5 0 2657 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_LOCK
S 1 5 0 2662 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_LOCK_STOP_UNBUFFER
S 1 5 0 2667 [Atf_SetStationState] stationId: %d, state:ATF_STATION_STATIC_STATE_CONNECTED_WAIT_FOR_LOCK_STOP_DROP
S 1 5 0 2673 [Atf_SetStationState] stationId: %d, state:%d
S 1 8 0 623 Assert in file: "BeaconHandler.c" in line: 623
S 1 8 0 647 Assert in file: "BeaconHandler.c" in line: 647
S 1 8 0 671 Assert in file: "BeaconHandler.c" in line: 671
S 1 8 0 696 beaconHandlerSendTemplateWasSetIndication for vap:%d
S 1 8 0 883 Assert in file: "BeaconHandler.c" in line: 883
S 1 8 0 884 Assert in file: "BeaconHandler.c" in line: 884
S 1 8 0 919 Assert in file: "BeaconHandler.c" in line: 919
S 1 8 0 927 Assert in file: "BeaconHandler.c" in line: 927
S 1 8 0 991 Assert in file: "BeaconHandler.c" in line: 991
S 1 8 0 1335 Assert in file: "BeaconHandler.c" in line: 1335
S 1 8 0 1500 Assert in file: "BeaconHandler.c" in line: 1500
S 1 8 0 1639 Assert in file: "BeaconHandler.c" in line: 1639
S 1 8 0 1713 Assert in file: "BeaconHandler.c" in line: 1713
S 1 8 0 1805 Assert in file: "BeaconHandler.c" in line: 1805
S 1 8 0 1874 Assert in file: "BeaconHandler.c" in line: 1874
S 1 8 0 1923 Assert in file: "BeaconHandler.c" in line: 1923
S 1 8 0 2091 Assert in file: "BeaconHandler.c" in line: 2091
S 1 8 0 2349 Assert in file: "BeaconHandler.c" in line: 2349
S 1 8 0 2391 Assert in file: "BeaconHandler.c" in line: 2391
S 1 8 0 2472 Assert in file: "BeaconHandler.c" in line: 2472
S 1 8 0 2510 Assert in file: "BeaconHandler.c" in line: 2510
S 1 8 0 2546 Assert in file: "BeaconHandler.c" in line: 2546
S 1 8 0 2757 Assert in file: "BeaconHandler.c" in line: 2757
S 1 8 0 2779 Assert in file: "BeaconHandler.c" in line: 2779
S 1 8 0 2801 Assert in file: "BeaconHandler.c" in line: 2801
S 1 8 0 2823 Assert in file: "BeaconHandler.c" in line: 2823
S 1 11 0 157 channelSwitchManager_ChangeState from %d, to %d
S 1 11 0 198 Assert in file: "ChannelSwitchManager.c" in line: 198
S 1 11 0 205 [channelSwitchManager_SetChannelRequest] CHANNEL_SWITCH_MANAGER_STATE_IDLE, channelSwitchManagerParams.pUmSetChannelParams->switch_type=%d
S 1 11 0 228 [channelSwitchManager_SetChannelRequest] in RSSI 0
S 1 11 0 259 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: illegal switch type
S 1 11 0 265 [channelSwitchManager_SetChannelRequest] in RSSI 1
S 1 11 0 334 Assert in file: "ChannelSwitchManager.c" in line: 334
S 1 11 0 366 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal type in current state
S 1 11 0 371 Assert in file: "ChannelSwitchManager.c" in line: 371
S 1 11 0 386 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 421 [channelSwitchManager_ProcessStartConfirm] channelSwitchManagerParams.state = %d, channelSwitchManagerParams.pUmSetChannelParams->switch_type = %d
S 1 11 0 423 Assert in file: "ChannelSwitchManager.c" in line: 423
S 1 11 0 449 [channelSwitchManager_ProcessStartConfirm] send message to HDK
S 1 11 0 491 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: illegal switch type
S 1 11 0 495 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 532 state: %d, event: Tx Queue Lock Confirm
S 1 11 0 604 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 630 [channelSwitchManager_ProcessFinishConfirm] channelSwitchManagerParams.state = %d
S 1 11 0 643 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 684 [channelSwitchManager_SetChannelConfirm] channelSwitchManagerParams.state = %d
S 1 11 0 693 [channelSwitchManager_SetChannelConfirm] CHANNEL_SWITCH_MANAGER_STATE_WAIT_FOR_SET_CHANNEL_CFM_FROM_HDK, channelSwitchManagerParams.pUmSetChannelParams->switch_type = %d
S 1 11 0 726 [channelSwitchManager_SetChannelConfirm] in ST_NORMAL_AFTER_RSSI
S 1 11 0 727 [channelSwitchManager_SetChannelConfirm], pUmSetChannelParamsLocal->u16SID = %d, pRssiParams->vapId = %d
S 1 11 0 731 [channelSwitchManager_SetChannelConfirm] in ST_NORMAL_AFTER_RSSI, before Process Manager Resume all
S 1 11 0 745 [channelSwitchManager_SetChannelConfirm], pUmSetChannelParamsLocal->u16SID = %d, pRssiParams->vapId = %d
S 1 11 0 746 [channelSwitchManager_SetChannelConfirm] in ST_RSSI
S 1 11 0 812 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: illegal switch type
S 1 11 0 818 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 845 state: %d, event: Tx Resume Confirm
S 1 11 0 864 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 890 state: %d, event: Rx Resume Confirm
S 1 11 0 910 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 937 state: %d, event: Tx Pause Confirm
S 1 11 0 969 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 997 state: %d, event: TX Pause VAP Confirm
S 1 11 0 1063 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1092 state: %d, event: Rx Pause Confirm
S 1 11 0 1134 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1162 state: %d, event: Timer Expired
S 1 11 0 1193 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1222 state: %d, event: Beacon Add Csa Ie Confirm
S 1 11 0 1250 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1280 state: %d, event: CSA Beacon Done Indication
S 1 11 0 1338 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1367 state: %d, event: Stop CSA Beacons Confirm
S 1 11 0 1406 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Channel Switch Manager: illegal event in current state
S 1 11 0 1523 channelSwitchManager_VapManagerRegistrationEventAddVap, state: %d, event: Vap Manager Registration Event Add Vap
S 1 11 0 1525 Assert in file: "ChannelSwitchManager.c" in line: 1525
S 1 11 0 1568 state: %d, event: Vap Manager Registration Event Post Remove Vap
S 1 11 0 1570 Assert in file: "ChannelSwitchManager.c" in line: 1570
S 1 11 0 1609 state: %d, event: Csa Manager Start Tx Cfm
S 1 11 0 1670 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: channelSwitchManager_ProcessInterruptedIndication
S 1 11 0 1698 state: %d, event: Csa Manager Stop Tx Cfm
S 1 11 0 1782 [channelSwitchManager_SendConfirmationToHost] channelSwitchManagerParams.pUmSetChannelParams->rssi[%d] = %d
S 1 11 0 1792 [channelSwitchManager_SendConfirmationToHost] --------------------------end]
S 1 11 0 1821 Assert in file: "ChannelSwitchManager.c" in line: 1821
S 1 11 0 1859 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetPrimaryChannel: 80+80 not supported
S 1 11 0 1862 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetPrimaryChannel: Illegal rate
S 1 11 0 1910 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetSecondayChannelOffset: 80+80 not supported
S 1 11 0 1913 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: Utils_GetSecondayChannelOffset: Illegal rate
S 1 11 0 1953 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetChannelWidth: not supported
S 1 11 0 1956 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetChannelWidth: not supported
S 1 11 0 1959 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetChannelWidth: Illegal channel width
S 1 11 0 2002 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetCenterFreq0Idx: not supported
S 1 11 0 2005 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetCenterFreq0Idx: not supported
S 1 11 0 2008 Fatal Error in file: "ChannelSwitchManager.c"; Fatal Print: ChannelSwitchManager_GetCenterFreq0Idx: Illegal channel width
S 1 11 0 2058 Assert in file: "ChannelSwitchManager.c" in line: 2058
S 1 14 0 216 CTS Manager changed from %d to %d
S 1 14 0 749 Fatal Error in file: "CtsManager.c"; Fatal Print: CTS Manager Fatal
S 1 14 0 795 Assert in file: "CtsManager.c" in line: 795
S 1 17 4 131 RX TH - WriteRxTh2Phy THval: %d
S 1 17 4 202 RX TH - SetRxThReq THval: %d
S 1 17 4 246 RX TH - WriteMinRssi2Phy regVal: %d minRssi: %d
S 1 17 4 298 RX TH - RxThRemoveSta staId: %d , rssiVal %d
S 1 17 4 300 Assert in file: "StatisticsHandler.c" in line: 300
S 1 17 4 357 RX TH - RxThUpdateRssi newRssi: %d oldRssi:%d
S 1 17 4 359 Assert in file: "StatisticsHandler.c" in line: 359
S 1 17 4 441 RX TH - RxThAddSta staId: %d rssiVal:%d
S 1 17 1 129 RX TH - WriteRxTh2Phy THval: %d
S 1 17 1 197 RX TH - SetRxThReq THval: %d
S 1 17 1 239 RX TH - WriteMinRssi2Phy regVal: %d minRssi: %d
S 1 17 1 288 RX TH - RxThRemoveSta staId: %d , rssiVal %d
S 1 17 1 289 Assert in file: "StatisticsHandler.c" in line: 289
S 1 17 1 344 RX TH - RxThUpdateRssi newRssi: %d oldRssi:%d
S 1 17 1 345 Assert in file: "StatisticsHandler.c" in line: 345
S 1 17 1 425 RX TH - RxThAddSta staId: %d rssiVal:%d
S 1 20 0 661 Fatal Error in file: "ErrorHandler.c"; Fatal Print: Lower MAC Assertion
S 1 20 0 686 Assert in file: "ErrorHandler.c" in line: 686
S 1 20 0 718 Fatal Error in file: "ErrorHandler.c"; Fatal Print: Assert Requested by the Host
S 1 20 0 899 Assert in file: "ErrorHandler.c" in line: 899
S 1 27 3 576 START AFE CALIBRATION
S 1 27 3 605 retVal=%d, packetMod=%d
S 1 27 3 610 packetMod=%d,pElements->results.offlineModulationType=%d 
S 1 27 3 614 exit ALB mode, calibration end!
S 1 27 3 621 LastClRunTime: %d
S 1 27 3 681 QBF calibration finished
S 1 27 3 709 Setting TPC: %d, for extPa = %d
S 1 27 3 824 Assert in file: "BeamFormingClbrHndlr.c" in line: 824
S 1 27 3 831 agcGains(ant %d). lnaIndx = %d pgc1Indx = %d pgc2Indx = %d pgc3Indx = %d
S 1 27 3 841 Send packet %d => %d
S 1 27 3 857 Packet sent from ant %d to ant %d
S 1 27 3 876 BM calibration fail! number of recorded bins from sessions not identical
S 1 27 3 901 StopRisc called
S 1 27 3 938 Assert in file: "BeamFormingClbrHndlr.c" in line: 938
S 1 27 3 948 StartRisc called
S 1 27 3 987 TRSW: %x %x %x
S 1 27 3 1076 Assert in file: "BeamFormingClbrHndlr.c" in line: 1076
S 1 27 3 1100 Assert in file: "BeamFormingClbrHndlr.c" in line: 1100
S 1 27 3 1149 Registers values were not saved, cannot restore them
S 1 27 3 1150 Assert in file: "BeamFormingClbrHndlr.c" in line: 1150
S 1 27 3 1155 Stop risc
S 1 27 3 1171 Run risc
S 1 27 3 1217 Assert in file: "BeamFormingClbrHndlr.c" in line: 1217
S 1 27 3 1266 BF Calibration Failed!! could not achieve a good channel
S 1 27 3 1282 triggerTB
S 1 27 3 1344 Record Channel Failed !! packet did not arrive in time
S 1 27 3 1356 Record Channel Failed!! wrong channel size, CB: %d, numOfBins:%d
S 1 27 3 1367 Record Channel Failed!! Wrong Packet received with length %d
S 1 27 3 1381 Record channel failed!!! CRC error
S 1 27 3 1432 Assert in file: "BeamFormingClbrHndlr.c" in line: 1432
S 1 27 3 1438 Record %d bins
S 1 27 3 1586 CaluclateCalResult, calPair=%d
S 1 27 3 1588 Assert in file: "BeamFormingClbrHndlr.c" in line: 1588
S 1 27 3 1650 NCB mode: Start checking phase jump
S 1 27 3 1659 PhaseDiff = %d
S 1 27 3 1668 Phase jump found! correcting K calibration
S 1 27 3 1693 Phase jump not found
S 1 27 3 1776 Assert in file: "BeamFormingClbrHndlr.c" in line: 1776
S 1 27 3 1865 Assert in file: "BeamFormingClbrHndlr.c" in line: 1865
S 1 27 3 1881 START AGC GAINS CALIBRATION
S 1 27 3 1892 START K CALIBRATION
S 1 27 3 1916 START AGC OFFSET CALIBRATION
S 1 27 3 1924 START TX OFFSET CALIBRATION
S 1 27 3 1931 exit ALB mode, calibration end!, calStatus = %X
S 1 27 3 1961 Start K%d calibration, CB=%d
S 1 27 3 1999 extGainDb = %d, extGain = %d, trAttenDb = %d
S 1 27 3 2077 relative gain = %d
S 1 27 3 2102 Assert in file: "BeamFormingClbrHndlr.c" in line: 2102
S 1 27 3 2118 Warning: working at %d instead of 15 dB backoff
S 1 27 3 2126 BF Calibration Failed !! Attenuation between antennas too high:%d
S 1 27 3 2151 Send packet: Ant%d->Ant%d
S 1 27 3 2152 trSwTxAnt: %d
S 1 27 3 2324 Assert in file: "BeamFormingClbrHndlr.c" in line: 2324
S 1 27 3 2365 digital gain %d
S 1 27 3 2376 running for gains : LnaIndex %d, pgc1Index %d, pgc2Index %d,pgc3Index %d
S 1 27 3 2624 Assert in file: "BeamFormingClbrHndlr.c" in line: 2624
S 1 27 3 2806 Assert in file: "BeamFormingClbrHndlr.c" in line: 2806
S 1 27 3 2856 BF Calibration Failed!! could not achieve a good channel
S 1 27 3 2881 DisTxCancel
S 1 27 3 2888 EnTxCancel
S 1 29 16 701 Assert in file: "RficDriver.c" in line: 701
S 1 29 16 748 Assert in file: "RficDriver.c" in line: 748
S 1 29 16 793 Assert in file: "RficDriver.c" in line: 793
S 1 29 16 1033 Assert in file: "RficDriver.c" in line: 1033
S 1 29 16 1152 Assert in file: "RficDriver.c" in line: 1152
S 1 29 16 1153 Assert in file: "RficDriver.c" in line: 1153
S 1 29 16 1154 Assert in file: "RficDriver.c" in line: 1154
S 1 29 16 1230 Assert in file: "RficDriver.c" in line: 1230
S 1 29 16 1342 Assert in file: "RficDriver.c" in line: 1342
S 1 29 16 1404 Assert in file: "RficDriver.c" in line: 1404
S 1 29 16 1452 Assert in file: "RficDriver.c" in line: 1452
S 1 29 16 1493 Assert in file: "RficDriver.c" in line: 1493
S 1 29 16 1537 Assert in file: "RficDriver.c" in line: 1537
S 1 29 16 1577 Assert in file: "RficDriver.c" in line: 1577
S 1 29 16 1682 Assert in file: "RficDriver.c" in line: 1682
S 1 29 16 1760 Assert in file: "RficDriver.c" in line: 1760
S 1 29 16 1775 Assert in file: "RficDriver.c" in line: 1775
S 1 29 16 1842 Assert in file: "RficDriver.c" in line: 1842
S 1 29 16 1938 RficDriver_SetFrequency
S 1 29 16 1965 [RficDriver_SetFrequency], Flo = %d
S 1 29 16 2124 Assert in file: "RficDriver.c" in line: 2124
S 1 29 16 2238 Assert in file: "RficDriver.c" in line: 2238
S 1 29 16 2338 Assert in file: "RficDriver.c" in line: 2338
S 1 29 16 2396 Assert in file: "RficDriver.c" in line: 2396
S 1 29 16 2479 Assert in file: "RficDriver.c" in line: 2479
S 1 29 16 2480 Assert in file: "RficDriver.c" in line: 2480
S 1 29 16 2520 Assert in file: "RficDriver.c" in line: 2520
S 1 29 16 2521 Assert in file: "RficDriver.c" in line: 2521
S 1 29 16 2597 Assert in file: "RficDriver.c" in line: 2597
S 1 29 16 2637 Assert in file: "RficDriver.c" in line: 2637
S 1 29 16 2770 Assert in file: "RficDriver.c" in line: 2770
S 1 32 0 315 [hostInterfaceRingsSetAtfBufferEnable] stationId:%d
S 1 32 0 344 [hostInterfaceRingsSetAtfBufferDisable]
S 1 32 0 396 Assert in file: "HostInterface.c" in line: 396
S 1 32 0 398 Assert in file: "HostInterface.c" in line: 398
S 1 32 0 404 HostInterface_RestrictedAcMsg: User indicates that Restricted AC should not be used by HOST I/F TASK. QoS TASK shall use it.
S 1 32 0 795 Assert in file: "HostInterface.c" in line: 795
S 1 32 0 826 Fatal Error in file: "HostInterface.c"; Fatal Print: Error buffer descriptor in FIFO!
S 1 32 0 848 Assert in file: "HostInterface.c" in line: 848
S 1 32 0 927 Ts Manager, Send Confirmation, Client %d, SID %d
S 1 32 0 1046 Assert in file: "HostInterface.c" in line: 1046
S 1 32 0 1049 Assert in file: "HostInterface.c" in line: 1049
S 1 32 0 1061 Assert in file: "HostInterface.c" in line: 1061
S 1 32 0 1360 Assert in file: "HostInterface.c" in line: 1360
S 1 32 0 1369 Assert in file: "HostInterface.c" in line: 1369
S 1 32 0 1406 Fatal Error in file: "HostInterface.c"; Fatal Print: Error buffer descriptor in FIFO!
S 1 32 0 1496 Assert in file: "HostInterface.c" in line: 1496
S 1 32 0 1535 Assert in file: "HostInterface.c" in line: 1535
S 1 32 0 1569 HostInterface_GlobalDb.atf_AgeingEnable %d ttlCount %d, HostInterface_GlobalDb.atf_End_of_interval_ttl %d, HostInterface_GlobalDb.atf_AgeingTtlCriteria %d
S 1 32 0 1570 willAged%d
S 1 32 1 346 hostInterfaceRingsConvertDriverHdsToPds, numOfHds %d
S 1 32 1 352 Assert in file: "HostInterfaceRings.c" in line: 352
S 1 32 1 407 Assert in file: "HostInterfaceRings.c" in line: 407
S 1 32 1 415 Assert in file: "HostInterfaceRings.c" in line: 415
S 1 32 1 416 Assert in file: "HostInterfaceRings.c" in line: 416
S 1 32 1 438 hostInterfaceRingsConvertDriverHdsToRds, numOfHds %d
S 1 32 1 447 Assert in file: "HostInterfaceRings.c" in line: 447
S 1 32 1 460 Assert in file: "HostInterfaceRings.c" in line: 460
S 1 32 1 476 hostInterfaceRingsConvertDriverRdsToHds, numOfHds %d
S 1 32 1 527 hostInterfaceRingsConvertDriverRdsToHds, hd2RdCounter %d
S 1 32 1 540 hostInterfaceRingsConvertDriverPdsToHds, numOfHds %d
S 1 32 1 612 hostInterfaceRingsConvertDriverPdsToHds, hd2PdCounter %d
S 1 32 1 740 Assert in file: "HostInterfaceRings.c" in line: 740
S 1 32 1 963 Assert in file: "HostInterfaceRings.c" in line: 963
S 1 32 1 992 Assert in file: "HostInterfaceRings.c" in line: 992
S 1 32 1 993 Assert in file: "HostInterfaceRings.c" in line: 993
S 1 32 1 1041 Assert in file: "HostInterfaceRings.c" in line: 1041
S 1 32 1 1042 Assert in file: "HostInterfaceRings.c" in line: 1042
S 1 33 8 150 Assert in file: "PacTim.c" in line: 150
S 1 44 0 316 Assert in file: "logger.c" in line: 316
S 1 44 0 504 Assert in file: "logger.c" in line: 504
S 1 44 0 508 Assert in file: "logger.c" in line: 508
S 1 44 0 530 Assert in file: "logger.c" in line: 530
S 1 44 0 531 Assert in file: "logger.c" in line: 531
S 1 44 0 629 Assert in file: "logger.c" in line: 629
S 1 44 0 891 Assert in file: "logger.c" in line: 891
S 1 44 0 936 Assert in file: "logger.c" in line: 936
S 1 44 0 1046 Assert in file: "logger.c" in line: 1046
S 1 44 0 1239 Assert in file: "logger.c" in line: 1239
S 1 44 0 1294 Assert in file: "logger.c" in line: 1294
S 1 44 0 1298 Assert in file: "logger.c" in line: 1298
S 1 44 0 1320 ** missed logs: lack of buffers: %d, lack of BD: %d
S 1 44 0 1362 Assert in file: "logger.c" in line: 1362
S 1 44 0 1400 Assert in file: "logger.c" in line: 1400
S 1 44 0 1416 Assert in file: "logger.c" in line: 1416
S 1 50 0 315 Assert in file: "PacketTrafficArbitrator.c" in line: 315
S 1 50 0 321 [PTA][PtaTest] Test command received
S 1 50 0 359 [PTA][PtaTestDriverReq]
S 1 50 0 371 [PTA][PtaTestEmulateGpio0Int] btActiveVal = %d txDemandVal = %d
S 1 50 0 387 [PTA][PtaTestReset]
S 1 50 0 435 [PTA][REP][PtaTestRep]
S 1 50 0 458 [PTA][PtaTestModifyQosParam] bUseRepetitionMoe value = %d
S 1 50 0 472 [PTA][PtaTestModifyQosParam] Suspend new value = %d will use = %d old value = %d resume = %d
S 1 50 0 487 [PTA][PtaTestModifyQosParam] Resume new value = %d will use = %d old value = %d suspend = %d
S 1 50 0 498 [PTA][PtaTestModifyQosParam] ZigBee radioHoldOffValue new value = %d old value = %d
S 1 50 0 509 [PTA][PtaTestModifyQosParam] ZigBee starvationTimeValue new value = %d old value = %d
S 1 50 0 521 [PTA][PtaTestModifyQosParam] BT radioHoldOffValue new value = %d old value = %d
S 1 50 0 533 [PTA][PtaTestModifyQosParam] BT starvationTimeValue new value = %d old value = %d
S 1 50 0 543 [PTA][PtaTestModifyQosParam] you are trying to change a PTA parameter but with wrong "parameter". allwoed values are 0 - 6
S 1 50 0 813 [PTA][ptaInit]
S 1 50 0 848 [PTA][ptaInit] Feature is disabled
S 1 50 0 879 [PTA][PtaPendingDriverReq]
S 1 50 0 887 Assert in file: "PacketTrafficArbitrator.c" in line: 887
S 1 50 0 917 Assert in file: "PacketTrafficArbitrator.c" in line: 917
S 1 50 0 919 [PTA][PtaStateChange] currentState = %d nextState = %d
S 1 50 0 1027 Assert in file: "PacketTrafficArbitrator.c" in line: 1027
S 1 50 0 1029 Assert in file: "PacketTrafficArbitrator.c" in line: 1029
S 1 50 0 1031 Assert in file: "PacketTrafficArbitrator.c" in line: 1031
S 1 50 0 1044 [PTA][PtaStateInitTestCommand]
S 1 50 0 1172 [PTA][PtaStateTxStarvationTimerExpired] State = %d isGrantHigh = %d isBtActiveHigh = %d isTxDemandHigh = %d
S 1 50 0 1176 Assert in file: "PacketTrafficArbitrator.c" in line: 1176
S 1 50 0 1224 [PTA][PtaStateTestStarvationTimerExpired] State = %d 
S 1 50 0 1226 Assert in file: "PacketTrafficArbitrator.c" in line: 1226
S 1 50 0 1249 [PTA][PtaMoveToIdle]
S 1 50 0 1329 [PTA][PtaZigBeeDenyError] ZigBee does not understand DENY
S 1 50 0 1334 Assert in file: "PacketTrafficArbitrator.c" in line: 1334
S 1 50 0 1348 [PTA][PtaGrantNotUsed] radio = %d is not using the grant
S 1 50 0 1354 Assert in file: "PacketTrafficArbitrator.c" in line: 1354
S 1 50 0 1363 [PTA][PtaStartBtTx]
S 1 50 0 1378 [PTA][PtaStartZigBeeTx]
S 1 50 0 1399 [PTA][PtaTxOngoing] BT = %d
S 1 50 0 1482 [PTA][PtaHandle24GCoExReq]  Driver: ON
S 1 50 0 1498 [PTA][PtaHandle24GCoExReq] Delaying the handling of Driver command since PTA is not in IDLE. PTA State = %d
S 1 50 0 1507 [PTA][PtaHandle24GCoExReq] Driver: all other radios off
S 1 50 0 1520 [PTA][PtaHandle24GCoExReq] Driver: 2.4G co-ex feature is off
S 1 50 0 1538 [PTA][GPIO ERROR][PtaTestGpioValueIsWrong] GPIO = %d ERROR = %d
S 1 50 0 1556 [PTA][PtaTestHwTimerIsOK] Test completed OK
S 1 50 0 1591 [PTA][PtaGpioDetermineEvent] btCounter = %d BT->radioHoldOffValue = %d ZigBeeCounter = %d ZigBee->radioHoldOffValue = %d
S 1 50 0 1643 [PTA][PtaStarvationTimerStart] timeToGo = %d
S 1 50 0 1652 [PTA][PtaStarvationTimerStop]
S 1 50 0 1806 [PTA][Isr_PtaGpio0] BT_ACTIVE = %d TX_DEMAND = %d state = %d
S 1 50 0 1821 [PTA][Isr_PtaGpio0] ptaSmEvents = %d
S 1 50 0 1835 Assert in file: "PacketTrafficArbitrator.c" in line: 1835
S 1 50 0 1848 [PTA][Isr_MipsTimer1]
S 1 50 0 1853 Assert in file: "PacketTrafficArbitrator.c" in line: 1853
S 1 50 0 1907 [PTA][PtaHwTimerDetermineEvent] event = %d
S 1 50 0 1996 [PTA][PtaPhyTxRegisterSet] register = %d write regVal = 0x%x
S 1 50 0 2051 [PTA][PtaIgnoreEvent] State = %d event = %d									*** que pasa? ***
S 1 50 0 2055 Assert in file: "PacketTrafficArbitrator.c" in line: 2055
S 1 50 0 2067 Assert in file: "PacketTrafficArbitrator.c" in line: 2067
S 1 50 0 2085 [PTA][PtaIllegalEvent] State = %d event = %d									*** que pasa? ***
S 1 50 0 2089 Assert in file: "PacketTrafficArbitrator.c" in line: 2089
S 1 54 2 248 Sec Manager, Send Confirmation, Client %d, SID %d
S 1 54 2 279 SEC Manager STA Manager, Station %d changed from %d to %d
S 1 54 2 961 Fatal Error in file: "secManager_StaManager.c"; Fatal Print: SEC Manager STA Manager Fatal
S 1 54 2 1001 Assert in file: "secManager_StaManager.c" in line: 1001
S 1 54 2 1103 Assert in file: "secManager_StaManager.c" in line: 1103
S 1 54 2 1143 Assert in file: "secManager_StaManager.c" in line: 1143
S 1 54 2 1184 Assert in file: "secManager_StaManager.c" in line: 1184
S 1 54 2 1224 Assert in file: "secManager_StaManager.c" in line: 1224
S 1 75 0 304 Statistics Manager, Send Confirmation, Client %d, SID %d
S 1 75 0 335 Statistics Manager, Send Confirmation, VapId %d
S 1 75 0 508 statisticsManagerIncrease %d %d %d %d
S 1 75 0 529 statisticsManagerDecrease %d %d %d %d
S 1 75 0 558 Fatal Error in file: "StatisticsManager.c"; Fatal Print: statisticsManagerArithmetic
S 1 75 0 606 Fatal Error in file: "StatisticsManager.c"; Fatal Print: statisticsManagerSet
S 1 75 0 673 Fatal Error in file: "StatisticsManager.c"; Fatal Print: statisticsManagerSet
S 1 75 0 818 Assert in file: "StatisticsManager.c" in line: 818
S 1 75 0 980 Assert in file: "StatisticsManager.c" in line: 980
S 1 75 0 984 Assert in file: "StatisticsManager.c" in line: 984
S 1 75 0 1088 Assert in file: "StatisticsManager.c" in line: 1088
S 1 75 0 1093 Assert in file: "StatisticsManager.c" in line: 1093
S 1 75 0 1094 Assert in file: "StatisticsManager.c" in line: 1094
S 1 75 0 1124 Assert in file: "StatisticsManager.c" in line: 1124
S 1 75 0 1125 Assert in file: "StatisticsManager.c" in line: 1125
S 1 75 0 1187 Assert in file: "StatisticsManager.c" in line: 1187
S 1 75 0 1188 Assert in file: "StatisticsManager.c" in line: 1188
S 1 75 0 1221 Fatal Error in file: "StatisticsManager.c"; Fatal Print: Current implementation: table stored in IRAM
S 1 75 0 1671 Assert in file: "StatisticsManager.c" in line: 1671
S 1 75 0 1706 Assert in file: "StatisticsManager.c" in line: 1706
S 1 75 0 1855 pGetAocsInfo->dynamicBW20MHz, %d
S 1 75 0 1856 pGetAocsInfo->dynamicBW40MHz, %d
S 1 75 0 1857 pGetAocsInfo->dynamicBW80MHz, %d
S 1 75 0 1858 pGetAocsInfo->extStaRx, %d
S 1 75 0 1859 pGetAocsInfo->noiseFloor, %d
S 1 75 0 1860 pGetAocsInfo->TxPower, %d
S 1 75 0 1861 pGetAocsInfo->channelLoad, %d
S 1 75 0 1862 pGetAocsInfo->CWIvalue, %d
S 1 75 0 1863 numOfStationCounter, %d
S 1 75 0 1864 averageRssi, %d
S 1 75 0 1865 pGetAocsInfo->RSSI, %d
S 1 75 0 1866 pGetAocsInfo->SNR, %d
S 1 75 0 1867 phyRxStatusDb.devicePhyRxStatus.rf_gain[ant], %d
S 1 75 0 1933 Assert in file: "StatisticsManager.c" in line: 1933
S 1 75 0 2101 Assert in file: "StatisticsManager.c" in line: 2101
S 1 75 0 2111 Assert in file: "StatisticsManager.c" in line: 2111
S 1 75 0 2187 Assert in file: "StatisticsManager.c" in line: 2187
S 1 75 0 2203 Assert in file: "StatisticsManager.c" in line: 2203
S 1 75 0 2205 Assert in file: "StatisticsManager.c" in line: 2205
S 1 75 0 2287 j:%d i:%d
S 1 75 0 2349 %d %d
S 1 45 0 121 Assert in file: "System_Main.c" in line: 121
S 1 78 0 235 Assert in file: "TrainingManager.c" in line: 235
S 1 78 0 242 TrainingManager_RunStateMachine: CurrentState = %d, event = %d
S 1 78 0 252 TrainingManager_ChangeState: newState = %d
S 1 78 0 312 Fatal Error in file: "TrainingManager.c"; Fatal Print: TrainingManager_IllegalEvent
S 1 78 0 339 TrainingManager_SendLaInfoReq, muActiveVapBitmap = 0x%04X
S 1 78 0 391 TrainingManager_CheckNdpaConfirmationStatus, Status = %d
S 1 78 0 419 Group Manager result BW = %d
S 1 78 0 453 TrainingManager_StopTrainingDuringTraining
S 1 78 0 484 TrainingManager_StopTrainingDuringWaitingForLaInfo
S 1 78 0 523 TrainingManager_AddVap, new VAP id = %d
S 1 78 0 664 TrainingManager_RemoveStaNotDuringTraining, sta Id = 0x%X
S 1 78 0 710 TrainingManager_RemoveStaDuringTraining, sta Id = 0x%X
S 1 78 0 774 TrainingManager_RemoveStaDuringStopping, sta Id = 0x%X
S 1 78 0 825 TrainingManager_HaltStaNotDuringTraining, sta Id = 0x%X
S 1 78 0 859 TrainingManager_HaltStaDuringTraining, sta Id = 0x%X
S 1 78 0 914 TrainingManager_StopStaDuringTraining, sta Id = 0x%X
S 1 78 0 1011 TrainingManager_SendTrainingStoppedConfirmation, cfmBitmap = 0x%08X, 0x%08X
S 1 78 0 1045 TrainingManager_IgnoreStopTraining
S 1 78 0 1084 TrainingManager_StartTraining, num of connected station = %d, All active vaps bitmap = 0x%04X, MU active vaps bitmap = 0x%04X, num of Pools = %d
S 1 78 0 1090 VAP SELECTED!!!, VAP ID = %d
S 1 78 0 1146 Build test plan and Training Vector finished, send Start Tx to NDPA Manager, num of station = %d, VAP ID = %d
S 1 78 0 1155 VAP NOT SELECTED!!!
S 1 78 0 1211 TrainingManager_BuildPools, input is active sta bitmap from Link adaptive:
S 1 78 0 1220 Final Active STA bitmap
S 1 78 0 1239 current VAP Id = %d
S 1 78 0 1267 Current feature bitmap for station %d = 0x%08X
S 1 78 0 1347 Start select stations!!! , pool id = %d
S 1 78 0 1382 Assert in file: "TrainingManager.c" in line: 1382
S 1 78 0 1415 STA index selected = %X
S 1 78 0 1451 Start Building Test Plan!!! , pool id = %d, current policies bitmap = 0x%04X, num of atennas = %d
S 1 78 0 1466 TrainingManager_BuildTestPlan: currentPlicyBitmap = 0x%04X, currentPolicy = %d
S 1 78 0 1476 Start Building Test Plan!!! , pool id = %d
S 1 78 0 1515 TrainingManager_StartResultsProcessing
S 1 78 0 1563 TrainingManager_UpdateGroupCombinationTable, poolId = %d, testPlanPoliciesBitmap = 0x%04X, num of antennas = %d
S 1 78 0 1578 TrainingManager_UpdateGroupCombinationTable: currentPlicyBitmap = 0x%04X, currentPolicy = %d
S 1 78 0 1588 TrainingManager_UpdateGroupCombinationTable, poolId = %d
S 1 78 0 1622 Bulding Test Plan for policy 0
S 1 78 0 1628 Bulding Test Plan for policy 1
S 1 78 0 1635 Bulding Test Plan for policy 2
S 1 78 0 1644 Bulding Test Plan for policy 3
S 1 78 0 1650 Bulding Test Plan for policy 4
S 1 78 0 1656 Bulding Test Plan for policy 5
S 1 78 0 1665 Bulding Test Plan for policy 6
S 1 78 0 1704 Bulding Test Plan for Segment 1xxx
S 1 78 0 1730 Num of combinations in 1XXX segment is %d
S 1 78 0 1749 Bulding Test Plan for Segment 2xxx
S 1 78 0 1779 Num of combinations in 2XXX segment is %d
S 1 78 0 1799 Bulding Test Plan for Segment 22xx
S 1 78 0 1846 Num of combinations in 22XX segment is %d
S 1 78 0 1867 Bulding Test Plan for Segment 21xx
S 1 78 0 1912 Num of combinations in 21XX segment is %d
S 1 78 0 1931 Bulding Test Plan for Segment 12xx
S 1 78 0 1976 Num of combinations in 12XX segment is %d
S 1 78 0 1996 Bulding Test Plan for Segment 11xx
S 1 78 0 2036 Num of combinations in 11XX segment is %d
S 1 78 0 2055 Bulding Test Plan for Segment 111x
S 1 78 0 2102 Num of combinations in 111X segment is %d
S 1 78 0 2120 Bulding Test Plan for Segment 211x
S 1 78 0 2172 Num of combinations in 211X segment is %d
S 1 78 0 2191 Bulding Test Plan for Segment 121x
S 1 78 0 2243 Num of combinations in 121X segment is %d
S 1 78 0 2262 Bulding Test Plan for Segment 112x
S 1 78 0 2314 Num of combinations in 112X segment is %d
S 1 78 0 2334 Bulding Test Plan for Segment 1111
S 1 78 0 2387 Num of combinations in 1111 segment is %d
S 1 78 0 2420 Update Group Combination table for policy 0
S 1 78 0 2427 Update Group Combination table for policy 1
S 1 78 0 2435 Update Group Combination table for policy 2
S 1 78 0 2445 Update Group Combination table for policy 3
S 1 78 0 2452 Update Group Combination table for policy 4
S 1 78 0 2459 Update Group Combination table for policy 5
S 1 78 0 2469 Update Group Combination table for policy 6
S 1 78 0 2504 Update Group Combination table for Segment 1xxx, output lines:
S 1 78 0 2538 Update Group Combination table for Segment 2xxx, output lines:
S 1 78 0 2578 Update Group Combination table for Segment 22xx, output lines:
S 1 78 0 2645 Update Group Combination table for Segment 21xx, output lines:
S 1 78 0 2712 Update Group Combination table for Segment 12xx, output lines:
S 1 78 0 2779 Update Group Combination table for Segment 11xx, output lines:
S 1 78 0 2842 Update Group Combination table for Segment 111x, output lines:
S 1 78 0 2912 Update Group Combination table for Segment 211x, output lines:
S 1 78 0 2987 Update Group Combination table for Segment 121x, output lines:
S 1 78 0 3061 Update Group Combination table for Segment 112x, output lines:
S 1 78 0 3135 Update Group Combination table for Segment 1111, output lines:
S 1 78 0 3291 Calculated group mark = %d
S 1 78 0 3340 Group combination table for table index %d is updated!!!
S 1 78 0 4017 Fatal Error in file: "TrainingManager.c"; Fatal Print: TrainingManager_Init
S 1 79 1 564 Fatal Error in file: "TsManagerInitiator.c"; Fatal Print: TS Manager Initiator Fatal
S 1 79 1 593 TS Manager Initiator Change SID %d, TID %d, State from %d to %d
S 1 79 1 1882 Assert in file: "TsManagerInitiator.c" in line: 1882
S 1 79 1 2233 tsManagerInitiatorBarConfirmedInOpenedSending station index = %d tid = %d
S 1 79 1 2401 tsManagerInitiatorBarStatusInOpenedSending status %d
S 1 79 1 2428 tsManagerInitiatorBarStatusInOpenedSending normal flow
S 1 79 1 3307 Assert in file: "TsManagerInitiator.c" in line: 3307
S 1 79 1 3342 Assert in file: "TsManagerInitiator.c" in line: 3342
S 1 79 1 3390 Assert in file: "TsManagerInitiator.c" in line: 3390
S 1 79 1 3921 Assert in file: "TsManagerInitiator.c" in line: 3921
S 1 79 1 3977 tsManagerInitiatorFlushIllegalPackets 
S 1 79 1 4524 Assert in file: "TsManagerInitiator.c" in line: 4524
S 1 79 1 4759 TsManagerInitiator_BarConfirmed TsDb->commonPart.stationId %d tid %d state %d
S 1 79 1 4799 TsManagerInitiator_BarStatus TsDb->commonPart.stationId %d tid %d state %d
S 1 79 1 4832 TsManagerInitiator_PdAllocated TsDb->commonPart.stationId %d tid %d state %d
S 1 79 1 4875 Assert in file: "TsManagerInitiator.c" in line: 4875
S 1 79 1 4918 TsManagerInitiator_DiscardedPacket TsDb->commonPart.stationId %d tid %d state %d
S 1 79 1 4954 TsManagerInitiator_QueueIsLocked TsDb->commonPart.stationId %d tid %d state %d
S 1 79 1 5355 Assert in file: "TsManagerInitiator.c" in line: 5355
S 1 79 1 5357 Assert in file: "TsManagerInitiator.c" in line: 5357
S 1 82 1 504 TX Manager STA Manager, Station %d changed from %d to %d
S 1 82 1 829 Fatal Error in file: "TxManager_StaManager.c"; Fatal Print: TX Manager STA Manager Fatal
S 1 83 0 148 Assert in file: "TxMulticastHandler.c" in line: 148
S 1 83 0 149 Assert in file: "TxMulticastHandler.c" in line: 149
S 1 83 0 378 Assert in file: "TxMulticastHandler.c" in line: 378
S 1 83 0 379 Assert in file: "TxMulticastHandler.c" in line: 379
S 1 83 0 380 Assert in file: "TxMulticastHandler.c" in line: 380
S 1 83 0 381 Assert in file: "TxMulticastHandler.c" in line: 381
S 1 83 0 421 Assert in file: "TxMulticastHandler.c" in line: 421
S 1 83 0 422 Assert in file: "TxMulticastHandler.c" in line: 422
S 1 83 0 423 Assert in file: "TxMulticastHandler.c" in line: 423
S 1 83 0 424 Assert in file: "TxMulticastHandler.c" in line: 424
S 1 83 0 463 Assert in file: "TxMulticastHandler.c" in line: 463
S 1 83 0 464 Assert in file: "TxMulticastHandler.c" in line: 464
S 1 83 0 590 Assert in file: "TxMulticastHandler.c" in line: 590
S 1 8 5 173 Beacon CSA Manager changed from %d to %d
S 1 8 5 399 Assert in file: "Beacon_CsaManager.c" in line: 399
S 1 8 5 659 Fatal Error in file: "Beacon_CsaManager.c"; Fatal Print: Beacon CSA Manager Fatal
S 1 8 5 691 Assert in file: "Beacon_CsaManager.c" in line: 691
S 1 8 5 722 Assert in file: "Beacon_CsaManager.c" in line: 722
S 1 7 5 273 Assert in file: "HwLogger.c" in line: 273
S 1 7 5 355 Assert in file: "HwLogger.c" in line: 355
S 1 7 5 356 Assert in file: "HwLogger.c" in line: 356
S 1 7 5 387 Assert in file: "HwLogger.c" in line: 387
S 1 7 5 570 Assert in file: "HwLogger.c" in line: 570
S 1 7 5 586 Assert in file: "HwLogger.c" in line: 586
S 1 7 5 806 Assert in file: "HwLogger.c" in line: 806
S 1 7 5 863 Assert in file: "HwLogger.c" in line: 863
S 1 7 5 2238 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableUnknown
S 1 7 5 2269 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableMuLockerLogs
S 1 7 5 2274 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisablePacExtraLogs
S 1 7 5 2279 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableMuBfLogs
S 1 7 5 2284 Fatal Error in file: "HwLogger.c"; Fatal Print: hwLoggerEnableDisableMuBitmapSelectLogs
S 1 29 20 752 Assert in file: "RficDriver.c" in line: 752
S 1 29 20 799 Assert in file: "RficDriver.c" in line: 799
S 1 29 20 975 Assert in file: "RficDriver.c" in line: 975
S 1 29 20 1071 Assert in file: "RficDriver.c" in line: 1071
S 1 29 20 1131 Assert in file: "RficDriver.c" in line: 1131
S 1 29 20 1380 Assert in file: "RficDriver.c" in line: 1380
S 1 29 20 1395 Assert in file: "RficDriver.c" in line: 1395
S 1 29 20 1462 Assert in file: "RficDriver.c" in line: 1462
S 1 29 20 1560 Assert in file: "RficDriver.c" in line: 1560
S 1 29 20 1605 Assert in file: "RficDriver.c" in line: 1605
S 1 29 20 1624 RficDriver_SetFrequency freq = %d, bw = %d
S 1 29 20 1989 Assert in file: "RficDriver.c" in line: 1989
S 1 29 20 2050 Assert in file: "RficDriver.c" in line: 2050
S 1 29 20 2123 Assert in file: "RficDriver.c" in line: 2123
S 1 29 20 2167 Assert in file: "RficDriver.c" in line: 2167
S 1 29 20 2273 Assert in file: "RficDriver.c" in line: 2273
S 1 29 20 2287 Assert in file: "RficDriver.c" in line: 2287
S 1 29 20 2366 Assert in file: "RficDriver.c" in line: 2366
S 1 29 20 2401 Assert in file: "RficDriver.c" in line: 2401
S 1 29 23 690 sendChannelParams. Call Requester: %d 
S 1 29 23 705 hdkChannelNotificationCb
S 1 29 23 761 Assert in file: "HdkTask.c" in line: 761
S 1 29 23 782 Assert in file: "HdkTask.c" in line: 782
S 1 29 23 899 radioOn1:%d (2)
S 1 29 23 927 Fatal Error in file: "HdkTask.c"; Fatal Print:  In case we're running on FPGA,  we should't get here 
S 1 29 23 934 HDK_startUserDemandProcess. temp1 %d temp2 %d temp3 %d
S 1 29 23 1152 limitFromHost %d, limitFromEfuse %d
S 1 29 23 1170 Assert in file: "HdkTask.c" in line: 1170
S 1 29 23 1233 HDK event: HDK_EVENT_ADD_FIRST_VAP. current state: %d
S 1 29 23 1242 HDK event: HDK_EVENT_REMOVE_LAST_VAP. current state: %d
S 1 29 23 1259 HDK event: HDK_EVENT_ENABLE_RF. current state: %d
S 1 29 23 1266 HDK event: HDK_EVENT_DISABLE_RF. current state: %d
S 1 29 23 1277 HDK event: HDK_EVENT_CALIBRATE. current state: %d
S 1 29 23 1288 HDK event: HDK_EVENT_SET_CHANNEL. current state: %d
S 1 29 23 1297 HDK event: HDK_EVENT_ONLINE_TIMER_EXPIRED. current state: %d
S 1 29 23 1310 HDK event: HDK_EVENT_SET_ANTENNAS. current state: %d
S 1 29 23 1319 HDK event: HDK_EVENT_USER_DEMAND. current state: %d
S 1 29 23 1330 Set Channel event: SET_CHANNEL_EVENT_SET_FREQUENCY. current state: %d
S 1 29 23 1339 Set Channel event: SET_CHANNEL_EVENT_FREQUENCY_SET. current state: %d
S 1 29 23 1348 Set Channel event: SET_CHANNEL_EVENT_CAL_RESULTS_LOADED. current state: %d
S 1 29 23 1357 Set Channel event: SET_CHANNEL_EVENT_OFFLINE_CAL_DONE. current state: %d
S 1 29 23 1366 Set Channel event: SET_CHANNEL_EVENT_CAL_RESULTS_STORED. current state: %d
S 1 29 23 1375 Set Channel event: SET_CHANNEL_EVENT_CHANNEL_NOTIFICATION_DONE. current state: %d
S 1 29 23 1384 Set Channel event: SET_CHANNEL_EVENT_REMOVE_LAST_VAP. current state: %d
S 1 29 23 1395 HDK Process event: HDK_PROCESS_EVENT_SCHEDULE_PROCESS_REQ. current state: %d proc: %d
S 1 29 23 1404 HDK Process event: HDK_PROCESS_EVENT_PROCESS_SCHEDULED. current state: %d proc: %d
S 1 29 23 1413 HDK Process event: HDK_PROCESS_EVENT_PROCESS_FINISHED. current state: %d proc: %d
S 1 29 23 1422 HDK Process event: HDK_PROCESS_EVENT_EXECUTION_COMPLETED. current state: %d proc: %d
S 1 29 23 1516 Assert in file: "HdkTask.c" in line: 1516
S 1 29 23 1630 FREEEEEE MSG............
S 1 29 23 1718 Assert in file: "HdkTask.c" in line: 1718
S 1 29 23 1784 Assert in file: "HdkTask.c" in line: 1784
S 1 29 23 1876 Assert in file: "HdkTask.c" in line: 1876
S 1 29 23 1886 Assert in file: "HdkTask.c" in line: 1886
S 1 29 23 1896 setHdkMainSmState. state: %d
S 1 29 23 1908 setSetChannelSmState. state: %d
S 1 29 23 1922 setHdkProcessSmState. state: %d
S 1 29 23 1934 setHdkProcessId. processId: %d
S 1 29 23 1947 setFreqJumpSmState. state: %d
S 1 29 23 2156 RADIO_OFF FindState
S 1 29 23 2163 RADIO_ON FindState
S 1 29 23 2170 RADIO_ON_AND_1_ON_1 FindState
S 1 29 23 2177 1_ON_1 FindState
S 1 29 23 2184 OUT_OF_1_ON_1 FindState
S 1 29 23 2191 INCREASE_NUM_OF_ANTS FindState
S 1 29 23 2198 DECREASE_NUM_OF_ANTS FindState
S 1 29 23 2254 RADIO_ON_INIT
S 1 29 23 2261 RADIO_ON
S 1 29 23 2267 RADIO_OFF
S 1 29 23 2273 RADIO_ON_AND_1_ON_1
S 1 29 23 2279 1_ON_1
S 1 29 23 2285 OUT_OF_1_ON_1
S 1 29 23 2701 Assert in file: "HdkTask.c" in line: 2701
S 1 29 23 2782 Assert in file: "HdkTask.c" in line: 2782
S 1 29 23 2850 Assert in file: "HdkTask.c" in line: 2850
S 1 29 23 2854 Assert in file: "HdkTask.c" in line: 2854
S 1 29 23 3010 BITMAP FJ_CHANNEL_STATE m_curOfflineProcBitmap = %d
S 1 29 23 3111 Freq Jump event 2 + 3: FREQ_JUMP_EVENT_NEXT_BW. current state: %d
S 1 29 23 3118 Freq Jump event 4 done: FREQ_JUMP_EVENT_CAL_DONE. current state: %d
S 1 29 23 3128 Assert in file: "HdkTask.c" in line: 3128
S 1 29 23 3223 SWITCH TYPE REAL FJ  %d ++++++++ 
S 1 29 23 3246 +++++FREQ JUMP HNDLR++++++++	
S 1 29 23 3263 INTO NextBW %d & Restore RestoreOriginParms 
S 1 29 23 3279 NextBW %d NOT the LAST. fill params 
S 1 29 23 3289 LOOPPPPPPPP ======= no send param
S 1 29 23 3323 Assert in file: "HdkTask.c" in line: 3323
S 1 2 1 204 Assert in file: "AgerEmulator.c" in line: 204
S 1 2 1 244 Assert in file: "AgerEmulator.c" in line: 244
S 1 2 1 280 Assert in file: "AgerEmulator.c" in line: 280
S 1 2 1 314 Assert in file: "AgerEmulator.c" in line: 314
S 1 2 1 316 Assert in file: "AgerEmulator.c" in line: 316
S 1 2 1 993 agerEmulatorSendConfirmToStationManager, Client %d, stationIndex %d
S 1 2 1 1467 agerEmulatorProcessQueue BAR TtlCount = %d , , retransmission = %d
S 1 2 1 1524 agerEmulatorProcessQueue MANAGEMENT  TtlCount = %d 
S 1 2 1 1559 agerEmulatorProcessQueue RETRANSMIT PDs 
S 1 2 1 1580 agerEmulatorProcessQueue RETRANSMIT NOT DISCARD locationInArray = %d, locationInBitmap = %d, locationInWord = %d 
S 1 2 1 1596 agerEmulatorProcessQueue RETRANSMIT PDs current = %x, amsdu tail = %x , ttlCount = %d , numberOfPdsInAmsdu %d 
S 1 2 1 1611 agerEmulatorProcessQueue RETRANSMIT DISCARD umacListHead = %x, umacListTail = %x 
S 1 2 1 1651 agerEmulatorProcessQueue RETRANSMIT PDs current = %x, amsdu tail = %x , ttlCount = %d , numberOfPdsInAmsdu %d 
S 1 2 1 1666 agerEmulatorProcessQueue RETRANSMIT DISCARD umacListHead = %x, umacListTail = %x 
S 1 2 1 1704 agerEmulatorProcessQueue NOT RETRANSMIT PDs TtlCount = %d
S 1 2 1 1724 agerEmulatorProcessQueue NOT RETRANSMIT DISCARD liberatorListHead = %x, liberatorListTail = %x
S 1 2 1 1748 agerEmulatorProcessQueue pHeadDesc = %x , pTailDesc = %x , numberOfDiscardedPds = %d 
S 1 2 1 1785 agerEmulatorProcessQueue AGER_EMULATOR_FIRST_PART_OF_BITMAP pdIndex = %d , currentPacketDescriptor = %x , amsduTail = %x , notDiscardedListHead = %x, notDiscardedListTail = %x
S 1 2 1 1813 agerEmulatorProcessQueue AGER_EMULATOR_FIRST_PART_OF_BITMAP pdIndex = %d , currentPacketDescriptor = %x , amsduTail = %x , notDiscardedListHead = %x, notDiscardedListTail = %x
S 1 2 1 1822 agerEmulatorProcessQueue NOT DISCARDED LIST notDiscardedListHead = %x, notDiscardedListTail = %x
S 1 2 1 1833 agerEmulatorProcessQueue LIBERATOR LIST liberatorListHead = %x, liberatorListTail = %x
S 1 2 1 1842 agerEmulatorProcessQueue UMAC LIST umacListHead = %x, umacListTail = %x
S 1 6 0 183 Assert in file: "BaAnalyzer.c" in line: 183
S 1 6 0 262 Assert in file: "BaAnalyzer.c" in line: 262
S 1 6 0 263 Assert in file: "BaAnalyzer.c" in line: 263
S 1 6 0 274 Fatal Error in file: "BaAnalyzer.c"; Fatal Print: baAnalyzerIllegalStdStatus
S 1 6 0 341 Assert in file: "BaAnalyzer.c" in line: 341
S 1 6 0 746 Assert in file: "BaAnalyzer.c" in line: 746
S 1 6 0 920 Assert in file: "BaAnalyzer.c" in line: 920
S 1 6 0 931 Assert in file: "BaAnalyzer.c" in line: 931
S 1 6 0 948 Assert in file: "BaAnalyzer.c" in line: 948
S 1 6 0 965 Assert in file: "BaAnalyzer.c" in line: 965
S 1 6 0 971 Assert in file: "BaAnalyzer.c" in line: 971
S 1 10 0 228 BssManager_StartActivateProcess
S 1 10 0 230 Assert in file: "BSSmanager.c" in line: 230
S 1 10 0 263 Assert in file: "BSSmanager.c" in line: 263
S 1 10 0 390 Assert in file: "BSSmanager.c" in line: 390
S 1 10 0 418 Assert in file: "BSSmanager.c" in line: 418
S 1 10 1 546 BSS Manager STA Manager, Station %d changed from %d to %d
S 1 10 1 583 Assert in file: "BssManager_StaManager.c" in line: 583
S 1 10 1 585 Assert in file: "BssManager_StaManager.c" in line: 585
S 1 10 1 587 Assert in file: "BssManager_StaManager.c" in line: 587
S 1 10 1 588 BSS MNG, STA MNG, Dispatch Reg %d, SID %d, num %d
S 1 10 1 603 BSS MNG, STA MNG, Dispatch Client %d, MsgId %d, TaskId %d
S 1 10 1 641 BSS MNG, STA MNG, Check Dispatcher, SID %d, state %d
S 1 10 1 644 Assert in file: "BssManager_StaManager.c" in line: 644
S 1 10 1 647 Assert in file: "BssManager_StaManager.c" in line: 647
S 1 10 1 650 Assert in file: "BssManager_StaManager.c" in line: 650
S 1 10 1 653 Assert in file: "BssManager_StaManager.c" in line: 653
S 1 10 1 723 BSS MNG, STA MNG, STA Open Done, SID %d
S 1 10 1 765 BSS MNG, STA MNG, Set Filter Done, SID %d
S 1 10 1 807 BSS MNG, STA MNG, Stop Traffic Done, SID %d
S 1 10 1 850 BSS MNG, STA MNG, STA Close Done, SID %d
S 1 10 1 884 BSS MNG, STA MNG, Check Confirm, SID %d, pending %x
S 1 10 1 894 Assert in file: "BssManager_StaManager.c" in line: 894
S 1 10 1 975 Fatal Error in file: "BssManager_StaManager.c"; Fatal Print: BSS Manager STA Manager Fatal
S 1 10 1 1014 Assert in file: "BssManager_StaManager.c" in line: 1014
S 1 10 1 1018 BSS MNG, STA MNG, Reg Confirm, SID %d, Client %d, Pending Bitmap %x
S 1 10 1 1053 Assert in file: "BssManager_StaManager.c" in line: 1053
S 1 10 1 1056 Assert in file: "BssManager_StaManager.c" in line: 1056
S 1 10 1 1064 BSS MNG, STA MNG, ADD STA, SID %d
S 1 10 1 1101 Assert in file: "BssManager_StaManager.c" in line: 1101
S 1 10 1 1105 BSS MNG, STA MNG, Set Filter, SID %d
S 1 10 1 1142 Assert in file: "BssManager_StaManager.c" in line: 1142
S 1 10 1 1146 BSS MNG, STA MNG, Stop Traffic, SID %d
S 1 10 1 1183 Assert in file: "BssManager_StaManager.c" in line: 1183
S 1 10 1 1187 BSS MNG, STA MNG, Close STA, SID %d
S 1 10 2 272 BssManager_VapManager_SetState, vapId:%d, vapManagerNewState:%d
S 1 10 2 300 Assert in file: "BSSmanager_VapManager.c" in line: 300
S 1 10 2 301 BssManager_VapManager_AddVap of vapId:%d
S 1 10 2 336 BssManager_VapManager_StartAddVaptProcess of vapId:%d
S 1 10 2 381 Assert in file: "BSSmanager_VapManager.c" in line: 381
S 1 10 2 385 Assert in file: "BSSmanager_VapManager.c" in line: 385
S 1 10 2 422 Assert in file: "BSSmanager_VapManager.c" in line: 422
S 1 10 2 461 BssManager_VapManager_StartSetBssProcess of vapId:%d
S 1 10 2 469 Assert in file: "BSSmanager_VapManager.c" in line: 469
S 1 10 2 515 Assert in file: "BSSmanager_VapManager.c" in line: 515
S 1 10 2 528 Assert in file: "BSSmanager_VapManager.c" in line: 528
S 1 10 2 596 BssManager_VapManager_StartSetWmmParamsProcess of vapId:%d
S 1 10 2 606 Assert in file: "BSSmanager_VapManager.c" in line: 606
S 1 10 2 641 Assert in file: "BSSmanager_VapManager.c" in line: 641
S 1 10 2 644 BssManager_VapManager_FinalizeSetWmmParamsProcess of vapId:%d
S 1 10 2 728 BssManager_VapManager_StartRemoveVapProcess, vapId:%d
S 1 10 2 768 Assert in file: "BSSmanager_VapManager.c" in line: 768
S 1 10 2 771 BssManager_VapManager_FinalizeRemoveVapProcess of vapId:%d
S 1 10 2 774 Assert in file: "BSSmanager_VapManager.c" in line: 774
S 1 10 2 811 Assert in file: "BSSmanager_VapManager.c" in line: 811
S 1 10 2 854 Assert in file: "BSSmanager_VapManager.c" in line: 854
S 1 10 2 855 Assert in file: "BSSmanager_VapManager.c" in line: 855
S 1 10 2 892 BssManager_VapManager_EventHandlerConfirm, got cfm from taskID:%d
S 1 10 2 893 Assert in file: "BSSmanager_VapManager.c" in line: 893
S 1 10 2 894 Assert in file: "BSSmanager_VapManager.c" in line: 894
S 1 10 2 1146 Assert in file: "BSSmanager_VapManager.c" in line: 1146
S 1 10 2 1213 Assert in file: "BSSmanager_VapManager.c" in line: 1213
S 1 10 2 1219 Assert in file: "BSSmanager_VapManager.c" in line: 1219
S 1 10 2 1225 Assert in file: "BSSmanager_VapManager.c" in line: 1225
S 1 10 2 1239 Assert in file: "BSSmanager_VapManager.c" in line: 1239
S 1 10 2 1245 Assert in file: "BSSmanager_VapManager.c" in line: 1245
S 1 10 2 1258 Assert in file: "BSSmanager_VapManager.c" in line: 1258
S 1 10 2 1264 Assert in file: "BSSmanager_VapManager.c" in line: 1264
S 1 10 2 1270 Assert in file: "BSSmanager_VapManager.c" in line: 1270
S 1 10 2 1272 Assert in file: "BSSmanager_VapManager.c" in line: 1272
S 1 10 2 1277 Assert in file: "BSSmanager_VapManager.c" in line: 1277
S 1 10 2 1283 Assert in file: "BSSmanager_VapManager.c" in line: 1283
S 1 10 2 1288 Assert in file: "BSSmanager_VapManager.c" in line: 1288
S 1 17 2 143 Assert in file: "StatisticsPhyHandler.c" in line: 143
S 1 17 2 157 [PhyStatistics_MetricsFifoNotEmpty], rdType = %d
S 1 17 2 174 [PhyStatistics_MetricsFifoNotEmpty], stationId = %d, isAmpdu = %d, packetLength = %d
S 1 17 2 306 [PhyStatistics_GetPhyStatusReq]
S 1 17 2 320 Assert in file: "StatisticsPhyHandler.c" in line: 320
S 1 17 2 521 [PhyStatistics_ChannelSwitchDone]
S 1 17 2 689 Assert in file: "StatisticsPhyHandler.c" in line: 689
S 1 7 3 186 Assert in file: "HwErrors.c" in line: 186
S 1 7 3 203 hwErrorsRxcRxBufferOverflow rxBufferOverflowDroppedMpdus = %d
S 1 7 3 255 Assert in file: "HwErrors.c" in line: 255
S 1 7 3 272 Assert in file: "HwErrors.c" in line: 272
S 1 7 3 286 Assert in file: "HwErrors.c" in line: 286
S 1 7 3 352 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsRxEof
S 1 7 3 376 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsRxAggr
S 1 7 3 408 Assert in file: "HwErrors.c" in line: 408
S 1 7 3 471 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsTxSelector
S 1 7 3 505 Assert in file: "HwErrors.c" in line: 505
S 1 7 3 528 Assert in file: "HwErrors.c" in line: 528
S 1 7 3 543 Assert in file: "HwErrors.c" in line: 543
S 1 7 3 557 Assert in file: "HwErrors.c" in line: 557
S 1 7 3 571 Assert in file: "HwErrors.c" in line: 571
S 1 7 3 584 Assert in file: "HwErrors.c" in line: 584
S 1 7 3 598 Assert in file: "HwErrors.c" in line: 598
S 1 7 3 617 Fatal Error in file: "HwErrors.c"; Fatal Print: hwErrorsDelineatorFifoOverflow
S 1 7 3 700 Assert in file: "HwErrors.c" in line: 700
S 1 7 3 704 isr_HwErrors errorIndex %d num of errors %d
S 1 42 3 311 CyclicPrefixSetNextProbingPoint, tcrCpTable[%d] = %d
S 1 42 3 412 Assert in file: "CyclicPrefix.c" in line: 412
S 1 42 3 462 CyclicPrefixProcessFeedback,workingPointPer = %d,slowProbingPointPer = %d, effectiveTpWp = %d,  effectiveTpProbing = %d
S 1 42 3 474 CyclicPrefixProcessFeedback, Chane WP, tcrCpTable[%d] = =%d
S 1 42 3 510 Assert in file: "CyclicPrefix.c" in line: 510
S 1 42 3 514 CyclicPrefix - SET RATE + 1
S 1 42 3 591 Assert in file: "CyclicPrefix.c" in line: 591
S 1 62 0 946 Assert in file: "RxClassifier.c" in line: 946
S 1 62 0 1004 [RxClassifier_FillRtd], staIndex = %d
S 1 62 0 1024 [RxClassifier_FillRtd], rssiTypeFlag = %d, isMulticastOrBroadcast = %d, isStaIndexValid = %d
S 1 62 0 1038 Assert in file: "RxClassifier.c" in line: 1038
S 1 62 0 1415 RxClassifier_RxFilters drop sn %d
S 1 62 0 1789 Assert in file: "RxClassifier.c" in line: 1789
S 1 62 0 1813 Assert in file: "RxClassifier.c" in line: 1813
S 1 62 0 1837 Assert in file: "RxClassifier.c" in line: 1837
S 1 62 0 1864 Assert in file: "RxClassifier.c" in line: 1864
S 1 62 0 1892 Assert in file: "RxClassifier.c" in line: 1892
S 1 62 0 1921 Assert in file: "RxClassifier.c" in line: 1921
S 1 62 0 1950 Assert in file: "RxClassifier.c" in line: 1950
S 1 62 0 1984 Assert in file: "RxClassifier.c" in line: 1984
S 1 62 0 2047 Assert in file: "RxClassifier.c" in line: 2047
S 1 62 0 2137 Assert in file: "RxClassifier.c" in line: 2137
S 1 62 0 2250 Assert in file: "RxClassifier.c" in line: 2250
S 1 62 0 2278 Assert in file: "RxClassifier.c" in line: 2278
S 1 62 0 2404 -------- Rx Classifier configured for Sniffer --------
S 1 62 0 2498 [RxClassifier_ConfigureNormalMode] - WAVE400------------------end]
S 1 62 0 2525 [RxClassifier_ConfigureRssiMode]-------- Rx Classifier configured for RSSI -WAVE400------- RxClassifierDb.rssiTypeFlag = %d
S 1 66 0 374 Assert in file: "RxManager.c" in line: 374
S 1 66 0 379 Assert in file: "RxManager.c" in line: 379
S 1 66 0 380 Assert in file: "RxManager.c" in line: 380
S 1 66 0 555 Fatal Error in file: "RxManager.c"; Fatal Print: RX Manager Timer Unknown Type
S 1 66 0 678 Fatal Error in file: "RxManager.c"; Fatal Print: RX Manager Classifier Resource Timeout
S 1 66 0 712 [rxManagerClassifierConfigureNormalMode]--------------------end]
S 1 66 0 748 [rxManagerClassifierConfigureRssiMode]----------------------end]
S 1 66 0 797 [rxManagerConfigureNormalMode]------------------------------end]
S 1 66 0 839 [rxManagerConfigureRssiMode]--------------------------------end]
S 1 66 0 886 Assert in file: "RxManager.c" in line: 886
S 1 66 0 904 Assert in file: "RxManager.c" in line: 904
S 1 66 0 928 Assert in file: "RxManager.c" in line: 928
S 1 66 0 929 Assert in file: "RxManager.c" in line: 929
S 1 66 0 1228 Assert in file: "RxManager.c" in line: 1228
S 1 66 0 1332 rxManagerPsSettingsFifoNotEmpty %x
S 1 66 0 1345 Assert in file: "RxManager.c" in line: 1345
S 1 66 0 1350 rxManagerPsSettingsFifoNotEmpty  Station Changed Ps Mode Set Ps Status %x Clear Ps Status %x
S 1 66 0 1478 [CLIENT_MODE_MCAST] rxManagerDriverListHandler
S 1 66 0 1522 [CLIENT_MODE_MCAST] rxManagerDataTemporaryForwardToFwListHandler
S 1 66 0 1532 [CLIENT_MODE_MCAST] rxManagerErrorRdsListHandler. ErrorIndex = %d
S 1 66 0 1559 Assert in file: "RxManager.c" in line: 1559
S 1 66 0 1565 Assert in file: "RxManager.c" in line: 1565
S 1 66 0 1572 Assert in file: "RxManager.c" in line: 1572
S 1 66 0 1662 [ClientModeMcastFilterLocateRd] URID. current index = %d
S 1 66 0 1667 [CLIENT_MODE_MCAST] ClientModeMcastFilterLocateRd [1] clientModeMcastFilterRing[current] = 0x%x 0x%x 0x%x 0x%x
S 1 66 0 1668 [CLIENT_MODE_MCAST] ClientModeMcastFilterLocateRd [2] own = %d valid = %d pRing->sequenceNumber = %d rd->sequenceNumber = %d pRing = 0x%x
S 1 66 0 1669 [CLIENT_MODE_MCAST] ClientModeMcastFilterLocateRd [3] pRing->rdPointer = 0x%x rd offset = 0x%x rd = 0x%x
S 1 66 0 1676 Assert in file: "RxManager.c" in line: 1676
S 1 66 0 1679 [CLIENT_MODE_MCAST] ClientModeMcastFilterLocateRd [5] elementCounter = %d
S 1 66 0 1680 [CLIENT_MODE_MCAST] ClientModeMcastFilterLocateRd [5] index = %d
S 1 66 0 1693 Assert in file: "RxManager.c" in line: 1693
S 1 66 0 1696 [CLIENT_MODE_MCAST] ClientModeMcastFilterLocateRd [6] Own = %d Valid = %d elementCounter = 0x%x *index = %d
S 1 66 0 1707 [ClientModeMcastFilterLocateRd] URID. new index = %d
S 1 66 0 1747 rxManagerErrorRdsListHandler
S 1 66 0 1752 [CLIENT_MODE_MCAST] rxManagerErrorRdsListHandler
S 1 66 0 1815 [CLIENT_MODE_MCAST] rxManagerErrorRdsListHandler. ErrorIndex = %d
S 1 66 0 1881 [CLIENT_MODE_MCAST] rxManagerReleaseFwdRdListHandler
S 1 66 0 1934 Fatal Error in file: "RxManager.c"; Fatal Print: RX Manager RD Handler
S 1 66 0 1963 [CLIENT_MODE_MCAST] rxManagerUnsupportedRdHandler. >>>>>> Why does RX Manager think this is MCAST
S 1 66 0 2002 [ClientModeMcastFilterIsRdLocalyOriginatedMcastPacket] rxManagerErrorRdsListHandler. FilterIndex = %d
S 1 66 0 2016 [CLIENT_MODE_MCAST] ClientModeMcastFilterIsRdLocalyOriginatedMcastPacket [2] mcastPacketSourceMacAddress = 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 
S 1 66 0 2017 [CLIENT_MODE_MCAST] ClientModeMcastFilterIsRdLocalyOriginatedMcastPacket [2] ourMacAddress = 0x%x 0x%x 0x%x 0x%x 0x%x 0x%x 
S 1 66 0 2070 Assert in file: "RxManager.c" in line: 2070
S 1 66 0 2073 [CLIENT_MODE_MCAST] rxManagerMulticastDataRdHandler
S 1 66 0 2083 Assert in file: "RxManager.c" in line: 2083
S 1 66 0 2098 [CLIENT_MODE_MCAST] rxManagerMulticastDataRdHandler dropping localy origniated packet SN = %d
S 1 66 0 2112 [rxManagerMulticastDataRdHandler] URID. you got here due to replay detection fail
S 1 66 0 2124 [CLIENT_MODE_MCAST] rxManagerMulticastDataRdHandler WDS is active and it is not forwarding mcast packets - free the element from the ring SN = %d
S 1 66 0 2164 [CLIENT_MODE_MCAST] rxManagerControlRdHandler. >>>>>> Why does RX Manager think this is MCAST
S 1 66 0 2170 Assert in file: "RxManager.c" in line: 2170
S 1 66 0 2229 [CLIENT_MODE_MCAST] rxManagerFwManagementRdHandler. >>>>>> Why does RX Manager think this is MCAST
S 1 66 0 2234 Assert in file: "RxManager.c" in line: 2234
S 1 66 0 2375 Assert in file: "RxManager.c" in line: 2375
S 1 66 0 2378 [CLIENT_MODE_MCAST] rxManagerFwUnassociatedManagementRdHandler. >>>>>> Why does RX Manager think this is MCAST
S 1 66 0 2578 rxManagerMulticastRekeyTimeout, vap ID - %d, prev key ID - %d
S 1 66 0 2628 rxManagerCheckMulticastRekey, vap ID - %d, last Rx key ID - %d, key Id - %d
S 1 66 0 3385 Assert in file: "RxManager.c" in line: 3385
S 1 66 0 3462 Assert in file: "RxManager.c" in line: 3462
S 1 66 0 3514 [rxManagerDoReplayDetectionStaMode] URID. FAIL!!!! last PN is : %d, current PN is : %d
S 1 66 0 3750 RX Manager, Send Confirmation, Client %d, SID %d
S 1 66 0 3790 Assert in file: "RxManager.c" in line: 3790
S 1 70 0 334 Assert in file: "LowerSender.c" in line: 334
S 1 70 0 449 Assert in file: "LowerSender.c" in line: 449
S 1 70 0 480 Assert in file: "LowerSender.c" in line: 480
S 1 70 0 487 Assert in file: "LowerSender.c" in line: 487
S 1 70 0 497 Assert in file: "LowerSender.c" in line: 497
S 1 70 0 593 Assert in file: "LowerSender.c" in line: 593
S 1 70 0 642 LowerSenderDutTxEndHandler, DUT_TX_STATE_STOPPING, toStop == TRUE
S 1 70 0 648 Assert in file: "LowerSender.c" in line: 648
S 1 70 0 658 Assert in file: "LowerSender.c" in line: 658
S 1 70 0 665 LowerSenderDutTxAbortHandler
S 1 70 0 869 Assert in file: "LowerSender.c" in line: 869
S 1 70 0 1007 Assert in file: "LowerSender.c" in line: 1007
S 1 70 0 1121 LowerSender_DutConfig
S 1 70 0 1139 LowerSender_UpdateStdWithDutParams, alloctedStd_p:0x%x, current std:0x%x
S 1 82 0 342 Assert in file: "TxManager.c" in line: 342
S 1 82 0 350 Assert in file: "TxManager.c" in line: 350
S 1 82 0 351 Assert in file: "TxManager.c" in line: 351
S 1 82 0 352 Assert in file: "TxManager.c" in line: 352
S 1 82 0 407 Assert in file: "TxManager.c" in line: 407
S 1 82 0 469 Assert in file: "TxManager.c" in line: 469
S 1 82 0 470 Assert in file: "TxManager.c" in line: 470
S 1 82 0 551 Assert in file: "TxManager.c" in line: 551
S 1 82 0 558 Assert in file: "TxManager.c" in line: 558
S 1 82 0 559 Assert in file: "TxManager.c" in line: 559
S 1 82 0 714 Assert in file: "TxManager.c" in line: 714
S 1 82 0 787 txManagerPackestFromFwListHandler packet descriptor %x
S 1 82 0 1107 Fatal Error in file: "TxManager.c"; Fatal Print: txManagerNdpaHandler
S 1 82 0 1230 Assert in file: "TxManager.c" in line: 1230
S 1 82 0 1424 Assert in file: "TxManager.c" in line: 1424
S 1 82 0 1454 Fatal Error in file: "TxManager.c"; Fatal Print: txManagerAssert
S 1 82 0 1481 Fatal Error in file: "TxManager.c"; Fatal Print: txManagerListFatal
S 1 82 0 1586 -------- NTD configured for Sniffer --------
S 1 82 0 1842 Assert in file: "TxManager.c" in line: 1842
S 1 82 0 1965 Assert in file: "TxManager.c" in line: 1965
S 1 61 1 105 Assert in file: "TxPacketsClassifier.c" in line: 105
S 1 61 1 249 num_Pds =%d agerCount=%d IsrTime=%d pdCount=%d
S 1 61 1 419 Assert in file: "TxPacketsClassifier.c" in line: 419
S 1 61 1 420 Assert in file: "TxPacketsClassifier.c" in line: 420
S 1 85 0 894 [UMI_ADD_VAP_REQ LA]
S 1 85 0 1092 UMI_SET_INTERFERER_DETECTION_PARAMS_REQ: time %u
S 1 85 0 1222 [vUM_PHY_RX_STATUS_REQ]
S 1 85 0 1240 [vMC_PHY_RX_STATUS_CFM]
S 1 85 0 1296 [vUM_SET_CHAN_CFM]
S 1 85 0 1343 Assert in file: "um_interface_task.c" in line: 1343
S 1 85 0 1408 Fatal Error in file: "um_interface_task.c"; Fatal Print: Debug Assert Requested by Host
S 1 85 0 1414 Assert in file: "um_interface_task.c" in line: 1414
S 1 85 0 1437 [vUM_SET_CHAN_REQ]
S 1 85 0 1690 Assert in file: "um_interface_task.c" in line: 1690
S 1 85 0 1713 Assert in file: "um_interface_task.c" in line: 1713
S 1 85 0 1856 Assert in file: "um_interface_task.c" in line: 1856
S 1 85 0 2002 Assert in file: "um_interface_task.c" in line: 2002
S 1 85 0 2012 Assert in file: "um_interface_task.c" in line: 2012
S 1 85 0 2432 Assert in file: "um_interface_task.c" in line: 2432
S 1 85 0 2450 [startLockAttempt 1] *** semaphore test start *** 
S 1 85 0 2469 [startLockAttempt 2] UM is trying to get the lock -> lock is busy = %d
S 1 85 0 2473 [startLockAttempt 3] Get a non used lock 
S 1 85 0 2475 [startLockAttempt 4] Got the lock 
S 1 85 0 2477 [startLockAttempt 5] Free the lock 
S 1 85 0 2479 [startLockAttempt 6] Get a non used lock 
S 1 85 0 2481 Assert in file: "um_interface_task.c" in line: 2481
S 1 85 0 2482 [startLockAttempt 7] Got the lock 
S 1 85 0 2483 [startLockAttempt 8] Free the lock
S 1 85 0 2485 [startLockAttempt 9] Free 
S 1 85 0 2487 [startLockAttempt 10] Get a busy lock 
S 1 85 0 2489 [startLockAttempt 11] Locked 
S 1 85 0 2490 [startLockAttempt 12] Free the lock 
S 1 85 0 2492 [startLockAttempt 13] Free 
S 1 85 0 2528 UMAC Rx UM_DBG_CLI_REQ from Host, action:%d, argc:%d, data1:%d, data2:%d, data3:%d
S 1 85 0 2607 [UmDbgCliReq] Unknown message type
S 1 85 0 2747 CLI req, data1=%d, data2=%d, data3=%d
S 1 85 0 2851 Assert in file: "um_interface_task.c" in line: 2851
S 1 85 0 2873 Assert in file: "um_interface_task.c" in line: 2873
S 1 85 0 2881 Assert in file: "um_interface_task.c" in line: 2881
S 1 85 0 2887 Assert in file: "um_interface_task.c" in line: 2887
S 1 85 0 2917 Assert in file: "um_interface_task.c" in line: 2917
S 1 85 0 2929 Assert in file: "um_interface_task.c" in line: 2929
S 1 85 0 2942 Assert in file: "um_interface_task.c" in line: 2942
S 1 85 0 2954 Assert in file: "um_interface_task.c" in line: 2954
S 1 85 0 2955 Assert in file: "um_interface_task.c" in line: 2955
S 1 85 0 2983 Assert in file: "um_interface_task.c" in line: 2983
S 1 85 0 2996 Assert in file: "um_interface_task.c" in line: 2996
S 1 85 0 3006 Assert in file: "um_interface_task.c" in line: 3006
S 1 85 0 3132 [vUMI_MAN_STA_ADD_REQ]
S 1 85 0 3153 [vUMI_MAN_STA_ADD_CFM]
S 1 85 0 3178 [vUMI_MAN_STA_REMOVE_REQ]
S 1 85 0 3199 [vUMI_MAN_STA_REMOVE_CFM]
S 1 85 0 3261 Assert in file: "um_interface_task.c" in line: 3261
S 1 85 0 3509 [vUMI_MAN_REQUEST_SID_REQ]
S 1 85 0 3528 [vUMI_MAN_REQUEST_SID_CFM]
S 1 85 0 3565 [vUMI_MAN_REMOVE_SID_REQ]
S 1 85 0 3756 Assert in file: "um_interface_task.c" in line: 3756
S 1 85 0 3955 Assert in file: "um_interface_task.c" in line: 3955
S 1 85 0 4247 [vUMI_MAN_REMOVE_SID_CFM]
S 1 85 0 4269 [vUMI_MAN_STOP_TRAFFIC_REQ]
S 1 85 0 4287 [vUMI_MAN_STOP_TRAFFIC_CFM]
S 1 85 0 4953 Fatal Error in file: "um_interface_task.c"; Fatal Print: UMI_GROUP_LOCK_CFM
S 1 85 0 5503 Assert in file: "um_interface_task.c" in line: 5503
S 1 85 0 5540 Assert in file: "um_interface_task.c" in line: 5540
S 1 85 0 5542 Assert in file: "um_interface_task.c" in line: 5542
S 1 29 10 448 Assert in file: "PhyDriver.c" in line: 448
S 1 29 10 499 Assert in file: "PhyDriver.c" in line: 499
S 1 29 10 508 Assert in file: "PhyDriver.c" in line: 508
S 1 29 10 607 Assert in file: "PhyDriver.c" in line: 607
S 1 29 10 647 Assert in file: "PhyDriver.c" in line: 647
S 1 29 10 654 Assert in file: "PhyDriver.c" in line: 654
S 1 29 10 794 PhyDrv_DisableBB, %u
S 1 29 10 803 PhyDrv_EnableBB, %u
S 1 29 10 1045 Assert in file: "PhyDriver.c" in line: 1045
S 1 29 10 1070 Assert in file: "PhyDriver.c" in line: 1070
S 1 29 10 1096 Assert in file: "PhyDriver.c" in line: 1096
S 1 29 10 1131 Assert in file: "PhyDriver.c" in line: 1131
S 1 29 10 1284 Assert in file: "PhyDriver.c" in line: 1284
S 1 29 10 1328 Assert in file: "PhyDriver.c" in line: 1328
S 1 29 10 1329 Assert in file: "PhyDriver.c" in line: 1329
S 1 29 10 1354 Fatal Error in file: "PhyDriver.c"; Fatal Print: WD(phy) interrupt occured
S 1 29 10 1487 Assert in file: "PhyDriver.c" in line: 1487
S 1 29 10 1522 1continuousInterfererSample   = %d
S 1 29 14 355 Assert in file: "PhyDriver.c" in line: 355
S 1 29 14 365 Fatal Error in file: "PhyDriver.c"; Fatal Print: MIPS halt done
S 1 29 14 475 PhyDrv_ReleaseSWreset
S 1 29 14 661 PhyDrv_DisableBB
S 1 29 14 670 PhyDrv_EnableBB
S 1 29 14 734 Assert in file: "PhyDriver.c" in line: 734
S 1 29 14 807 Assert in file: "PhyDriver.c" in line: 807
S 1 29 14 838 Assert in file: "PhyDriver.c" in line: 838
S 1 29 14 878 Assert in file: "PhyDriver.c" in line: 878
S 1 29 14 1023 Assert in file: "PhyDriver.c" in line: 1023
S 1 29 14 1119 Assert in file: "PhyDriver.c" in line: 1119
S 1 29 14 1120 Assert in file: "PhyDriver.c" in line: 1120
S 1 29 14 1128 Assert in file: "PhyDriver.c" in line: 1128
S 1 29 14 1129 Assert in file: "PhyDriver.c" in line: 1129
S 1 29 14 1157 Fatal Error in file: "PhyDriver.c"; Fatal Print: WD(phy) interrupt occured
S 1 29 14 1352 Assert in file: "PhyDriver.c" in line: 1352
S 1 29 14 1373 -------------------- RAW SAMPLE %d --------------------
S 1 29 14 1391 PhyDrvInterfererDetection_FlushContinuousInterfererDetectionFifo	radarDetectionSample->amp[subBandIndex] %d
S 1 29 14 1398 interfererDetectionRadarSamplesMessageParameters->pulses[index].ampSubBandBitMap = %d
S 1 29 14 1465 Assert in file: "PhyDriver.c" in line: 1465
S 1 29 14 1500 PhyDrvInterfererDetection_FlushContinuousInterfererDetectionFifo index = %d continuousInterfererSample = %d 
S 1 29 14 1684 Assert in file: "PhyDriver.c" in line: 1684
S 1 29 14 1715 Assert in file: "PhyDriver.c" in line: 1715
S 1 29 14 1744 Assert in file: "PhyDriver.c" in line: 1744
S 1 29 14 1781 PhyDrv_SetCompressedFourierPhases, Enter function
S 1 29 14 1789 PhyDrv_SetCompressedFourierPhases, tableSize = %d
S 1 29 14 1798 PhyDrv_SetCompressedFourierPhases, address = %X
S 1 42 5 718 Assert in file: "LinkAdaptation.c" in line: 718
S 1 42 5 792 Assert in file: "LinkAdaptation.c" in line: 792
S 1 42 5 936 Assert in file: "LinkAdaptation.c" in line: 936
S 1 42 5 1213 Assert in file: "LinkAdaptation.c" in line: 1213
S 1 42 5 1217 Assert in file: "LinkAdaptation.c" in line: 1217
S 1 42 5 1477 Assert in file: "LinkAdaptation.c" in line: 1477
S 1 42 5 1691 Assert in file: "LinkAdaptation.c" in line: 1691
S 1 42 5 1701 Assert in file: "LinkAdaptation.c" in line: 1701
S 1 42 5 1914 linkAdaptationHandleAgingTimerEvent
S 1 42 5 1926 Assert in file: "LinkAdaptation.c" in line: 1926
S 1 42 5 1930 Assert in file: "LinkAdaptation.c" in line: 1930
S 1 42 5 2179 [linkAdaptationAddStationReq], staPHYmode = %d
S 1 42 5 2344 Assert in file: "LinkAdaptation.c" in line: 2344
S 1 42 5 2736 Assert in file: "LinkAdaptation.c" in line: 2736
S 1 42 5 2879 Assert in file: "LinkAdaptation.c" in line: 2879
S 1 42 5 3112 [setLinkAdaptationRatesMask], pLmStaDbSwinfo->supportedRates = %d
S 1 42 5 3149 [setLinkAdaptationRatesMask] pLinkAdaptationDb->laStaUspCommon.raIndexMask.raIndexMask64bit[0] = %d
S 1 42 5 3150 [setLinkAdaptationRatesMask] pLinkAdaptationDb->laStaUspCommon.raIndexMask.raIndexMask64bit[1] = %d
S 1 42 5 3399 Assert in file: "LinkAdaptation.c" in line: 3399
S 1 42 5 3448 Assert in file: "LinkAdaptation.c" in line: 3448
S 1 42 5 3580 Assert in file: "LinkAdaptation.c" in line: 3580
S 1 42 5 3757 Assert in file: "LinkAdaptation.c" in line: 3757
S 1 42 5 3868 Assert in file: "LinkAdaptation.c" in line: 3868
S 1 42 5 3873 Assert in file: "LinkAdaptation.c" in line: 3873
S 1 42 5 3887 Assert in file: "LinkAdaptation.c" in line: 3887
S 1 42 5 3989 Assert in file: "LinkAdaptation.c" in line: 3989
S 1 42 5 4010 Assert in file: "LinkAdaptation.c" in line: 4010
S 1 42 5 4027 Assert in file: "LinkAdaptation.c" in line: 4027
S 1 42 5 4155 Assert in file: "LinkAdaptation.c" in line: 4155
S 1 42 5 4187 Assert in file: "LinkAdaptation.c" in line: 4187
S 1 42 5 4217 Assert in file: "LinkAdaptation.c" in line: 4217
S 1 42 5 4519 [FAST DROP] linkAdaptationFastDropConfig enableFastDrop = %d pFastDropCfg->enableFastDrop = %d 
S 1 42 5 4804 [updateTransmissionTimeParams] rate is above threshold: %d
S 1 42 5 4810 [updateTransmissionTimeParams] rate is below threshold: %d. limit transmission time
S 1 42 5 4848 clientIsolationRateIsChanged oldPhyRate: %d newPhyRate: %d oldPhymode %d newPhyMode %d
S 1 42 5 4936 Assert in file: "LinkAdaptation.c" in line: 4936
S 1 42 5 5059 Assert in file: "LinkAdaptation.c" in line: 5059
S 1 42 5 5079 pTcrPowerModified = %d
S 1 42 5 5205 Assert in file: "LinkAdaptation.c" in line: 5205
S 1 42 5 5220 Assert in file: "LinkAdaptation.c" in line: 5220
S 1 42 5 5227 Fatal Error in file: "LinkAdaptation.c"; Fatal Print: linkAdaptationProcessCurrentBaaReport
S 1 42 5 5270 Assert in file: "LinkAdaptation.c" in line: 5270
S 1 42 5 5500 Assert in file: "LinkAdaptation.c" in line: 5500
S 1 42 5 5539 [ChangeStaToSteadyStateConfigurationParams]
S 1 42 5 5576 Assert in file: "LinkAdaptation.c" in line: 5576
S 1 42 5 5584 Fatal Error in file: "LinkAdaptation.c"; Fatal Print: updateLaDbDistributionParam
S 1 42 5 5710 Assert in file: "LinkAdaptation.c" in line: 5710
S 1 42 5 5785 Assert in file: "LinkAdaptation.c" in line: 5785
S 1 42 5 5827 Assert in file: "LinkAdaptation.c" in line: 5827
S 1 42 5 5854 Assert in file: "LinkAdaptation.c" in line: 5854
S 1 42 5 6034 Assert in file: "LinkAdaptation.c" in line: 6034
S 1 42 5 6037 Assert in file: "LinkAdaptation.c" in line: 6037
S 1 42 5 6043 Assert in file: "LinkAdaptation.c" in line: 6043
S 1 58 0 222 Assert in file: "Qos.c" in line: 222
S 1 58 0 633 [qosSingleCheckDone]
S 1 58 0 664 [qosSingleCheckDone], numberOfFreePdsNeeded = %d, currentNumberOfFreePds = %d
S 1 58 0 671 [qosSingleCheckDone], QosAgerSingleCheckConfigurationParameters.maximumPdsToDiscard = %d, QosSingleCheckParameters.currentPdLimitIndex = %d
S 1 58 0 678 [qosSingleCheckDone], QosSingleCheckParameters.currentTtl = %d
S 1 58 0 736 [qosSingleCheckDone] stop single check
S 1 58 0 996 [qosPdThresholdConfig], QoSPdThresholdDb.mode = %d, config->mode = %d, config->minPdDiff = %d , config->minPdAmount = %d 
S 1 58 0 1007 Assert in file: "Qos.c" in line: 1007
S 1 58 0 1030 [qosPdThresholdConfig], in QOS_PD_THRESHOLD_DISABLED
S 1 58 0 1248 Assert in file: "Qos.c" in line: 1248
S 1 58 0 1306 Assert in file: "Qos.c" in line: 1306
S 1 58 0 1487 Qos, Send Confirmation, Client %d, stationIndex %d
S 1 58 0 1551 Assert in file: "Qos.c" in line: 1551
S 1 58 0 1593 [DROP_DEBUG][QosSetAgerParams] hostInterfaceAcceleratorFreePdsThreshold = %d freePdsHysteresisNumber = %d pollingTimer = %d
S 1 42 4 454 estimatorsResetFastProbingFilters
S 1 42 4 819 Assert in file: "Estimators.c" in line: 819
S 1 42 4 862 Assert in file: "Estimators.c" in line: 862
S 1 42 4 871 Assert in file: "Estimators.c" in line: 871
S 1 42 4 1050 Assert in file: "Estimators.c" in line: 1050
S 1 42 4 1118 Assert in file: "Estimators.c" in line: 1118
S 1 42 4 1208 Assert in file: "Estimators.c" in line: 1208
S 1 42 4 1238 estimatorsProcessBaaReport, rate changed, new rate = %d
S 1 42 4 1386 Assert in file: "Estimators.c" in line: 1386
S 1 42 4 1675 estimatorsSlowProbingDbUpdate av per,RateIndex = %d,bandwidth = %d,filterinput = %d, filterResult = %d, alpha = %d
S 1 42 4 1725 calculatePer, resWeighted = %d, resMPduNum = %d, resLength = %d
S 1 42 4 1729 Assert in file: "Estimators.c" in line: 1729
S 1 42 4 1786 Assert in file: "Estimators.c" in line: 1786
S 1 42 4 1811 Assert in file: "Estimators.c" in line: 1811
S 1 42 4 1843 Assert in file: "Estimators.c" in line: 1843
S 1 42 4 1902 estimatorsProbingValidationCriteria,currentPacketTsf = %d, probeIsValid = %d, currentTsfMod = %d, tsfDiff = %d, validationCounter = %d
S 1 42 4 1967 estimatorsAgingCheck, staId = %d, MU group count - %d
S 1 42 4 2047 Fatal Error in file: "Estimators.c"; Fatal Print: estimatorsSetSlowProbingPointRateIndex
S 1 42 4 2117 Assert in file: "Estimators.c" in line: 2117
S 1 42 4 2162 Assert in file: "Estimators.c" in line: 2162
S 1 42 4 2208 Assert in file: "Estimators.c" in line: 2208
S 1 42 4 2261 estimatorsProcessSequencerReport, staId = %d, Station's grade is - %d, MU group count - %d
S 1 42 4 2291 Sequencer estimaror processing - goodput update, current totalgroup's avgGoodput = %d, normAvgGoodput %d, groupId %d
S 1 42 4 2338 estimatorsProcessSequencerReport recovery
S 1 42 4 2366 estimatorsProcessSequencerReport, rate changed, new rate = %d
S 1 42 4 2512 estimatorsRecheckCandidacy, staId = %d, Station's grade is - %d
S 1 42 4 2592 Assert in file: "Estimators.c" in line: 2592
S 1 42 4 2765 Assert in file: "Estimators.c" in line: 2765
S 1 42 4 2768 fastDropEstimator, windowFailedPacketBitmap = %d, numberOfFailedPacketInWindow = %d,  consFailMask = %d, numbOfFailsinWind = %d, consequtiveFailsCondition = %d, FailIndication = %d,failsInWindow = %d
S 1 42 4 2826 Assert in file: "Estimators.c" in line: 2826
S 1 42 4 2845 estimatorsFastProbingSearchMaxEffTp, AvPerFilter: filetrResult = %d, alpha = %d, Last TSF = %d
S 1 42 4 2919 Assert in file: "Estimators.c" in line: 2919
S 1 42 4 2962 Assert in file: "Estimators.c" in line: 2962
S 1 42 4 3007 Assert in file: "Estimators.c" in line: 3007
S 1 42 4 3028 Assert in file: "Estimators.c" in line: 3028
S 1 42 4 3032 Assert in file: "Estimators.c" in line: 3032
S 1 42 4 3065 linkAdaptationCalcMuCandidacyGrade - stationInPsOrManagementWithinWindowCount =%d 
S 1 42 4 3066 linkAdaptationCalcMuCandidacyGrade - lowFrameRateCounter =%d 
S 1 42 4 3067 linkAdaptationCalcMuCandidacyGrade - wpAverageGoodPut =%d 
S 1 42 16 153 linkAdaptationStateMachine: la_state %d, event %d
S 1 42 16 402 waitForNextProbeCycleStateBaTxReportEvent- waitForNextProbeCycleStateBaTxReportEvent == %d
S 1 42 16 1150 Assert in file: "LinkAdaptation_StateMachine.c" in line: 1150
S 1 42 16 1201 Probe response ignored after state aging, stationIndex = %d
S 1 42 16 1233 Assert in file: "LinkAdaptation_StateMachine.c" in line: 1233
S 1 42 16 1259 updateOverridePendingDb. override %d value %d
S 1 42 16 1279 Assert in file: "LinkAdaptation_StateMachine.c" in line: 1279
S 1 42 16 1348 executeParamOverride, staIdx: %d
S 1 42 16 1526 Fatal Error in file: "LinkAdaptation_StateMachine.c"; Fatal Print: laStateMachineProcessBaaReport
S 1 42 16 1532 laStateMachineProcessBaaReport, event %d
S 1 42 16 1537 laStateMachineProcessBaaReport, event %d
S 1 42 16 1565 laStateMachineProcessSequencerReport, event %d
S 1 42 16 1570 laStateMachineProcessSequencerReport, event %d
T 1 7 1 304 BaaTxReport_t
T 1 9 0 227 PacManagerStart_t
T 1 15 0 191 UMI_MIB
T 1 19 0 333 dutMessageHeader_t
T 1 19 1 153 dutChipVersion_t
T 1 19 1 214 dutSetAntennaParams_t
T 1 19 1 246 LinkAdaptationFixedAntennaSelection_t
T 1 19 1 272 dutSetAntennaParams_t
T 1 19 1 375 dutTxSpacelessParams_t
T 1 19 1 486 dutIfsParams_t
T 1 19 1 538 dutRssiParams_t
T 1 19 1 595 dutTpcFeedbackparams_t
T 1 19 1 716 dutRficRxGainsParams_t
T 1 19 1 738 dutXtalParams_t
T 1 19 1 758 dutXtalParams_t
T 1 19 1 801 dutMemoryAccessParams_t
T 1 19 1 841 dutMemoryAccessParams_t
T 1 19 1 959 dutTpcFeedbackparams_t
T 1 19 1 980 dutRficTxGainsParams_t
T 1 19 2 171 dutPowerOutVecParams_t
T 1 19 2 182 dutPowerOutVecParams_t
T 1 19 2 240 RssiGainBlock_t
T 1 19 2 251 RssiCwPower_t
T 1 19 2 259 S2dParams_t
T 1 19 2 270 DutRssiOffsetGain_t
T 1 19 2 280 RssiDBPower_t
T 1 19 2 291 Clipping_trigger_t
T 1 19 2 328 dutLnaMidGain_t
T 1 19 2 406 clbrHndlrResetConf_t
T 1 19 2 424 dutStartCalibrationParams_t
T 1 19 2 425 dutDB_t
T 1 19 2 655 dutSetRate_t
T 1 19 2 675 LaFixedRateParams_t
T 1 19 2 704 dutGetFwInfo_t
T 1 19 3 261 dutTxParams_t
T 1 19 3 278 trafficParams_t
T 1 19 3 455 FM_PAYLOAD_MANAGEMENT_ACTION_PUBLIC_FRAME
T 1 19 3 471 manPacketDescriptor_t
T 1 30 2 1920 SetChannelParams_t
T 1 33 7 415 ENET_RXF
T 1 42 0 152 AntennaSelectionDatabase_t
T 1 42 0 166 AntennaSelectionDatabase_t
T 1 42 0 200 AntennaSelectionDatabase_t
T 1 42 0 489 AntennaSelectionDatabase_t
T 1 42 18 287 LaTcrModificationStruct_t
T 1 42 20 180 DynamicTxopDB_t
T 1 42 19 413 RateMask_t
T 1 42 19 795 RateMask_t
T 1 42 19 796 RateMask_t
T 1 42 19 820 RateMask_t
T 1 42 19 839 RateMask_t
T 1 42 19 840 RateMask_t
T 1 44 2 186 UmiLoggerMsgSetFilter_t
T 1 44 2 263 UmiLoggerMsgSetMode_t
T 1 44 2 327 UmiLoggerMsgFlushBuffer_t
T 1 28 18 727 ClbrMngr_TemperatureDB_t
T 1 28 18 728 ClbrMngr_OnlineCalibDB_t
T 1 28 18 791 ClbrMngr_CalibrateDB_t
T 1 28 18 836 ClbrMngr_CalibrateDB_t
T 1 42 6 341 LaTcrModificationStruct_t
T 1 32 1 354 bssHostDescriptor_t
T 1 32 1 449 bssHostDescriptor_t
T 1 32 1 517 bssHostDescriptor_t
T 1 32 1 604 bssHostDescriptor_t
T 1 50 0 550 PtaDb_t
T 1 50 0 551 PtaRepetitionParams_t
T 1 78 0 420 GroupCombinationTableDebug_t
T 1 78 0 1147 TrainingVectorDebugStruct_t
T 1 78 0 1212 TrainingManagerStaBitmap_t
T 1 78 0 1221 TrainingManagerStaBitmap_t
T 1 78 0 1360 GroupManagerStationBitmap_t
T 1 78 0 1718 MuEffectiveRateDbRamEntry_u
T 1 78 0 1767 MuEffectiveRateDbRamEntry_u
T 1 78 0 1831 MuEffectiveRateDbRamEntry_u
T 1 78 0 1898 MuEffectiveRateDbRamEntry_u
T 1 78 0 1962 MuEffectiveRateDbRamEntry_u
T 1 78 0 2023 MuEffectiveRateDbRamEntry_u
T 1 78 0 2087 MuEffectiveRateDbRamEntry_u
T 1 78 0 2156 MuEffectiveRateDbRamEntry_u
T 1 78 0 2227 MuEffectiveRateDbRamEntry_u
T 1 78 0 2298 MuEffectiveRateDbRamEntry_u
T 1 78 0 2370 MuEffectiveRateDbRamEntry_u
T 1 78 0 2514 MuEffectiveRateDbRamEntry_u
T 1 78 0 2551 MuEffectiveRateDbRamEntry_u
T 1 78 0 2602 MuEffectiveRateDbRamEntry_u
T 1 78 0 2669 MuEffectiveRateDbRamEntry_u
T 1 78 0 2736 MuEffectiveRateDbRamEntry_u
T 1 78 0 2800 MuEffectiveRateDbRamEntry_u
T 1 78 0 2866 MuEffectiveRateDbRamEntry_u
T 1 78 0 2939 MuEffectiveRateDbRamEntry_u
T 1 78 0 3014 MuEffectiveRateDbRamEntry_u
T 1 78 0 3088 MuEffectiveRateDbRamEntry_u
T 1 78 0 3164 MuEffectiveRateDbRamEntry_u
T 1 78 0 3341 GroupCombinationTableEntry_t
T 1 29 20 1622 SetChannelParams_t
T 1 29 23 691 ChannelNotificationParams_t
T 1 29 23 706 ChannelNotificationParams_t
T 1 29 23 744 UmiHwDependentConfig_t
T 1 29 23 823 tpcConfig_t
T 1 29 23 845 UMI_HDK_CONFIG
T 1 29 23 1281 UMI_CALIBRATE_PARAMS
T 1 29 23 2394 cocReq_t
T 1 29 23 2489 UmiHwDependentConfig_t
T 1 29 23 3287 HdkSetChannelReqParams_t
T 1 29 23 3288 HdkSetChannelReqParams_t
T 1 6 0 255 BaaTxReport_t
T 1 10 2 302 UMI_ADD_VAP
T 1 10 2 419 UMI_SET_BSS
T 1 10 2 561 UMI_SET_WMM_PARAMETERS
T 1 10 2 688 UMI_REMOVE_VAP
T 1 10 2 809 UMI_STOP_VAP_TRAFFIC
T 1 17 2 173 metricFifoEntry_t
T 1 85 0 1057 UMI_GET_CHANNEL_LOAD_REQ
T 1 85 0 1075 UMI_GET_CHANNEL_LOAD_REQ
T 1 85 0 1157 UMI_POLL_CLIENT_t
T 1 85 0 1189 UMI_CONTINUOUS_INTERFERER
T 1 85 0 1258 UMI_RADAR_DETECTION
T 1 85 0 1293 UM_SET_CHAN_PARAMS
T 1 85 0 1319 UMI_SET_KEY
T 1 85 0 1434 UM_SET_CHAN_PARAMS
T 1 85 0 1473 UMI_GROUP_PN
T 1 85 0 1631 UMI_AOCS_INFO_t
T 1 85 0 3129 UMI_STA_ADD
T 1 85 0 3175 UMI_STA_REMOVE
T 1 85 0 3221 UMI_BEACON_SET
T 1 85 0 3511 UMI_REQUEST_SID
T 1 85 0 3563 UMI_REMOVE_SID
T 1 85 0 3602 UMI_AOCS_INFO_t
T 1 85 0 3621 UMI_TS_VAP_CONFIGURE
T 1 85 0 4266 UMI_STOP_TRAFFIC
T 1 85 0 4309 UMI_FRAME_CLASS_ERROR
T 1 85 0 4347 UMI_TKIP_MIC_FAILURE
T 1 85 0 5366 UMI_MULTICAST_MODE
T 1 85 0 5399 UMI_MULTICAST_ACTION
T 1 42 5 943 SequencerTxReport_t
T 1 42 5 2286 RateMask_t
T 1 42 4 1251 LaStationGroupCommonParams_t
T 1 42 4 1252 LaStationUspCommonParams_t
T 1 42 4 1256 LaStationUniqueParams_t
T 1 42 4 1260 LaGroupUniqueParams_t
T 1 42 4 2310 SequencerTxReport_t
T 1 42 16 1303 overridePendingDb_t
